kvmstart: Specify single-file method
Signed-off-by: Mel Gorman <mgorman@techsingularity.net>

diff --git a/shellpack_src/src/kvmstart/kvmstart-bench b/shellpack_src/src/kvmstart/kvmstart-bench
--- a/shellpack_src/src/kvmstart/kvmstart-bench
+++ b/shellpack_src/src/kvmstart/kvmstart-bench
@@ -31,7 +31,7 @@ if [ $MEMSIZE_STEPPING -lt $MIN_STEPSIZE ]; then
 fi
 
 if [ "$KVMSTART_PRETEST" != "" ]; then
-	eval $KVMSTART_PRETEST prepare --method $KVMSTART_METHOD $KVMSTART_PRETEST_ARGS || die "Failed to prepare $KVMSTART_PRETEST $KVMSTART_METHOD"
+	eval $KVMSTART_PRETEST prepare --method $KVMSTART_PRETEST_METHOD $KVMSTART_PRETEST_ARGS || die "Failed to prepare $KVMSTART_PRETEST $KVMSTART_PRETEST_METHOD"
 fi
 
 while [ $MEMSIZE -le $KVMSTART_MAX_MEMORY ]; do
@@ -49,8 +49,8 @@ while [ $MEMSIZE -le $KVMSTART_MAX_MEMORY ]; do
 		kvm-stop &> /dev/null
 
 		if [ "$KVMSTART_PRETEST" != "" ]; then
-			echo Pretest $KVMSTART_METHOD $KVMSTART_PRETEST_RUN_ARGS
-			eval $KVMSTART_PRETEST run --method $KVMSTART_METHOD $KVMSTART_PRETEST_RUN_ARGS || die "Failed to prepare $KVMSTART_PRETEST $KVMSTART_METHOD"
+			echo Pretest $KVMSTART_PRETEST_METHOD $KVMSTART_PRETEST_RUN_ARGS
+			eval $KVMSTART_PRETEST run --method $KVMSTART_PRETEST_METHOD $KVMSTART_PRETEST_RUN_ARGS || die "Failed to prepare $KVMSTART_PRETEST $KVMSTART_PRETEST_METHOD"
 		fi
 
 		echo Timing for memory size ${MEMSIZE_GB}g iteration $ITERATION/$KVMSTART_ITERATIONS
