specfem3d: Build example after configuration
Signed-off-by: Mel Gorman <mgorman@techsingularity.net>

diff --git a/shellpack_src/src/specfem3d/specfem3d-bench b/shellpack_src/src/specfem3d/specfem3d-bench
--- a/shellpack_src/src/specfem3d/specfem3d-bench
+++ b/shellpack_src/src/specfem3d/specfem3d-bench
@@ -6,26 +6,53 @@
 ###SHELLPACK monitor_hooks
 
 ###SHELLPACK check_install_required specfem3d-$VERSION
-###SHELLPACK init_complete
 
 ###SHELLPACK mpi_setup_deps SPECFEM3D_OPENMPI_VERSION
 ###SHELLPACK mpi_setup_env SPECFEM3D_MPI_PATH SPECFEM3D_MPI_LIBPATH
 ###SHELLPACK mpi_setup_shmem
 
+MPI_OPTS="--allow-run-as-root"
+
+if [ ! -e $SHELLPACK_DATA/model-$SPECFEM3D_MODEL ]; then
+	case $SPECFEM3D_MODEL in
+	s362)
+		# Copy model
+		cd $SHELLPACK_SOURCES/specfem3d-${VERSION}-installed/EXAMPLES || die "Failed to change to EXAMPLES directory"
+		rm -rf model-$SPECFEM3D_MODEL
+		cp -r global_s362ani_shakemovie model-$SPECFEM3D_MODEL || die "Failed to copy model"
+		cd model-$SPECFEM3D_MODEL || die "Failed to change to model"
+
+		# Configure model
+		sed -i -e /compute_nodes/d go_*_pbs.bash
+		sed -i -e /jobid/d go_*_pbs.bash
+		sed -i -e "s/mpiexec/mpiexec $MPI_OPTS/" go_*_pbs.bash
+		sed -i -e "s/^NCHUNKS.*/NCHUNKS = $SPECFEM3D_NCHUNKS/" DATA/Par_file
+		sed -i -e "s/^NEX_XI.*/NEX_XI = $SPECFEM3D_NEX_XI/" DATA/Par_file
+		sed -i -e "s/^NEX_ETA.*/NEX_ETA = $SPECFEM3D_NEX_ETA/" DATA/Par_file
+		sed -i -e "s/^NPROC_XI.*/NPROC_XI = $SPECFEM3D_NPROC_XI/" DATA/Par_file
+		sed -i -e "s/^NPROC_ETA.*/NPROC_ETA = $SPECFEM3D_NPROC_ETA/" DATA/Par_file
+		cp DATA/Par_file $LOGDIR_RESULTS/Par_file || die "Failed to copy DATA/Par_file"
+
+		# Build
+		echo Building global_s362ani_shakemovie
+		ROOTDIR=$SHELLPACK_SOURCES/specfem3d-${VERSION}-installed
+		ROOTDIR_ESCAPED=`echo "$ROOTDIR" | sed -e 's/\//\\\\\//g'`
+		sed -i -e "s/rootdir=.*/rootdir=$ROOTDIR_ESCAPED/" run_this_example.sh
+		./run_this_example.sh || die "Failed to execute global_s362ani_shakemovie run_this_example.sh"
+
+		# Make a copy
+		cd $SHELLPACK_SOURCES/specfem3d-${VERSION}-installed/EXAMPLES || die "Failed to change to EXAMPLES directory"
+		cp -r model-$SPECFEM3D_MODEL $SHELLPACK_DATA/model-$SPECFEM3D_MODEL
+		;;
+	*)
+		die "Unrecognised model $SPECFEM3D_MODEL"
+		;;
+	esac
+fi
+###SHELLPACK init_complete
+
 case $SPECFEM3D_MODEL in
 s362)
-	rm -rf $SHELLPACK_DATA/model-$SPECFEM3D_MODEL
-	cp -r $SHELLPACK_SOURCES/specfem3d-${VERSION}-installed/EXAMPLES/global_s362ani_shakemovie $SHELLPACK_DATA/model-$SPECFEM3D_MODEL ||
-		die "Failed to copy model"
-	cd $SHELLPACK_DATA/model-$SPECFEM3D_MODEL || die "Failed to change to model"
-	sed -i -e /compute_nodes/d go_*_pbs.bash
-	sed -i -e /jobid/d go_*_pbs.bash
-	sed -i -e "s/^NCHUNKS.*/NCHUNKS = $SPECFEM3D_NCHUNKS/" DATA/Par_file
-	sed -i -e "s/^NEX_XI.*/NEX_XI = $SPECFEM3D_NEX_XI/" DATA/Par_file
-	sed -i -e "s/^NEX_ETA.*/NEX_ETA = $SPECFEM3D_NEX_ETA/" DATA/Par_file
-	sed -i -e "s/^NPROC_XI.*/NPROC_XI = $SPECFEM3D_NPROC_XI/" DATA/Par_file
-	sed -i -e "s/^NPROC_ETA.*/NPROC_ETA = $SPECFEM3D_NPROC_ETA/" DATA/Par_file
-	cp DATA/Par_file $LOGDIR_RESULTS/Par_file || die "Failed to copy DATA/Par_file"
 	JOB_LIST="mesher:go_mesher_pbs.bash solver:go_solver_pbs.bash"
 	;;
 *)
@@ -33,11 +60,13 @@ s362)
 	;;
 esac
 
+
 cd $SHELLPACK_DATA/model-$SPECFEM3D_MODEL
 export PBS_O_WORKDIR=`pwd`
 
 monitor_pre_hook $LOGDIR_RESULTS $SPECFEM3D_MODEL
 for JOB in $JOB_LIST; do
+	echo Executing $JOB
 	NAME=`echo $JOB | awk -F : '{print $1}'`
 	SCRIPT=`echo $JOB | awk -F : '{print $2}'`
 
@@ -51,3 +80,5 @@ for JOB in $JOB_LIST; do
 	tar -czf $LOGDIR_RESULTS/output-$NAME.tar.gz OUTPUT_FILES
 done
 monitor_post_hook $LOGDIR_RESULTS $SPECFEM3D_MODEL
+cd $SHELLPACK_DATA
+rm -rf $SHELLPACK_DATA/model-$SPECFEM3D_MODEL
