dedup: Use xz compressed files
Signed-off-by: Mel Gorman <mgorman@suse.com>

diff --git a/shellpack_src/src/dedup/dedup-bench b/shellpack_src/src/dedup/dedup-bench
--- a/shellpack_src/src/dedup/dedup-bench
+++ b/shellpack_src/src/dedup/dedup-bench
@@ -20,31 +20,28 @@ TESTLIST=
 
 # Copy/download test file into the test partition
 if [ "$DEDUP_FILE" = "" ]; then
-	die DEDUP_FILE must be specified
+	die "DEDUP_FILE must be specified"
 fi
 if [ -e $DEDUP_FILE ]; then
 	mmtests_activity Copying
-	cp $DEDUP_FILE $SHELLPACK_TEMP/in.file.gz
-	if [ $? -ne 0 ]; then
-		die Failed to copy $DEDUP_FILE
-	fi
+	cp $DEDUP_FILE "$SHELLPACK_TEMP/in.file.xz" || die "Failed to copy $DEDUP_FILE"
 else
 	mmtests_activity Downloading
 	echo Downloading $DEDUP_FILE
-	wget -O $SHELLPACK_TEMP/in.file.gz -q $DEDUP_FILE
+	wget -O $SHELLPACK_TEMP/in.file.xz -q $DEDUP_FILE
 	if [ $? -ne 0 ]; then
-		wget -O $SHELLPACK_TEMP/in.file.gz $DEDUP_FILE
+		wget -O $SHELLPACK_TEMP/in.file.xz $DEDUP_FILE
 		if [ $? -ne 0 ]; then
-			die Failed to download $DEDUP_FILE
+			die "Failed to download $DEDUP_FILE"
 		fi
 	fi
 fi
-if [ "`file $SHELLPACK_TEMP/in.file.gz | grep gzip`" = "" ]; then
+if [ "`file $SHELLPACK_TEMP/in.file.xz | grep XZ`" = "" ]; then
 	echo Source file already uncompressed
-	mv $SHELLPACK_TEMP/in.file.gz $SHELLPACK_DATA/in.file
+	mv $SHELLPACK_TEMP/in.file.xz $SHELLPACK_DATA/in.file
 else
 	echo Uncompressing source file
-	gzip -dc $SHELLPACK_TEMP/in.file.gz >$SHELLPACK_DATA/in.file || die Failed to decompress source file
+	xzcat $SHELLPACK_TEMP/in.file.xz >$SHELLPACK_DATA/in.file || die "Failed to decompress source file"
 fi
 
 ###SHELLPACK threads_large_stride_begin $DEDUP_MIN_THREADS $DEDUP_MAX_THREADS
@@ -67,5 +64,5 @@ fi
 	###SHELLPACK iteration_end $ITERATIONS
 	monitor_post_hook $LOGDIR_RESULTS $NR_THREADS
 ###SHELLPACK threads_stride_end
-rm -f $SHELLPACK_DATA/in.file $SHELLPACK_TEMP/in.file.gz
+rm -f $SHELLPACK_DATA/in.file $SHELLPACK_TEMP/in.file.xz
 exit $SHELLPACK_SUCCESS
