dedup: By default, download a source file for parallel compression
Signed-off-by: Mel Gorman <mgorman@suse.de>

diff --git a/shellpack_src/src/dedup/dedup-bench b/shellpack_src/src/dedup/dedup-bench
--- a/shellpack_src/src/dedup/dedup-bench
+++ b/shellpack_src/src/dedup/dedup-bench
@@ -19,16 +19,51 @@ TESTLIST=
 # Include monitor hooks
 . $SHELLPACK_INCLUDE/include-monitor.sh
 
+# Copy/download test file into the test partition
+if [ "$DEDUP_FILE" = "" ]; then
+	die DEDUP_FILE must be specified
+fi
+if [ -e $DEDUP_FILE ]; then
+	mmtests_activity Copying
+	cp $DEDUP_FILE $SHELLPACK_TEMP/in.file.gz
+	if [ $? -ne 0 ]; then
+		die Failed to copy $DEDUP_FILE
+	fi
+else
+	mmtests_activity Downloading
+	echo Downloading $DEDUP_FILE
+	wget -O $SHELLPACK_TEMP/in.file.gz -q $DEDUP_FILE
+	if [ $? -ne 0 ]; then
+		die Failed to download $DEDUP_FILE
+	fi
+fi
+if [ "`file $SHELLPACK_TEMP/in.file.gz | grep gzip`" = "" ]; then
+	echo Source file already uncompressed
+	mv $SHELLPACK_TEMP/in.file.gz $SHELLPACK_TEMP/in.file
+else
+	echo Uncompressing source file
+	gunzip $SHELLPACK_TEMP/in.file.gz || die Failed to decompress source file
+fi
+
 ###SHELLPACK threads_large_stride_begin $DEDUP_MIN_THREADS $DEDUP_MAX_THREADS $DEDUP_ITERATIONS
 	monitor_pre_hook $LOGDIR_RESULTS $NR_THREADS
 	###SHELLPACK iteration_begin $DEDUP_ITERATIONS
 		echo Starting threads $NR_THREADS/$DEDUP_MAX_THREADS iteration $ITERATION/$DEDUP_ITERATIONS
-		$TIME_CMD -o $LOGDIR_RESULTS/dedup-${NR_THREADS}-$ITERATION.time \
-		    ./dedup -v -c -p -t $NR_THREADS -i $DEDUP_FILE -o $SHELLPACK_TEMP/tmp.file 2>&1 \
-		    tee $LOGDIR_RESULTS/dedup-${NR_THREADS}-${ITERATION}.log || die Failed to run dedup
-		rm $SHELLPACK_TEMP/tmp.file #cleanup
+		save_rc $TIME_CMD -o $LOGDIR_RESULTS/dedup-${NR_THREADS}-$ITERATION.time \
+		    $SHELLPACK_SOURCES/dedup-${VERSION}-installed/dedup \
+			-v -c -p -t $NR_THREADS \
+			-i $SHELLPACK_TEMP/in.file  \
+			-o $SHELLPACK_TEMP/out.file \
+				2>&1 | tee $LOGDIR_RESULTS/dedup-${NR_THREADS}-${ITERATION}.log
+		recover_rc
+		if [ $? -ne 0 ]; then
+			die Failed to run dedup
+		fi
 
+		#cleanup
+		rm $SHELLPACK_TEMP/out.file
 	###SHELLPACK iteration_end $ITERATIONS
 	monitor_post_hook $LOGDIR_RESULTS $NR_THREADS
 ###SHELLPACK threads_stride_end
+rm $SHELLPACK_TEMP/in.file
 exit $SHELLPACK_SUCCESS
