iperf3: implement TCP and UDP throughput testing
The iperf3 benchmark was modified to iterate over buffer sizes and
bitrates, in addition to parallel client streams. The default buffer sizes
- 200, 1420 and 8920 bytes - correspond to the commonly used Ethernet
frame sizes (when taking into account the size of the IPv6 header, usually
40 bytes, and the size of the TCP header, usually 32 bytes). By default,
there is no throughput limit so maximum throughput is measured. Two new
config file templates were written. The remaining config files are
autogenerated. A perl extraction script was written to reflect the changes
made to the iperf3 result files. Variables in config files and options in
the driver script were renamed to express intentions in terms used by the
iperf3 manual page.

Signed-off-by: Jiri Wiesner <jwiesner@suse.de>
Signed-off-by: Mel Gorman <mgorman@techsingularity.net>

diff --git a/shellpack_src/src/iperf3/iperf3-bench b/shellpack_src/src/iperf3/iperf3-bench
--- a/shellpack_src/src/iperf3/iperf3-bench
+++ b/shellpack_src/src/iperf3/iperf3-bench
@@ -1,73 +1,79 @@
 #!/bin/bash
 # This script installs iperf and runs the regression tests
 ###SHELLPACK preamble iperf3-bench 3.14
-IPV_SWITCH=-4
 
 TASKSET_SERVER=
 TASKSET_CLIENT=
-SERVER_HOST=127.0.0.1
-if [ "$REMOTE_SERVER_HOST" != "" ]; then
-	SERVER_HOST=$REMOTE_SERVER_HOST
-fi
 
 ###SHELLPACK parseargBegin
 ###SHELLPACK parseargInstall
 ###SHELLPACK parseargBindings
+###SHELLPACK parseargParam    --net-protocol	IPERF_NET_PROTOCOL
 ###SHELLPACK parseargParam    --protocol	IPERF_PROTOCOL
-###SHELLPACK parseargParam    --msg-size	IPERF_MESSAGE_SIZE
-###SHELLPACK parseargParam    --msg-rate	IPERF_MESSAGE_RATE
-###SHELLPACK parseargParam    --min-client	IPERF_MIN_CLIENTS
-###SHELLPACK parseargParam    --max-client	IPERF_MAX_CLIENTS
+###SHELLPACK parseargParam    --buffer-sizes	IPERF_BUFFER_SIZES
+###SHELLPACK parseargParam    --bitrates	IPERF_BITRATES
+###SHELLPACK parseargParam    --min-streams	IPERF_MIN_STREAMS
+###SHELLPACK parseargParam    --max-streams	IPERF_MAX_STREAMS
 ###SHELLPACK parseargParam    --duration	IPERF_DURATION
+###SHELLPACK parseargParam    --iterations	IPERF_ITERATIONS
 ###SHELLPACK parseargEnd
 ###SHELLPACK monitor_hooks
 
 ###SHELLPACK check_install_required iperf3-${VERSION}
 ###SHELLPACK init_complete
 
-BUFFER_SIZES=`echo $BUFFER_SIZES | sed -e 's/,/ /g'`
-
-export REMOTE_SERVER_SCRIPT=$SCRIPTDIR/shellpacks/shellpack-bench-iperf3
-case $SERVERSIDE_COMMAND in
-start)
+kill_iperf3_server()
+{
 	if [ -e /tmp/iperf3.pid ]; then
 		IPERF3_PID=`cat /tmp/iperf3.pid`
 		echo Killing server pid $IPERF3_PID
 		kill $IPERF3_PID
-		rm /tmp/iperf3.pid
+		rm -f /tmp/iperf3.pid
 	fi
+}
+
+case $IPERF_NET_PROTOCOL in
+ipv4)
+	NET_PROTOCOL_OPT="-4"
+	SERVER_HOST=127.0.0.1
+	;;
+ipv6)
+	NET_PROTOCOL_OPT="-6"
+	SERVER_HOST=::1
+	;;
+esac
+if [ "$REMOTE_SERVER_HOST" != "" ]; then
+	SERVER_HOST=$REMOTE_SERVER_HOST
+fi
+
+export REMOTE_SERVER_SCRIPT=$SCRIPTDIR/shellpacks/shellpack-bench-iperf3
+case $SERVERSIDE_COMMAND in
+start)
+	kill_iperf3_server
 
 	echo Starting server
 	mmtests_activity iperf3-$SERVERSIDE_NAME
 	monitor_pre_hook $LOGDIR_RESULTS iperf3-$SERVERSIDE_NAME
 	IPERFROOT=$SHELLPACK_SOURCES/iperf3-${VERSION}-installed 
-	$TASKSET_SERVER $IPERFROOT/bin/iperf3 -s $PROTO -D $IPV_SWITCH -I /tmp/iperf3.pid || die "Failed to start iperf3 server"
+	$TASKSET_SERVER $IPERFROOT/bin/iperf3 -s -D $NET_PROTOCOL_OPT -I /tmp/iperf3.pid \
+		|| die "Failed to start iperf3 server"
 	exit $SHELLPACK_SUCCESS
 	;;
 stop)
 	monitor_post_hook $LOGDIR_RESULTS iperf3-$SERVERSIDE_NAME
-	if [ -e /tmp/iperf3.pid ]; then
-		IPERF3_PID=`cat /tmp/iperf3.pid`
-		echo Killing server pid $IPERF3_PID
-		kill $IPERF3_PID
-		rm /tmp/iperf3.pid
-	fi
+	kill_iperf3_server
 	exit $SHELLPACK_SUCCESS
 	;;
 flush)
 	exit $SHELLPACK_SUCCESS
 	;;
 none)
-	if [ -e /tmp/iperf3.pid ]; then
-		IPERF3_PID=`cat /tmp/iperf3.pid`
-		echo Killing server pid $IPERF3_PID
-		kill $IPERF3_PID
-		rm /tmp/iperf3.pid
-	fi
+	kill_iperf3_server
 
 	echo Starting server
 	IPERFROOT=$SHELLPACK_SOURCES/iperf3-${VERSION}-installed 
-	$TASKSET_SERVER $IPERFROOT/bin/iperf3 -s $PROTO -D $IPV_SWITCH || die "Failed to start iperf3 server"
+	$TASKSET_SERVER $IPERFROOT/bin/iperf3 -s -D $NET_PROTOCOL_OPT -I /tmp/iperf3.pid \
+		|| die "Failed to start iperf3 server"
 	sleep 2
 	;;
 *)
@@ -75,30 +81,41 @@ none)
 	;;
 esac
 
-###SHELLPACK threads_powertwo_begin $IPERF_MIN_CLIENTS $IPERF_MAX_CLIENTS
-	mmtests_server_ctl start --serverside-name $IPERF_PROTOCOL-$IPERF_MESSAGE_SIZE-$IPERF_MESSAGE_RATE
-	mmtests_activity msg-$IPERF_MESSAGE_SIZE-$RATE
-	PROTOCOL_OPT=
-	MSGSIZE_OPT="-l $IPERF_MESSAGE_SIZE"
-	MSGRATE_OPT="-b $IPERF_MESSAGE_RATE"
-	DURATION_OPT="-t $IPERF_DURATION"
-	SOCKETSIZE_OPT=
+echo $IPERF_PROTOCOL > $LOGDIR_RESULTS/protocols
 
-	if [ "$IPERF_PROTOCOL" = "udp" ]; then
-		PROTOCOL_OPT="-u"
-	fi
+for SIZE in ${IPERF_BUFFER_SIZES//,/ }; do
+for RATE in ${IPERF_BITRATES//,/ }; do
+###SHELLPACK threads_powertwo_begin $IPERF_MIN_STREAMS $IPERF_MAX_STREAMS
+	mmtests_server_ctl start --serverside-name $IPERF_PROTOCOL-$SIZE-$RATE
+	mmtests_activity msg-$SIZE-$RATE
+	PROTOCOL_OPT=
+	LENGTH_OPT="-l $SIZE"
+	BITRATE_OPT="-b $RATE"
+	TIME_OPT="-t $IPERF_DURATION"
+	OMIT_OPT=
+
+	case $IPERF_PROTOCOL in
+	tcp) OMIT_OPT="-O 2";;
+	udp) PROTOCOL_OPT="-u";;
+	esac
 		
 	IPERF3_OPTS="-c $SERVER_HOST \
-		$MSGSIZE_OPT $MSGRATE_OPT $SOCKETSIZE_OPT \
-		$PROTOCOL_OPT $DURATION_OPT \
-		-P $NR_THREADS --get-server-output -V"
+		$NET_PROTOCOL_OPT $PROTOCOL_OPT $LENGTH_OPT $BITRATE_OPT \
+		$TIME_OPT $OMIT_OPT -P $NR_THREADS \
+		-f m --get-server-output -V"
 	echo $TASKSET_CLIENT "iperf3" $IPERF3_OPTS
-	monitor_pre_hook $LOGDIR_RESULTS $IPERF_PROTOCOL-$IPERF_MESSAGE_SIZE-$IPERF_MESSAGE_RATE-$NR_THREADS
+	monitor_pre_hook $LOGDIR_RESULTS $IPERF_PROTOCOL-$SIZE-$RATE-$NR_THREADS
+###SHELLPACK iteration_begin $IPERF_ITERATIONS
+	echo Running test $IPERF_PROTOCOL iteration $ITERATION/$IPERF_ITERATIONS size $SIZE bitrate $RATE streams $NR_THREADS
 	eval $TASKSET_CLIENT $IPERFROOT/bin/iperf3 $IPERF3_OPTS \
-			2>&1 > $LOGDIR_RESULTS/$IPERF_PROTOCOL-$IPERF_MESSAGE_SIZE-$IPERF_MESSAGE_RATE-$NR_THREADS \
+			2>&1 > $LOGDIR_RESULTS/$IPERF_PROTOCOL-$SIZE-$RATE-$NR_THREADS.$ITERATION \
 			|| die "Failed to run iperf3"
-	monitor_post_hook $LOGDIR_RESULTS $IPERF_PROTOCOL-$IPERF_MESSAGE_SIZE-$IPERF_MESSAGE_RATE-$NR_THREADS
-	mmtests_server_ctl stop --serverside-name $IPERF_PROTOCOL-$IPERF_MESSAGE_SIZE-$IPERF_MESSAGE_RATE
+###SHELLPACK iteration_end
+	monitor_post_hook $LOGDIR_RESULTS $IPERF_PROTOCOL-$SIZE-$RATE-$NR_THREADS
+	mmtests_server_ctl stop --serverside-name $IPERF_PROTOCOL-$SIZE-$RATE
 ###SHELLPACK threads_powertwo_end
+done
+done
 
+kill_iperf3_server
 exit $SHELLPACK_SUCCESS
