use right openmpi version for building

diff --git a/shellpack_src/src/openfoambuild/openfoambuild-install b/shellpack_src/src/openfoambuild/openfoambuild-install
--- a/shellpack_src/src/openfoambuild/openfoambuild-install
+++ b/shellpack_src/src/openfoambuild/openfoambuild-install
@@ -24,7 +24,13 @@ if [ ! -e ThirdParty ]; then
 fi
 
 source etc/bashrc || die "Failed to source etc/bashrc"
-module load gnu openmpi || die "Failed to load openmi module"
+if [ "$OPENFOAM_OPENMPI_VERSION" = "openmpi3" ]; then
+	module load gnu openmpi/3 || die "Could not load openmpi/3 module"
+elif [ "$OPENFOAM_OPENMPI_VERSION" = "openmpi2" ]; then
+	module load gnu openmpi/2 || die "Could not load openmpi/2 module"
+else
+	die "\$OPENFOAM_OPENMPI_VERSION must be openmpi2 or openmpi3"
+fi
 cd "$WM_PROJECT_DIR" || die "Failed to change to WM_PROJECT_DIR"
 foamSystemCheck || die "Failed foamSystemCheck"
 ./Allwmake -s -l -j || die "Failed to build Allwmake"
