pft: Log runtime command line arguements
Signed-off-by: Mel Gorman <mgorman@techsingularity.net>

diff --git a/shellpack_src/src/pft/pft-bench b/shellpack_src/src/pft/pft-bench
--- a/shellpack_src/src/pft/pft-bench
+++ b/shellpack_src/src/pft/pft-bench
@@ -23,16 +23,17 @@ fi
 cd $SHELLPACK_SOURCES/pft-${VERSION}-installed || die Failed to cd to pft directory
 ###SHELLPACK threads_large_stride_begin $PFT_MIN_CLIENTS $PFT_MAX_CLIENTS
 	mmtests_activity client ${NR_THREADS}
+	BENCH_CMD="./pft -m $PFT_MAPPING_SIZE $PFT_CLIENT_SWITCH $NR_THREADS"
+	log_cmd $BENCH_CMD
+
 	monitor_pre_hook $LOGDIR_RESULTS ${NR_THREADS}
 	echo -n > $LOGDIR_RESULTS/pft-${NR_THREADS}.log
 	for ITER in `seq 1 $PFT_ITERATIONS`; do
-		( ./pft \
-			-m			$PFT_MAPPING_SIZE \
-			$PFT_CLIENT_SWITCH	${NR_THREADS}		  \
-			2>&1 | tee -a $LOGDIR_RESULTS/pft-${NR_THREADS}.log ) \
-				|| die Failed to run pft
+		( $BENCH_CMD 2>&1 | tee -a $LOGDIR_RESULTS/pft-${NR_THREADS}.log ) \
+			|| die "Failed to run pft"
 	done
 	monitor_post_hook $LOGDIR_RESULTS ${NR_THREADS}
+
 	CLIENT=$((CLIENT+1))
 ###SHELLPACK threads_stride_end
 
