Refresh all benchmarks
Signed-off-by: Mel Gorman <mgorman@techsingularity.net>

diff --git a/shellpacks/shellpack-install-lhcs b/shellpacks/shellpack-install-lhcs
--- a/shellpacks/shellpack-install-lhcs
+++ b/shellpacks/shellpack-install-lhcs
@@ -3,17 +3,32 @@
 P=lhcs-install
 DEFAULT_VERSION=1.6
 . $SHELLPACK_INCLUDE/common.sh
+TIME_CMD=`which time`
+if [ "$TIME_CMD" = "" ]; then
+        TIMEFORMAT="%2Uuser %2Ssystem %Relapsed %P%%CPU"
+        TIME_CMD="time"
+fi
 WEB_LOCATION=https://raw.githubusercontent.com/autotest/autotest-client-tests/master/cpu_hotplug
 MIRROR_LOCATION="$WEBROOT/lhcs/"
 
 # Basic argument parser
 TASKSET_SERVER=
 TASKSET_CLIENT=
+SERVERSIDE_COMMAND=none
+SERVERSIDE_NAME=`date +%Y%m%d-%H%M-%S`
 
 while [ "$1" != "" ]; do
 	case "$1" in
 	-v)
 		VERSION=$2
+		shift 2
+		;;
+	--serverside-command)
+		SERVERSIDE_COMMAND=$2
+		shift 2
+		;;
+	--serverside-name)
+		SERVERSIDE_NAME=$2
 		shift 2
 		;;
 	*)
@@ -31,13 +46,13 @@ fi
 
 # Unconditionally fetch the tar to find out the real version number
 TARFILE=lhcs_regression-${VERSION}.tgz
-sources_fetch $WEB_LOCATION/$TARFILE $MIRROR_LOCATION/$TARFILE $SHELLPACK_SOURCES/$TARFILE
+sources_fetch $WEB_LOCATION/$TARFILE $MIRROR_LOCATION/$TARFILE $SHELLPACK_SOURCES/$TARFILE $WEB_LOCATION_ALT/$TARFILE
 cd $SHELLPACK_SOURCES
 tar -xf $TARFILE
 if [ $? -ne 0 ]; then
-        error "$P: tar xf lhcs_regression-${VERSION}.tgz failed"
-        popd > /dev/null
-        exit $SHELLPACK_ERROR
+	error "$P: tar xf lhcs_regression-${VERSION}.tgz failed"
+	popd > /dev/null
+	exit $SHELLPACK_ERROR
 fi
 
 # Rename directory to something we expect.
@@ -47,4 +62,4 @@ pushd lhcs-${VERSION}-installed > /dev/null || die Failed to rename tar
 
 echo lhcs installed successfully
 #### Description Linux Hotplug CPU Support
-#### Details lhcs 12
+#### Details lhcs 13
diff --git a/shellpacks/shellpack-install-pft b/shellpacks/shellpack-install-pft
--- a/shellpacks/shellpack-install-pft
+++ b/shellpacks/shellpack-install-pft
@@ -3,17 +3,32 @@
 P=pft-install
 DEFAULT_VERSION=0.12x
 . $SHELLPACK_INCLUDE/common.sh
+TIME_CMD=`which time`
+if [ "$TIME_CMD" = "" ]; then
+        TIMEFORMAT="%2Uuser %2Ssystem %Relapsed %P%%CPU"
+        TIME_CMD="time"
+fi
 GIT_LOCATION=https://github.com/gormanm/pft
 MIRROR_LOCATION="$WEBROOT/pft/$TARFILE"
 
 # Basic argument parser
 TASKSET_SERVER=
 TASKSET_CLIENT=
+SERVERSIDE_COMMAND=none
+SERVERSIDE_NAME=`date +%Y%m%d-%H%M-%S`
 
 while [ "$1" != "" ]; do
 	case "$1" in
 	-v)
 		VERSION=$2
+		shift 2
+		;;
+	--serverside-command)
+		SERVERSIDE_COMMAND=$2
+		shift 2
+		;;
+	--serverside-name)
+		SERVERSIDE_NAME=$2
 		shift 2
 		;;
 	*)
@@ -35,9 +50,9 @@ git_fetch $GIT_LOCATION pft-${VERSION}-installed $MIRROR_LOCATION/$TARFILE $SHEL
 cd $SHELLPACK_SOURCES
 tar -xf $TARFILE
 if [ $? -ne 0 ]; then
-        error "$P: tar xf pft-${VERSION}.tar.gz failed"
-        popd > /dev/null
-        exit $SHELLPACK_ERROR
+	error "$P: tar xf pft-${VERSION}.tar.gz failed"
+	popd > /dev/null
+	exit $SHELLPACK_ERROR
 fi
 
 # Rename directory to something we expect.
@@ -146,4 +161,4 @@ fi
 
 echo pft installed successfully
 #### Description pft
-#### Details pft 11
+#### Details pft 12
diff --git a/shellpacks/shellpack-install-specjbb b/shellpacks/shellpack-install-specjbb
--- a/shellpacks/shellpack-install-specjbb
+++ b/shellpacks/shellpack-install-specjbb
@@ -3,17 +3,32 @@
 P=specjvm-install
 DEFAULT_VERSION=2005_kitv1.07
 . $SHELLPACK_INCLUDE/common.sh
+TIME_CMD=`which time`
+if [ "$TIME_CMD" = "" ]; then
+        TIMEFORMAT="%2Uuser %2Ssystem %Relapsed %P%%CPU"
+        TIME_CMD="time"
+fi
 WEB_LOCATION="NOT_AVAILABLE"
 MIRROR_LOCATION="$WEBROOT/spec"
 
 # Basic argument parser
 TASKSET_SERVER=
 TASKSET_CLIENT=
+SERVERSIDE_COMMAND=none
+SERVERSIDE_NAME=`date +%Y%m%d-%H%M-%S`
 
 while [ "$1" != "" ]; do
 	case "$1" in
 	-v)
 		VERSION=$2
+		shift 2
+		;;
+	--serverside-command)
+		SERVERSIDE_COMMAND=$2
+		shift 2
+		;;
+	--serverside-name)
+		SERVERSIDE_NAME=$2
 		shift 2
 		;;
 	*)
@@ -31,13 +46,13 @@ fi
 
 # Unconditionally fetch the tar to find out the real version number
 TARFILE=SPECjbb${VERSION}.tar.gz
-sources_fetch $WEB_LOCATION/$TARFILE $MIRROR_LOCATION/$TARFILE $SHELLPACK_SOURCES/$TARFILE
+sources_fetch $WEB_LOCATION/$TARFILE $MIRROR_LOCATION/$TARFILE $SHELLPACK_SOURCES/$TARFILE $WEB_LOCATION_ALT/$TARFILE
 cd $SHELLPACK_SOURCES
 tar -xf $TARFILE
 if [ $? -ne 0 ]; then
-        error "$P: tar xf SPECjbb${VERSION}.tar.gz failed"
-        popd > /dev/null
-        exit $SHELLPACK_ERROR
+	error "$P: tar xf SPECjbb${VERSION}.tar.gz failed"
+	popd > /dev/null
+	exit $SHELLPACK_ERROR
 fi
 
 # Rename directory to something we expect.
@@ -47,4 +62,4 @@ pushd specjbb-${VERSION}-installed > /dev/null || die Failed to rename tar
 
 exit $SHELLPACK_SUCCESS
 #### Description SPECjbb
-#### Details specjbb 27
+#### Details specjbb 28
