nas: Add support for running with openmpi
Signed-off-by: Mel Gorman <mgorman@suse.de>

diff --git a/shellpacks/shellpack-install-nas b/shellpacks/shellpack-install-nas
--- a/shellpacks/shellpack-install-nas
+++ b/shellpacks/shellpack-install-nas
@@ -1,17 +1,47 @@
 #!/bin/bash
-
-P='nas-install'
-WEB_LOCATION="NOT_AVAILABLE"
-MIRROR_LOCATION="$WEBROOT/nas/NPB3.3.tar.gz"
-
+P=nas-install
+DEFAULT_VERSION=3.3
 . $SHELLPACK_INCLUDE/common.sh
+WEB_LOCATION="NOT_AVAILABLE"
+MIRROR_LOCATION="$WEBROOT/nas/"
+
+install-depends gcc-fortran
+
+# Basic argument parser
+while [ "$1" != "" ]; do
+	case "$1" in
+	-v)
+		VERSION=$2
+		shift 2
+		;;
+	*)
+		echo Unrecognised option: $1
+		shift
+	esac
+done
+if [ -z "$VERSION" ]; then
+	VERSION=$DEFAULT_VERSION
+fi
 
 cd $SHELLPACK_SOURCES || die Sources directory does not exist
 rm -rf NPB3.3
 
-sources_fetch $WEB_LOCATION $MIRROR_LOCATION $SHELLPACK_SOURCES/NPB3.3.tar.gz
-tar xf NPB3.3.tar.gz || die "$P: Failed to unpack NPB"
+# Unconditionally fetch the tar to find out the real version number
+TARFILE=NPB${VERSION}.tar.gz
+sources_fetch $WEB_LOCATION/$TARFILE $MIRROR_LOCATION/$TARFILE $SHELLPACK_SOURCES/$TARFILE
+cd $SHELLPACK_SOURCES
+tar -xf $TARFILE
+if [ $? -ne 0 ]; then
+        error "$P: tar xf NPB${VERSION}.tar.gz failed"
+        popd > /dev/null
+        exit $SHELLPACK_ERROR
+fi
+
+# Rename directory to something we expect.
+DST_DIR=`tar tf $TARFILE | head -n 1 | awk -F / '{print $1}'`
+mv $DST_DIR nas-$VERSION-installed
+pushd nas-$VERSION-installed > /dev/null || die Failed to rename tar
 
 exit $SHELLPACK_SUCCESS
 #### Description NAS Parallel Benchmark
-#### Details nas 20
+#### Details nas 31
