Update sourceforge download paths
Signed-off-by: Mel Gorman <mgorman@techsingularity.net>

diff --git a/shellpacks/shellpack-install-ltp b/shellpacks/shellpack-install-ltp
--- a/shellpacks/shellpack-install-ltp
+++ b/shellpacks/shellpack-install-ltp
@@ -3,52 +3,90 @@
 P=ltp-install
 INSTALL_TESTS=0
 VERSION=
-DEFAULT_VERSION=full-20120104
-WEB_LOCATION=http://netcologne.dl.sourceforge.net/project/ltp/LTP%20Source/ltp-20120104/ltp-full-20120104.bz2
+DEFAULT_VERSION=20150420
+WEB_LOCATION=http://heanet.dl.sourceforge.net/sourceforge/ltp
 MIRROR_LOCATION=$WEBROOT/ltp
 LTP_SOURCE_REPO=http://mcp/mmtests-mirror
 . $SHELLPACK_INCLUDE/common.sh
 
 # Basic argument parser
-while [ "$1" != "" ]; do
-  case "$1" in
-    -v)
-            VERSION=$2
-	    shift 2
-	    ;;
-    *)
-            echo Unrecognised option: $1
-	    shift
-  esac
-done
+TASKSET_SERVER=
+TASKSET_CLIENT=
+SERVERSIDE_COMMAND=none
+SERVERSIDE_NAME=`date +%Y%m%d-%H%M-%S`
 
+while [ "$1" != "" ]; do
+	case "$1" in
+	-v)
+		VERSION=$2
+		shift 2
+		;;
+	--serverside-command)
+		SERVERSIDE_COMMAND=$2
+		shift 2
+		;;
+	--serverside-name)
+		SERVERSIDE_NAME=$2
+		shift 2
+		;;
+	--install-only)
+		INSTALL_ONLY=yes
+		shift
+		;;
+	--install-force)
+		INSTALL_FORCE=yes
+		shift
+		;;
+	*)
+		echo Unrecognised option: $1
+		shift
+	esac
+done
+if [ "$TASKSET_SERVER" != "" ]; then
+	echo TASKSET_SERVER: $TASKSET_SERVER
+	echo TASKSET_CLIENT: $TASKSET_CLIENT
+fi
 if [ -z "$VERSION" ]; then
 	VERSION=$DEFAULT_VERSION
 fi
-SUB_VERSION=`echo $VERSION | sed -e 's/full-//'`
-TARFILE=ltp-${VERSION}.bz2
-WEB_LOCATION=$WEB_LOCATION/ltp-$SUB_VERSION/ltp-$VERSION.bz2
 
-MIRROR_LOCATION=$MIRROR_LOCATION/$TARFILE
-sources_fetch $WEB_LOCATION $MIRROR_LOCATION $SHELLPACK_SOURCES/$TARFILE
-
+# Unconditionally fetch the tar to find out the real version number
+TARFILE=ltp-full-${VERSION}.tar.bz2
+sources_fetch $WEB_LOCATION/$TARFILE $MIRROR_LOCATION/$TARFILE $SHELLPACK_SOURCES/$TARFILE
 cd $SHELLPACK_SOURCES
-tar xf $TARFILE || die $P: tar xf ltp-$VERSION.tar.gz failed
+tar -xf $TARFILE
+if [ $? -ne 0 ]; then
+	error "$P: tar xf ltp-full-${VERSION}.tar.bz2 failed"
+	popd > /dev/null
+	exit $SHELLPACK_ERROR
+fi
 
 # Rename directory to something we expect.
-DST_DIR=`tar tf $TARFILE | head -n 1`
-[ "$DST_DIR" != "ltp-${VERSION}/" ] && mv $DST_DIR ltp-${VERSION}
-
-# Build the library
-pushd ltp-${VERSION} > /dev/null
-
-# Build
-INSTALLPATH=$SHELLPACK_SOURCES/ltp-${VERSION}-installed
-rm -rf $INSTALLPATH
-./configure --prefix=$INSTALLPATH  || die configure failed
-make -j4 || die build failed
-make install || die install failed
+DST_DIR=`tar tf $TARFILE | head -n 1 | awk -F / '{print $1}'`
+mv $DST_DIR ltp-$VERSION
+pushd ltp-$VERSION > /dev/null || die Failed to rename tar
+pushd $SHELLPACK_SOURCES/ltp-$VERSION || die Failed to change to source directory
+export CFLAGS="-O2 $CFLAGS_MMTESTS_EXTRA"
+eval ./configure --prefix=$SHELLPACK_SOURCES/ltp-${VERSION}-installed 
+if [ $? -ne 0 ]; then
+	error "$P: configure failed"
+	popd > /dev/null
+	exit $SHELLPACK_ERROR
+fi
+unset CFLAGS
+make -j$NUMCPUS 
+if [ $? -ne 0 ]; then
+	error "$P: make failed"
+	popd > /dev/null
+	exit $SHELLPACK_ERROR
+fi
+make install
+if [ $? -ne 0 ]; then
+	error "$P: make install failed"
+	popd > /dev/null
+	exit $SHELLPACK_ERROR
+fi
 
 echo LTP installed successfully
 #### Description LTP Regression Test Suite
-#### Details ltp 21
+#### Details ltp 22
diff --git a/shellpacks/shellpack-install-tiobench b/shellpacks/shellpack-install-tiobench
--- a/shellpacks/shellpack-install-tiobench
+++ b/shellpacks/shellpack-install-tiobench
@@ -3,17 +3,32 @@
 P=tiobench-install
 DEFAULT_VERSION=0.3.3
 . $SHELLPACK_INCLUDE/common.sh
-WEB_LOCATION=http://garr.dl.sourceforge.net/project/tiobench/tiobench/
+TIME_CMD=`which time`
+if [ "$TIME_CMD" = "" ]; then
+        TIMEFORMAT="%2Uuser %2Ssystem %Relapsed %P%%CPU"
+        TIME_CMD="time"
+fi
+WEB_LOCATION=http://heanet.dl.sourceforge.net/sourceforge/tiobench
 MIRROR_LOCATION="$WEBROOT/tiobench/"
 
 # Basic argument parser
 TASKSET_SERVER=
 TASKSET_CLIENT=
+SERVERSIDE_COMMAND=none
+SERVERSIDE_NAME=`date +%Y%m%d-%H%M-%S`
 
 while [ "$1" != "" ]; do
 	case "$1" in
 	-v)
 		VERSION=$2
+		shift 2
+		;;
+	--serverside-command)
+		SERVERSIDE_COMMAND=$2
+		shift 2
+		;;
+	--serverside-name)
+		SERVERSIDE_NAME=$2
 		shift 2
 		;;
 	*)
@@ -35,9 +50,9 @@ sources_fetch $WEB_LOCATION/$VERSION/$TARFILE $MIRROR_LOCATION/$TARFILE $SHELLPA
 cd $SHELLPACK_SOURCES
 tar -xf $TARFILE
 if [ $? -ne 0 ]; then
-        error "$P: tar xf tiobench-${VERSION}.tar.gz failed"
-        popd > /dev/null
-        exit $SHELLPACK_ERROR
+	error "$P: tar xf tiobench-${VERSION}.tar.gz failed"
+	popd > /dev/null
+	exit $SHELLPACK_ERROR
 fi
 
 # Rename directory to something we expect.
@@ -117,4 +132,4 @@ fi
 
 echo tiobench installed successfully
 #### Description tiobench
-#### Details tiobench 19
+#### Details tiobench 20
