Wire up iozone benchmark
Signed-off-by: Jan Kara <jack@suse.cz>
Signed-off-by: Mel Gorman <mgorman@suse.de>

diff --git a/shellpacks/shellpack-bench-iozone b/shellpacks/shellpack-bench-iozone
--- a/shellpacks/shellpack-bench-iozone
+++ b/shellpacks/shellpack-bench-iozone
@@ -1,145 +1,83 @@
 #!/bin/bash
-# This script installs iozone and runs the regression tests
-
+# This script installs iozone and whatever
 P=iozone-bench
-VERSION=3_327
+DEFAULT_VERSION=3_428
 . $SHELLPACK_INCLUDE/common.sh
 
-MEMTOTAL_BYTES=`free -b | grep Mem: | awk '{print $2}'`
-MEMTOTAL_KBYTES=$((MEMTOTAL_BYTES/1024))
-MAXIMUM_FILESIZE=$((MEMTOTAL_KBYTES*3/2))
-NUMCPUS=`grep processor /proc/cpuinfo | wc -l`
-RECORD_LEN=4
-THREADS=1
-TESTS=0,1,2,3
-WORKFILE_PREFIX=
-EXTRA_OPTS=
-TEST_TYPE=full-automatic
+# Basic argument parser
+TASKSET_SERVER=
+TASKSET_CLIENT=
 
-# Basic args parser
 while [ "$1" != "" ]; do
 	case "$1" in
-		-v)
-			VERSION=$2
-			shift 2;;
-		--fast)
-			MAXIMUM_FILESIZE=$((MEMTOTAL_KBYTES))
-			shift
-			;;
-		--faster)
-			MAXIMUM_FILESIZE=$((MEMTOTAL_KBYTES*3/4))
-			shift
-			;;
-		--fastest)
-			MAXIMUM_FILESIZE=$((MEMTOTAL_KBYTES/2))
-			shift
-			;;
-		--filesize)
-			MAXIMUM_FILESIZE=$2
-			shift 2
-			;;
-		--max-filesize-kbytes)
-			MAXIMUM_FILESIZE=$2
-			shift 2
-			;;
-		--record-length)
-			RECORD_LEN=$2
-			shift 2
-			;;
-		--workfile-prefix)
-			WORKFILE_PREFIX="-f $2"
-			shift 2
-			;;
-		--tests)
-			TESTS=$2
-			shift 2
-			;;
-		--full-automatic)
-			TEST_TYPE=full-automatic
-			shift
-			;;
-		--thread-scalability)
-			TEST_TYPE=thread-scalability
-			shift
-			;;
-		--single)
-			TEST_TYPE=single
-			shift
-			;;
-		--threads)
-			THREADS=$2
-			shift 2
-			;;
-		--throughput)
-			THROUGHPUT_IOZONE=yes
-			TESTS=0,1
-			shift
-			;;
-		--flush)
-			EXTRA_OPTS="$EXTRA_OPTS -e"
-			shift
-			;;
-		--show-thread-throughput)
-			EXTRA_OPTS="$EXTRA_OPTS -C"
-			shift
-			;;
-		*)	echo Unrecognised option: $1; shift
+	-v)
+		VERSION=$2
+		shift 2
+		;;
+	--install-only)
+		INSTALL_ONLY=yes
+		shift
+		;;
+	--install-force)
+		INSTALL_FORCE=yes
+		shift
+		;;
+	*)
+		echo Unrecognised option: $1
+		shift
 	esac
 done
+if [ "$TASKSET_SERVER" != "" ]; then
+	echo TASKSET_SERVER: $TASKSET_SERVER
+	echo TASKSET_CLIENT: $TASKSET_CLIENT
+fi
+if [ -z "$VERSION" ]; then
+	VERSION=$DEFAULT_VERSION
+fi
 
-# Install if necessary
+if [ "$INSTALL_FORCE" = "yes" ]; then
+	rm -rf $SHELLPACK_SOURCES/iozone-${VERSION}
+fi
 if [ ! -d $SHELLPACK_SOURCES/iozone-${VERSION}-installed ]; then
-	$SHELLPACK_INCLUDE/shellpack-install-iozone -v ${VERSION} || die iozone install script returned error
+	$SHELLPACK_INCLUDE/shellpack-install-iozone -v ${VERSION}  || die iozone install script returned error
 fi
 cd $SHELLPACK_SOURCES/iozone-${VERSION}-installed || die Failed to cd to iozone install directory
-
-# Build test parameters
-TESTS_PARAM=
-TESTS=`echo $TESTS | tr ',' ' '`
-for TEST in $TESTS; do
-	TESTS_PARAM="$TESTS_PARAM -i $TEST"
-done
+if [ "$INSTALL_ONLY" = "yes" ]; then
+	echo iozone installed only as requested.
+	exit $SHELLPACK_SUCCESS
+fi
 
 # Include monitor hooks
 . $SHELLPACK_INCLUDE/include-monitor.sh
 
-# Dump caches
-sync
-sleep 2
-echo 3 > /proc/sys/vm/drop_caches
+if [ -z "$IOZONE_MAX_SIZE" ]; then
+	IOZONE_MAX_SIZE=$((MEMTOTAL_BYTES*2))
+fi
 
-monitor_pre_hook $LOGDIR_RESULTS $RECORD_LEN
-case $TEST_TYPE in
-full-automatic)
-	$SHELLPACK_SOURCES/iozone-${VERSION}-installed/bin/iozone \
-		-a -g $MAXIMUM_FILESIZE \
-		$WORKFILE_PREFIX \
-		$TESTS_PARAM \
-		-r $RECORD_LEN $EXTRA_OPTS \
-		2>&1 | tee $LOGDIR_RESULTS/iozone-$RECORD_LEN.result
-	;;
-thread-scalability)
-	CPU=1
-	while [ $CPU -le $((NUMCPUS*16)) ]; do
-		$SHELLPACK_SOURCES/iozone-${VERSION}-installed/bin/iozone \
-			$WORKFILE_PREFIX \
-			-s $((MAXIMUM_FILESIZE/CPU)) -t $CPU \
-			-r $RECORD_LEN $TESTS_PARAM $EXTRA_OPTS \
-			2>&1 | tee $LOGDIR_RESULTS/iozone-tput-$CPU-$MAXIMUM_FILESIZE.result
-		CPU=$((CPU*2))
-	done
-	FILESIZE=$((FILESIZE*2))
-	;;
-single)
-	$SHELLPACK_SOURCES/iozone-${VERSION}-installed/bin/iozone \
-		-s $((MAXIMUM_FILESIZE/THREADS)) -t $THREADS \
-		$WORKFILE_PREFIX \
-		-r $RECORD_LEN $EXTRA_OPTS 2>&1 | tee $LOGDIR_RESULTS/iozone.result
-esac
-monitor_post_hook $LOGDIR_RESULTS $RECORD_LEN
+if [ -z "$IOZONE_MIN_SIZE" ]; then
+	IOZONE_MIN_SIZE=$((IOZONE_MAX_SIZE/16))
+fi
 
-echo
-echo IOZone completed successfully
+if [ -z "$IOZONE_MIN_BLK_SIZE" ]; then
+	if [ -z "$IOZONE_MAX_BLK_SIZE" ]; then
+		IOZONE_MAX_BLK_SIZE=4096
+	fi
+	IOZONE_MIN_BLK_SIZE="$IOZONE_MAX_BLK_SIZE"
+elif [ -z "$IOZONE_MAX_BLK_SIZE" ]; then
+	IOZONE_MAX_BLK_SIZE="$IOZONE_MIN_BLK_SIZE"
+fi
+
+monitor_pre_hook $LOGDIR_RESULTS
+for (( ITERATION = 1; ITERATION <= IOZONE_ITERATIONS; ITERATION++ )); do
+	src/current/iozone -a -n $((IOZONE_MIN_SIZE/1024)) \
+		-g $((IOZONE_MAX_SIZE/1024)) -y $IOZONE_MIN_BLK_SIZE \
+		-q $IOZONE_MAX_BLK_SIZE -i 0 -i 1 -i 2 -i 3 \
+		-f $TESTDISK_DIR/iozone_file 2>&1 | \
+		tee $LOGDIR_RESULTS/iozone-$ITERATION.log ||
+		die "Failed to run iozone"
+done
+monitor_post_hook $LOGDIR_RESULTS
+
 exit $SHELLPACK_SUCCESS
-#### Description IOZone benchmark
-#### Details iozone-bench 10
+#### Description iozone
+#### Details iozone-bench 7
diff --git a/shellpacks/shellpack-install-iozone b/shellpacks/shellpack-install-iozone
--- a/shellpacks/shellpack-install-iozone
+++ b/shellpacks/shellpack-install-iozone
@@ -1,81 +1,62 @@
 #!/bin/bash
-# IOZone installer
+# iozone installer
 P=iozone-install
-WEB_LOCATION=http://www.iozone.org/src/current/
-DEFAULT_VERSION=3_327
+DEFAULT_VERSION=3_428
 . $SHELLPACK_INCLUDE/common.sh
+WEB_LOCATION=http://www.iozone.org/src/current/
+MIRROR_LOCATION="$WEBROOT/iozone/"
 
 # Basic argument parser
-while [ "$1" != "" ]; do
-  case "$1" in
-    -v)
-            VERSION=$2
-	    shift 2
-	    ;;
-    *)
-            echo Unrecognised option: $1
-	    shift
-  esac
-done
+TASKSET_SERVER=
+TASKSET_CLIENT=
 
+while [ "$1" != "" ]; do
+	case "$1" in
+	-v)
+		VERSION=$2
+		shift 2
+		;;
+	*)
+		echo Unrecognised option: $1
+		shift
+	esac
+done
+if [ "$TASKSET_SERVER" != "" ]; then
+	echo TASKSET_SERVER: $TASKSET_SERVER
+	echo TASKSET_CLIENT: $TASKSET_CLIENT
+fi
 if [ -z "$VERSION" ]; then
 	VERSION=$DEFAULT_VERSION
 fi
 
 # Unconditionally fetch the tar to find out the real version number
-echo "$P: Fetching iozone from $WEB_LOCATION"
-pushd $SHELLPACK_SOURCES > /dev/null
 TARFILE=iozone${VERSION}.tar
-wget -q $WEB_LOCATION/$TARFILE -O $TARFILE
+sources_fetch $WEB_LOCATION/$TARFILE $MIRROR_LOCATION/$TARFILE $SHELLPACK_SOURCES/$TARFILE
+cd $SHELLPACK_SOURCES
+tar -xf $TARFILE
 if [ $? -ne 0 ]; then
-	die "$P: Could not download the source from $WEB_LOCATION"
-	exit $SHELLPACK_ERROR
-fi
-
-# Building from scratch, uncompress the tar
-tar xf $TARFILE
-if [ $? -ne 0 ]; then
-	die "$P: tar xf iozone${VERSION}.tar failed"
+        error "$P: tar xf iozone${VERSION}.tar failed"
+        popd > /dev/null
+        exit $SHELLPACK_ERROR
 fi
 
 # Rename directory to something we expect.
 DST_DIR=`tar tf $TARFILE | head -n 1 | awk -F / '{print $1}'`
-if [ "$DST_DIR" != "iozone-${VERSION}" ]; then
-	echo Moving $DST_DIR to iozone-${VERSION}
-	mv $DST_DIR iozone-${VERSION}
-fi
-
-# Build the library
-pushd iozone-${VERSION} > /dev/null
-
-# Configure
-INSTALLPATH=$SHELLPACK_SOURCES/iozone-${VERSION}-installed
-rm -rf $INSTALLPATH
+mv $DST_DIR iozone-${VERSION}-installed
+pushd iozone-${VERSION}-installed > /dev/null || die Failed to rename tar
 
 # Build
+pushd $SHELLPACK_SOURCES/iozone-${VERSION}-installed || die Failed to change to source directory
+
 cd src/current
-case `uname -m` in
-	i?86)
-		make linux
-		;;
-	x86_64)
-		make linux-AMD64
-		;;
-	ppc64)
-		make linux-powerpc64
-		;;
-esac
+
+make -j$NUMCPUS linux
 if [ $? -ne 0 ]; then
-	die "$P: make failed"
+	error "$P: make failed"
+	popd > /dev/null
+	exit $SHELLPACK_ERROR
 fi
 
-# Install
-mkdir -p $INSTALLPATH/bin
-cp iozone $INSTALLPATH/bin
-if [ $? -ne 0 ]; then
-	die "$P: installation failed"
-fi
-
-echo IOZone installed successfully
-#### Description IOZone benchmark
-#### Details iozone 10
+echo iozone installed successfully
+#### Description iozone
+#### Details iozone 7
