nas-mpi: Fix memory size handling
Signed-off-by: Mel Gorman <mgorman@suse.de>

diff --git a/shellpacks/shellpack-install-nas b/shellpacks/shellpack-install-nas
--- a/shellpacks/shellpack-install-nas
+++ b/shellpacks/shellpack-install-nas
@@ -39,9 +39,9 @@ sources_fetch $WEB_LOCATION/$TARFILE $MIRROR_LOCATION/$TARFILE $SHELLPACK_SOURCE
 cd $SHELLPACK_SOURCES
 tar -xf $TARFILE
 if [ $? -ne 0 ]; then
-        error "$P: tar xf NPB${VERSION}.tar.gz failed"
-        popd > /dev/null
-        exit $SHELLPACK_ERROR
+	error "$P: tar xf NPB${VERSION}.tar.gz failed"
+	popd > /dev/null
+	exit $SHELLPACK_ERROR
 fi
 
 # Rename directory to something we expect.
@@ -51,4 +51,4 @@ pushd nas-$VERSION-installed > /dev/null || die Failed to rename tar
 
 exit $SHELLPACK_SUCCESS
 #### Description NAS Parallel Benchmark
-#### Details nas 50
+#### Details nas 51
