Touch all files before using configure to avoid problems with timestamps
Signed-off-by: Mel Gorman <mgorman@techsingularity.net>

diff --git a/shellpacks/shellpack-install-aim9 b/shellpacks/shellpack-install-aim9
--- a/shellpacks/shellpack-install-aim9
+++ b/shellpacks/shellpack-install-aim9
@@ -3,17 +3,32 @@
 P=aim9-install
 DEFAULT_VERSION=9110
 . $SHELLPACK_INCLUDE/common.sh
+TIME_CMD=`which time`
+if [ "$TIME_CMD" = "" ]; then
+        TIMEFORMAT="%2Uuser %2Ssystem %Relapsed %P%%CPU"
+        TIME_CMD="time"
+fi
 WEB_LOCATION="http://heanet.dl.sourceforge.net/sourceforge/aimbench"
 MIRROR_LOCATION="$WEBROOT/aim9"
 
 # Basic argument parser
 TASKSET_SERVER=
 TASKSET_CLIENT=
+SERVERSIDE_COMMAND=none
+SERVERSIDE_NAME=`date +%Y%m%d-%H%M-%S`
 
 while [ "$1" != "" ]; do
 	case "$1" in
 	-v)
 		VERSION=$2
+		shift 2
+		;;
+	--serverside-command)
+		SERVERSIDE_COMMAND=$2
+		shift 2
+		;;
+	--serverside-name)
+		SERVERSIDE_NAME=$2
 		shift 2
 		;;
 	--install-only)
@@ -43,9 +58,9 @@ sources_fetch $WEB_LOCATION/$TARFILE $MIRROR_LOCATION/$TARFILE $SHELLPACK_SOURCE
 cd $SHELLPACK_SOURCES
 tar -xf $TARFILE
 if [ $? -ne 0 ]; then
-        error "$P: tar xf s${VERSION}.tar.Z failed"
-        popd > /dev/null
-        exit $SHELLPACK_ERROR
+	error "$P: tar xf s${VERSION}.tar.Z failed"
+	popd > /dev/null
+	exit $SHELLPACK_ERROR
 fi
 
 # Rename directory to something we expect.
@@ -54,6 +69,9 @@ mv $DST_DIR aim9-$VERSION-installed
 pushd aim9-$VERSION-installed > /dev/null || die Failed to rename tar
 
 pushd $SHELLPACK_SOURCES/aim9-$VERSION-installed || die Failed to change to source directory
+for FILE in `find -name "*"`; do
+	touch $FILE
+done
 echo  > aim9.configure
 echo >> aim9.configure
 echo >> aim9.configure
@@ -79,4 +97,4 @@ fork_test" >> s9workfile-short
 
 exit $SHELLPACK_SUCCESS
 #### Description AIM9 benchmark
-#### Details aim9 22
+#### Details aim9 23
diff --git a/shellpacks/shellpack-install-autonumabench b/shellpacks/shellpack-install-autonumabench
--- a/shellpacks/shellpack-install-autonumabench
+++ b/shellpacks/shellpack-install-autonumabench
@@ -4,17 +4,32 @@
 P=autonumabench-install
 DEFAULT_VERSION=0
 . $SHELLPACK_INCLUDE/common.sh
+TIME_CMD=`which time`
+if [ "$TIME_CMD" = "" ]; then
+        TIMEFORMAT="%2Uuser %2Ssystem %Relapsed %P%%CPU"
+        TIME_CMD="time"
+fi
 GIT_LOCATION=git://gitorious.org/autonuma-benchmark/autonuma-benchmark.git
 MIRROR_LOCATION="$WEBROOT/autonumabench/"
 
 # Basic argument parser
 TASKSET_SERVER=
 TASKSET_CLIENT=
+SERVERSIDE_COMMAND=none
+SERVERSIDE_NAME=`date +%Y%m%d-%H%M-%S`
 
 while [ "$1" != "" ]; do
 	case "$1" in
 	-v)
 		VERSION=$2
+		shift 2
+		;;
+	--serverside-command)
+		SERVERSIDE_COMMAND=$2
+		shift 2
+		;;
+	--serverside-name)
+		SERVERSIDE_NAME=$2
 		shift 2
 		;;
 	*)
@@ -36,9 +51,9 @@ git_fetch $GIT_LOCATION autonumabench-${VERSION}-installed $MIRROR_LOCATION/$TAR
 cd $SHELLPACK_SOURCES
 tar -xf $TARFILE
 if [ $? -ne 0 ]; then
-        error "$P: tar xf autonumabench-${VERSION}.tar.gz failed"
-        popd > /dev/null
-        exit $SHELLPACK_ERROR
+	error "$P: tar xf autonumabench-${VERSION}.tar.gz failed"
+	popd > /dev/null
+	exit $SHELLPACK_ERROR
 fi
 
 # Rename directory to something we expect.
@@ -48,6 +63,9 @@ pushd autonumabench-${VERSION}-installed > /dev/null || die Failed to rename tar
 
 # Build
 pushd $SHELLPACK_SOURCES/autonumabench-${VERSION}-installed || die Failed to change to source directory
+for FILE in `find -name "*"`; do
+	touch $FILE
+done
 echo 'diff --git a/start_bench.sh b/start_bench.sh
 index 101286e..5780b09 100755
 --- a/start_bench.sh
@@ -139,4 +157,4 @@ index 101286e..5780b09 100755
 
 echo autonumabench installed successfully
 #### Description AutoNUMA Benchmark
-#### Details autonumabench 12
+#### Details autonumabench 13
diff --git a/shellpacks/shellpack-install-cmattach-test b/shellpacks/shellpack-install-cmattach-test
--- a/shellpacks/shellpack-install-cmattach-test
+++ b/shellpacks/shellpack-install-cmattach-test
@@ -2,17 +2,32 @@
 P=cmattach-test-install
 DEFAULT_VERSION=20110718
 . $SHELLPACK_INCLUDE/common.sh
+TIME_CMD=`which time`
+if [ "$TIME_CMD" = "" ]; then
+        TIMEFORMAT="%2Uuser %2Ssystem %Relapsed %P%%CPU"
+        TIME_CMD="time"
+fi
 WEB_LOCATION=http://ozlabs.org/~cyeoh/cma
 MIRROR_LOCATION="$WEBROOT/cmattach/"
 
 # Basic argument parser
 TASKSET_SERVER=
 TASKSET_CLIENT=
+SERVERSIDE_COMMAND=none
+SERVERSIDE_NAME=`date +%Y%m%d-%H%M-%S`
 
 while [ "$1" != "" ]; do
 	case "$1" in
 	-v)
 		VERSION=$2
+		shift 2
+		;;
+	--serverside-command)
+		SERVERSIDE_COMMAND=$2
+		shift 2
+		;;
+	--serverside-name)
+		SERVERSIDE_NAME=$2
 		shift 2
 		;;
 	--install-only)
@@ -42,9 +57,9 @@ sources_fetch $WEB_LOCATION/$TARFILE $MIRROR_LOCATION/$TARFILE $SHELLPACK_SOURCE
 cd $SHELLPACK_SOURCES
 tar -xf $TARFILE
 if [ $? -ne 0 ]; then
-        error "$P: tar xf cma-test-${VERSION}.tgz failed"
-        popd > /dev/null
-        exit $SHELLPACK_ERROR
+	error "$P: tar xf cma-test-${VERSION}.tgz failed"
+	popd > /dev/null
+	exit $SHELLPACK_ERROR
 fi
 
 # Rename directory to something we expect.
@@ -54,6 +69,9 @@ pushd cmattach-test-${VERSION}-installed > /dev/null || die Failed to rename tar
 
 # Build
 pushd $SHELLPACK_SOURCES/cmattach-test-${VERSION}-installed || die Failed to change to source directory
+for FILE in `find -name "*"`; do
+	touch $FILE
+done
 echo "diff --git a/process_vm.h b/process_vm.h
 index bc69e45..d80a245 100755
 --- a/process_vm.h
@@ -118,4 +136,4 @@ if [ $? -ne 0 ]; then
 	exit $SHELLPACK_ERROR
 fi
 #### Description This is a basic functional test of cross-memory-attach
-#### Details cmattach-test 3
+#### Details cmattach-test 4
diff --git a/shellpacks/shellpack-install-iozone b/shellpacks/shellpack-install-iozone
--- a/shellpacks/shellpack-install-iozone
+++ b/shellpacks/shellpack-install-iozone
@@ -3,17 +3,32 @@
 P=iozone-install
 DEFAULT_VERSION=3_428
 . $SHELLPACK_INCLUDE/common.sh
+TIME_CMD=`which time`
+if [ "$TIME_CMD" = "" ]; then
+        TIMEFORMAT="%2Uuser %2Ssystem %Relapsed %P%%CPU"
+        TIME_CMD="time"
+fi
 WEB_LOCATION=http://www.iozone.org/src/current/
 MIRROR_LOCATION="$WEBROOT/iozone/"
 
 # Basic argument parser
 TASKSET_SERVER=
 TASKSET_CLIENT=
+SERVERSIDE_COMMAND=none
+SERVERSIDE_NAME=`date +%Y%m%d-%H%M-%S`
 
 while [ "$1" != "" ]; do
 	case "$1" in
 	-v)
 		VERSION=$2
+		shift 2
+		;;
+	--serverside-command)
+		SERVERSIDE_COMMAND=$2
+		shift 2
+		;;
+	--serverside-name)
+		SERVERSIDE_NAME=$2
 		shift 2
 		;;
 	*)
@@ -35,9 +50,9 @@ sources_fetch $WEB_LOCATION/$TARFILE $MIRROR_LOCATION/$TARFILE $SHELLPACK_SOURCE
 cd $SHELLPACK_SOURCES
 tar -xf $TARFILE
 if [ $? -ne 0 ]; then
-        error "$P: tar xf iozone${VERSION}.tar failed"
-        popd > /dev/null
-        exit $SHELLPACK_ERROR
+	error "$P: tar xf iozone${VERSION}.tar failed"
+	popd > /dev/null
+	exit $SHELLPACK_ERROR
 fi
 
 # Rename directory to something we expect.
@@ -47,6 +62,9 @@ pushd iozone-${VERSION}-installed > /dev/null || die Failed to rename tar
 
 # Build
 pushd $SHELLPACK_SOURCES/iozone-${VERSION}-installed || die Failed to change to source directory
+for FILE in `find -name "*"`; do
+	touch $FILE
+done
 
 cd src/current
 
@@ -59,4 +77,4 @@ fi
 
 echo iozone installed successfully
 #### Description iozone
-#### Details iozone 14
+#### Details iozone 15
diff --git a/shellpacks/shellpack-install-ipcscale b/shellpacks/shellpack-install-ipcscale
--- a/shellpacks/shellpack-install-ipcscale
+++ b/shellpacks/shellpack-install-ipcscale
@@ -2,17 +2,32 @@
 P=ipcscale-install
 DEFAULT_VERSION=0
 . $SHELLPACK_INCLUDE/common.sh
+TIME_CMD=`which time`
+if [ "$TIME_CMD" = "" ]; then
+        TIMEFORMAT="%2Uuser %2Ssystem %Relapsed %P%%CPU"
+        TIME_CMD="time"
+fi
 GIT_LOCATION=https://github.com/manfred-colorfu/ipcscale.git
 MIRROR_LOCATION="$WEBROOT/ipcscale/"
 
 # Basic argument parser
 TASKSET_SERVER=
 TASKSET_CLIENT=
+SERVERSIDE_COMMAND=none
+SERVERSIDE_NAME=`date +%Y%m%d-%H%M-%S`
 
 while [ "$1" != "" ]; do
 	case "$1" in
 	-v)
 		VERSION=$2
+		shift 2
+		;;
+	--serverside-command)
+		SERVERSIDE_COMMAND=$2
+		shift 2
+		;;
+	--serverside-name)
+		SERVERSIDE_NAME=$2
 		shift 2
 		;;
 	*)
@@ -34,9 +49,9 @@ git_fetch $GIT_LOCATION ipcscale-${VERSION}-installed $MIRROR_LOCATION/$TARFILE 
 cd $SHELLPACK_SOURCES
 tar -xf $TARFILE
 if [ $? -ne 0 ]; then
-        error "$P: tar xf ipcscale-${VERSION}.tar.gz failed"
-        popd > /dev/null
-        exit $SHELLPACK_ERROR
+	error "$P: tar xf ipcscale-${VERSION}.tar.gz failed"
+	popd > /dev/null
+	exit $SHELLPACK_ERROR
 fi
 
 # Rename directory to something we expect.
@@ -45,6 +60,9 @@ mv $DST_DIR ipcscale-${VERSION}-installed
 pushd ipcscale-${VERSION}-installed > /dev/null || die Failed to rename tar
 
 pushd $SHELLPACK_SOURCES/ipcscale-${VERSION}-installed || die Failed to change to source directory
+for FILE in `find -name "*"`; do
+	touch $FILE
+done
 make -j$NUMCPUS 
 if [ $? -ne 0 ]; then
 	error "$P: make failed"
@@ -54,4 +72,4 @@ fi
 
 echo ipcscale installed successfully
 #### Description ipcscale
-#### Details ipcscale 4
+#### Details ipcscale 5
diff --git a/shellpacks/shellpack-install-memtester b/shellpacks/shellpack-install-memtester
--- a/shellpacks/shellpack-install-memtester
+++ b/shellpacks/shellpack-install-memtester
@@ -3,6 +3,11 @@
 P=memtester-install
 DEFAULT_VERSION=4.3.0
 . $SHELLPACK_INCLUDE/common.sh
+TIME_CMD=`which time`
+if [ "$TIME_CMD" = "" ]; then
+        TIMEFORMAT="%2Uuser %2Ssystem %Relapsed %P%%CPU"
+        TIME_CMD="time"
+fi
 WEB_LOCATION=http://pyropus.ca/software/memtester/old-versions
 #memtester-4.3.0.tar.gz
 MIRROR_LOCATION="$WEBROOT/memtester/"
@@ -10,11 +15,21 @@ MIRROR_LOCATION="$WEBROOT/memtester/"
 # Basic argument parser
 TASKSET_SERVER=
 TASKSET_CLIENT=
+SERVERSIDE_COMMAND=none
+SERVERSIDE_NAME=`date +%Y%m%d-%H%M-%S`
 
 while [ "$1" != "" ]; do
 	case "$1" in
 	-v)
 		VERSION=$2
+		shift 2
+		;;
+	--serverside-command)
+		SERVERSIDE_COMMAND=$2
+		shift 2
+		;;
+	--serverside-name)
+		SERVERSIDE_NAME=$2
 		shift 2
 		;;
 	*)
@@ -36,9 +51,9 @@ sources_fetch $WEB_LOCATION/$TARFILE $MIRROR_LOCATION/$TARFILE $SHELLPACK_SOURCE
 cd $SHELLPACK_SOURCES
 tar -xf $TARFILE
 if [ $? -ne 0 ]; then
-        error "$P: tar xf memtester-${VERSION}.tar.gz failed"
-        popd > /dev/null
-        exit $SHELLPACK_ERROR
+	error "$P: tar xf memtester-${VERSION}.tar.gz failed"
+	popd > /dev/null
+	exit $SHELLPACK_ERROR
 fi
 
 # Rename directory to something we expect.
@@ -48,6 +63,9 @@ pushd memtester-${VERSION}-installed > /dev/null || die Failed to rename tar
 
 # Build
 pushd $SHELLPACK_SOURCES/memtester-${VERSION}-installed || die Failed to change to source directory
+for FILE in `find -name "*"`; do
+	touch $FILE
+done
 make -j$NUMCPUS 
 if [ $? -ne 0 ]; then
 	error "$P: make failed"
@@ -57,4 +75,4 @@ fi
 
 echo memtester installed successfully
 #### Description Userspace memory integrity tester
-#### Details memtester 5
+#### Details memtester 6
diff --git a/shellpacks/shellpack-install-sembench b/shellpacks/shellpack-install-sembench
--- a/shellpacks/shellpack-install-sembench
+++ b/shellpacks/shellpack-install-sembench
@@ -2,17 +2,32 @@
 P=sembench-install
 DEFAULT_VERSION=3
 . $SHELLPACK_INCLUDE/common.sh
+TIME_CMD=`which time`
+if [ "$TIME_CMD" = "" ]; then
+        TIMEFORMAT="%2Uuser %2Ssystem %Relapsed %P%%CPU"
+        TIME_CMD="time"
+fi
 GIT_LOCATION=https://github.com/davidlohr/sembench-ng.git
 MIRROR_LOCATION="$WEBROOT/sembench/"
 
 # Basic argument parser
 TASKSET_SERVER=
 TASKSET_CLIENT=
+SERVERSIDE_COMMAND=none
+SERVERSIDE_NAME=`date +%Y%m%d-%H%M-%S`
 
 while [ "$1" != "" ]; do
 	case "$1" in
 	-v)
 		VERSION=$2
+		shift 2
+		;;
+	--serverside-command)
+		SERVERSIDE_COMMAND=$2
+		shift 2
+		;;
+	--serverside-name)
+		SERVERSIDE_NAME=$2
 		shift 2
 		;;
 	*)
@@ -34,9 +49,9 @@ git_fetch $GIT_LOCATION sembench-${VERSION}-installed $MIRROR_LOCATION/$TARFILE 
 cd $SHELLPACK_SOURCES
 tar -xf $TARFILE
 if [ $? -ne 0 ]; then
-        error "$P: tar xf sembench-${VERSION}.tar.gz failed"
-        popd > /dev/null
-        exit $SHELLPACK_ERROR
+	error "$P: tar xf sembench-${VERSION}.tar.gz failed"
+	popd > /dev/null
+	exit $SHELLPACK_ERROR
 fi
 
 # Rename directory to something we expect.
@@ -45,6 +60,9 @@ mv $DST_DIR sembench-${VERSION}-installed
 pushd sembench-${VERSION}-installed > /dev/null || die Failed to rename tar
 
 pushd $SHELLPACK_SOURCES/sembench-${VERSION}-installed || die Failed to change to source directory
+for FILE in `find -name "*"`; do
+	touch $FILE
+done
 make -j$NUMCPUS 
 if [ $? -ne 0 ]; then
 	error "$P: make failed"
@@ -54,4 +72,4 @@ fi
 
 echo sembench installed successfully
 #### Description sembench
-#### Details sembench 10
+#### Details sembench 11
