Convert a number of shellpacks to a template
All shellpacks were generated based on a different directory layout and
a script that managed basic versioning. This expands on that concept to
generate some of the shellpack from macros and exposes the necessary
scripts to do that.

Signed-off-by: Mel Gorman <mgorman@suse.de>

diff --git a/shellpacks/shellpack-install-dbench b/shellpacks/shellpack-install-dbench
--- a/shellpacks/shellpack-install-dbench
+++ b/shellpacks/shellpack-install-dbench
@@ -1,25 +1,24 @@
 #!/bin/bash
 # dbench installer
 P=dbench-install
+DEFAULT_VERSION=3.04
+. $SHELLPACK_INCLUDE/common.sh
 GIT_LOCATION=git://git.samba.org/sahlberg/dbench.git
 WEB_LOCATION=http://samba.org/ftp/tridge/dbench/
 MIRROR_LOCATION="$WEBROOT/dbench/"
-DEFAULT_VERSION=3.04
-. $SHELLPACK_INCLUDE/common.sh
 
 # Basic argument parser
 while [ "$1" != "" ]; do
-  case "$1" in
-    -v)
-            VERSION=$2
-	    shift 2
-	    ;;
-    *)
-            echo Unrecognised option: $1
-	    shift
-  esac
+	case "$1" in
+	-v)
+		VERSION=$2
+		shift 2
+		;;
+	*)
+		echo Unrecognised option: $1
+		shift
+	esac
 done
-
 if [ -z "$VERSION" ]; then
 	VERSION=$DEFAULT_VERSION
 fi
@@ -27,14 +26,12 @@ fi
 # Unconditionally fetch the tar to find out the real version number
 TARFILE=dbench-${VERSION}.tar.gz
 sources_fetch $WEB_LOCATION/$TARFILE $MIRROR_LOCATION/$TARFILE $SHELLPACK_SOURCES/$TARFILE
-#git_fetch $GIT_LOCATION dbench-$VERSION $MIRROR_LOCATION/$TARFILE $SHELLPACK_SOURCES/$TARFILE
-
 cd $SHELLPACK_SOURCES
 tar -xf $TARFILE
 if [ $? -ne 0 ]; then
-	error "$P: tar xf dbench-${VERSION}.tar.gz failed"
-	popd > /dev/null
-	exit $SHELLPACK_ERROR
+        error "$P: tar xf dbench-${VERSION}.tar.gz failed"
+        popd > /dev/null
+        exit $SHELLPACK_ERROR
 fi
 
 # Rename directory to something we expect.
@@ -43,14 +40,17 @@ mv $DST_DIR dbench-${VERSION}
 pushd dbench-${VERSION} > /dev/null || die Failed to rename tar
 
 # Build
+cd $SHELLPACK_SOURCES/dbench-${VERSION} || die Failed to change to source directory
 ./autogen.sh || die Failed to run autogen
 ./configure --prefix=$SHELLPACK_SOURCES/dbench-${VERSION}-installed || die Failed to configure
 make || die Failed to build
 make install || die Failed to install
+
+# Fixups
 if [ ! -e $SHELLPACK_SOURCES/dbench-${VERSION}-installed/share ]; then
 	cp $SHELLPACK_SOURCES/dbench-${VERSION}-installed/share/doc/dbench/loadfiles/client.txt $SHELLPACK_SOURCES/dbench-${VERSION}-installed/share
 fi
 
 echo dbench installed successfully
 #### Description dbench
-#### Details dbench 9
+#### Details dbench 13
diff --git a/shellpacks/shellpack-install-ffsb b/shellpacks/shellpack-install-ffsb
--- a/shellpacks/shellpack-install-ffsb
+++ b/shellpacks/shellpack-install-ffsb
@@ -1,41 +1,37 @@
 #!/bin/bash
 # ffsb installer
 P=ffsb-install
-WEB_LOCATION=http://heanet.dl.sourceforge.net/project/ffsb/ffsb/
-#ffsb-6.0-rc2/ffsb-6.0-rc2.tar.bz2
-MIRROR_LOCATION="$WEBROOT/ffsb/"
 DEFAULT_VERSION=6.0-rc2
 . $SHELLPACK_INCLUDE/common.sh
+WEB_LOCATION=http://heanet.dl.sourceforge.net/project/ffsb/ffsb/
+MIRROR_LOCATION="$WEBROOT/ffsb/"
 
 # Basic argument parser
 while [ "$1" != "" ]; do
-  case "$1" in
-    -v)
-            VERSION=$2
-	    shift 2
-	    ;;
-    *)
-            echo Unrecognised option: $1
-	    shift
-  esac
+	case "$1" in
+	-v)
+		VERSION=$2
+		shift 2
+		;;
+	*)
+		echo Unrecognised option: $1
+		shift
+	esac
 done
-
 if [ -z "$VERSION" ]; then
 	VERSION=$DEFAULT_VERSION
 fi
 
-# Unconditionally fetch the tar to find out the real version number
 WEB_LOCATION=$WEB_LOCATION/ffsb-$VERSION
+# Unconditionally fetch the tar to find out the real version number
 TARFILE=ffsb-${VERSION}.tar.bz2
-sources_fetch $WEB_LOCATION/$VERSION/$TARFILE $MIRROR_LOCATION/$TARFILE $SHELLPACK_SOURCES/$TARFILE
-
-# Building from scratch, uncompress the tar
+sources_fetch $WEB_LOCATION/$TARFILE $MIRROR_LOCATION/$TARFILE $SHELLPACK_SOURCES/$TARFILE
 cd $SHELLPACK_SOURCES
-tar xf $TARFILE
+tar -xf $TARFILE
 if [ $? -ne 0 ]; then
-  error "$P: tar xf $TARFILE failed"
-  popd > /dev/null
-  exit $SHELLPACK_ERROR
+        error "$P: tar xf ffsb-${VERSION}.tar.bz2 failed"
+        popd > /dev/null
+        exit $SHELLPACK_ERROR
 fi
 
 # Rename directory to something we expect.
@@ -43,31 +39,26 @@ DST_DIR=`tar tf $TARFILE | head -n 1 | awk -F / '{print $1}'`
 mv $DST_DIR ffsb-${VERSION}
 pushd ffsb-${VERSION} > /dev/null || die Failed to rename tar
 
-# Configure
+pushd $SHELLPACK_SOURCES/ffsb-${VERSION} || die Failed to change to source directory
 ./configure --prefix=$SHELLPACK_SOURCES/ffsb-${VERSION}-installed
 if [ $? -ne 0 ]; then
 	error "$P: configure failed"
 	popd > /dev/null
 	exit $SHELLPACK_ERROR
 fi
-
-# Build
 make
 if [ $? -ne 0 ]; then
 	error "$P: make failed"
 	popd > /dev/null
 	exit $SHELLPACK_ERROR
 fi
-
-# Install
 make install
 if [ $? -ne 0 ]; then
-	error "$P: install failed"
+	error "$P: make install failed"
 	popd > /dev/null
 	exit $SHELLPACK_ERROR
 fi
 
-
 echo ffsb installed successfully
 #### Description Flexible FileSystem Benchmark
-#### Details ffsb 4
+#### Details ffsb 7
diff --git a/shellpacks/shellpack-install-fsmark b/shellpacks/shellpack-install-fsmark
--- a/shellpacks/shellpack-install-fsmark
+++ b/shellpacks/shellpack-install-fsmark
@@ -1,24 +1,23 @@
 #!/bin/bash
 # fs-mark installer
 P=fsmark-install
-WEB_LOCATION=http://heanet.dl.sourceforge.net/project/fsmark/fsmark/
-MIRROR_LOCATION="$WEBROOT/fsmark/"
 DEFAULT_VERSION=3.3
 . $SHELLPACK_INCLUDE/common.sh
+WEB_LOCATION=http://heanet.dl.sourceforge.net/project/fsmark/fsmark/
+MIRROR_LOCATION="$WEBROOT/fsmark/"
 
 # Basic argument parser
 while [ "$1" != "" ]; do
-  case "$1" in
-    -v)
-            VERSION=$2
-	    shift 2
-	    ;;
-    *)
-            echo Unrecognised option: $1
-	    shift
-  esac
+	case "$1" in
+	-v)
+		VERSION=$2
+		shift 2
+		;;
+	*)
+		echo Unrecognised option: $1
+		shift
+	esac
 done
-
 if [ -z "$VERSION" ]; then
 	VERSION=$DEFAULT_VERSION
 fi
@@ -26,14 +25,12 @@ fi
 # Unconditionally fetch the tar to find out the real version number
 TARFILE=fs_mark-${VERSION}.tar.gz
 sources_fetch $WEB_LOCATION/$VERSION/$TARFILE $MIRROR_LOCATION/$TARFILE $SHELLPACK_SOURCES/$TARFILE
-
-# Building from scratch, uncompress the tar
 cd $SHELLPACK_SOURCES
-tar xf $TARFILE
+tar -xf $TARFILE
 if [ $? -ne 0 ]; then
-  error "$P: tar xf fs_mark-${VERSION}.tar.gz failed"
-  popd > /dev/null
-  exit $SHELLPACK_ERROR
+        error "$P: tar xf fs_mark-${VERSION}.tar.gz failed"
+        popd > /dev/null
+        exit $SHELLPACK_ERROR
 fi
 
 # Rename directory to something we expect.
@@ -41,7 +38,7 @@ DST_DIR=`tar tf $TARFILE | head -n 1 | awk -F / '{print $1}'`
 mv $DST_DIR fsmark-${VERSION}-installed
 pushd fsmark-${VERSION}-installed > /dev/null || die Failed to rename tar
 
-# Build
+pushd $SHELLPACK_SOURCES/fsmark-${VERSION}-installed || die Failed to change to source directory
 make
 if [ $? -ne 0 ]; then
 	error "$P: make failed"
@@ -51,4 +48,4 @@ fi
 
 echo fsmark installed successfully
 #### Description fsmark
-#### Details fsmark 15
+#### Details fsmark 19
diff --git a/shellpacks/shellpack-install-lhcs b/shellpacks/shellpack-install-lhcs
--- a/shellpacks/shellpack-install-lhcs
+++ b/shellpacks/shellpack-install-lhcs
@@ -1,46 +1,43 @@
 #!/bin/bash
 # lhcs regression test installer
 P=lhcs-install
-WEB_LOCATION=https://github.com/autotest/autotest/raw/master/client/tests/cpu_hotplug/
-MIRROR_LOCATION="$WEBROOT/lhcs/"
 DEFAULT_VERSION=1.6
 . $SHELLPACK_INCLUDE/common.sh
+WEB_LOCATION=https://github.com/autotest/autotest/raw/master/client/tests/cpu_hotplug/
+MIRROR_LOCATION="$WEBROOT/lhcs/"
 
 # Basic argument parser
 while [ "$1" != "" ]; do
-  case "$1" in
-    -v)
-            VERSION=$2
-	    shift 2
-	    ;;
-    *)
-            echo Unrecognised option: $1
-	    shift
-  esac
+	case "$1" in
+	-v)
+		VERSION=$2
+		shift 2
+		;;
+	*)
+		echo Unrecognised option: $1
+		shift
+	esac
 done
-
 if [ -z "$VERSION" ]; then
 	VERSION=$DEFAULT_VERSION
 fi
 
 # Unconditionally fetch the tar to find out the real version number
-TARFILE=lhcs_regression-${VERSION}.tar.tgz
+TARFILE=lhcs_regression-${VERSION}.tar.gz
 sources_fetch $WEB_LOCATION/$TARFILE $MIRROR_LOCATION/$TARFILE $SHELLPACK_SOURCES/$TARFILE
-
-# Building from scratch, uncompress the tar
 cd $SHELLPACK_SOURCES
-tar xf $TARFILE
+tar -xf $TARFILE
 if [ $? -ne 0 ]; then
-  error "$P: tar xf $TARFILE failed"
-  popd > /dev/null
-  exit $SHELLPACK_ERROR
+        error "$P: tar xf lhcs_regression-${VERSION}.tar.gz failed"
+        popd > /dev/null
+        exit $SHELLPACK_ERROR
 fi
 
-if [ ! -e lhcs_regression-$VERSION ]; then
-	echo ERROR: Did not expand as expected
-	exit $SHELLPACK_ERROR
-fi
+# Rename directory to something we expect.
+DST_DIR=`tar tf $TARFILE | head -n 1 | awk -F / '{print $1}'`
+mv $DST_DIR lhcs-${VERSION}-installed
+pushd lhcs-${VERSION}-installed > /dev/null || die Failed to rename tar
 
 echo lhcs installed successfully
 #### Description Linux Hotplug CPU Support
-#### Details lhcs 5
+#### Details lhcs 7
diff --git a/shellpacks/shellpack-install-lmbench b/shellpacks/shellpack-install-lmbench
--- a/shellpacks/shellpack-install-lmbench
+++ b/shellpacks/shellpack-install-lmbench
@@ -1,50 +1,46 @@
 #!/bin/bash
-# lmbench installer
 P=lmbench-install
-WEB_LOCATION=http://www.bitmover.com/lmbench
-MIRROR_LOCATION="$WEBROOT/lmbench"
 DEFAULT_VERSION=3
 . $SHELLPACK_INCLUDE/common.sh
+WEB_LOCATION=http://www.bitmover.com/lmbench
+MIRROR_LOCATION="$WEBROOT/lmbench"
 
 # Basic argument parser
 while [ "$1" != "" ]; do
-  case "$1" in
-    -v)
-            VERSION=$2
-	    shift 2
-	    ;;
-    *)
-            echo Unrecognised option: $1
-	    shift
-  esac
+	case "$1" in
+	-v)
+		VERSION=$2
+		shift 2
+		;;
+	*)
+		echo Unrecognised option: $1
+		shift
+	esac
 done
-
 if [ -z "$VERSION" ]; then
 	VERSION=$DEFAULT_VERSION
 fi
 
+# Unconditionally fetch the tar to find out the real version number
 TARFILE=lmbench${VERSION}.tar.gz
 sources_fetch $WEB_LOCATION/$TARFILE $MIRROR_LOCATION/$TARFILE $SHELLPACK_SOURCES/$TARFILE
-
-# Building from scratch, uncompress the tar
 cd $SHELLPACK_SOURCES
-tar xf $TARFILE
+tar -xf $TARFILE
 if [ $? -ne 0 ]; then
-  error "$P: tar xf $TARFILE failed"
-  popd > /dev/null
-  exit $SHELLPACK_ERROR
+        error "$P: tar xf lmbench${VERSION}.tar.gz failed"
+        popd > /dev/null
+        exit $SHELLPACK_ERROR
 fi
 
 # Rename directory to something we expect.
 DST_DIR=`tar tf $TARFILE | head -n 1 | awk -F / '{print $1}'`
-mv $DST_DIR lmbench${VERSION}-installed
-pushd lmbench${VERSION}-installed > /dev/null || die Failed to rename tar
+mv $DST_DIR lmbench-${VERSION}-installed
+pushd lmbench-${VERSION}-installed > /dev/null || die Failed to rename tar
 
+pushd $SHELLPACK_SOURCES/lmbench-${VERSION}-installed || die Failed to change to source directory
 # Workaround build problem
 mkdir SCCS
 touch SCCS/s.ChangeSet
-
-# Build
 cd src
 make
 if [ $? -ne 0 ]; then
@@ -58,4 +54,4 @@ cp ../bin/*/* ../bin/
 
 echo lmbench installed successfully
 #### Description lmbench
-#### Details lmbench 10
+#### Details lmbench 11
diff --git a/shellpacks/shellpack-install-memcachetest b/shellpacks/shellpack-install-memcachetest
--- a/shellpacks/shellpack-install-memcachetest
+++ b/shellpacks/shellpack-install-memcachetest
@@ -1,52 +1,65 @@
 #!/bin/bash
 # memcachetest installer
 P=memcachetest-install
-GIT_LOCATION=https://github.com/ingenthr/memcachetest.git
-MIRROR_LOCATION="$WEBROOT/memcachetest"
 DEFAULT_VERSION=0.01
 . $SHELLPACK_INCLUDE/common.sh
+GIT_LOCATION=https://github.com/ingenthr/memcachetest.git
+MIRROR_LOCATION="$WEBROOT/memcachetest"
 
 # Basic argument parser
 while [ "$1" != "" ]; do
-  case "$1" in
-    -v)
-            VERSION=$2
-	    shift 2
-	    ;;
-    *)
-            echo Unrecognised option: $1
-	    shift
-  esac
+	case "$1" in
+	-v)
+		VERSION=$2
+		shift 2
+		;;
+	*)
+		echo Unrecognised option: $1
+		shift
+	esac
 done
-
 if [ -z "$VERSION" ]; then
 	VERSION=$DEFAULT_VERSION
 fi
 
 # Unconditionally fetch the tar to find out the real version number
 TARFILE=memcachetest-${VERSION}.tar.gz
-git_fetch $GIT_LOCATION memcachetest-$VERSION $MIRROR_LOCATION/$TARFILE $SHELLPACK_SOURCES/$TARFILE
-
+git_fetch $GIT_LOCATION memcachetest-${VERSION} $MIRROR_LOCATION/$TARFILE $SHELLPACK_SOURCES/$TARFILE
 cd $SHELLPACK_SOURCES
 tar -xf $TARFILE
 if [ $? -ne 0 ]; then
-	error "$P: tar xf memcachetest-${VERSION}.tar.gz failed"
-	popd > /dev/null
-	exit $SHELLPACK_ERROR
+        error "$P: tar xf memcachetest-${VERSION}.tar.gz failed"
+        popd > /dev/null
+        exit $SHELLPACK_ERROR
 fi
 
 # Rename directory to something we expect.
 DST_DIR=`tar tf $TARFILE | head -n 1 | awk -F / '{print $1}'`
 mv $DST_DIR memcachetest-${VERSION}
 pushd memcachetest-${VERSION} > /dev/null || die Failed to rename tar
-echo "m4_define([VERSION_NUMBER], [0.8.3_6_g35fd1b9])" > m4/version.m4
 
-# Build
+pushd $SHELLPACK_SOURCES/memcachetest-${VERSION} || die Failed to change to source directory
+echo "m4_define([VERSION_NUMBER], [0.8.3_6_g35fd1b9])" > m4/version.m4
 ./config/autorun.sh || die Failed to generate configure script
-./configure --prefix=$SHELLPACK_SOURCES/memcachetest-${VERSION}-installed || die Failed to configure
-make         || die Failed to build
-make install || die Failed to install
+./configure --prefix=$SHELLPACK_SOURCES/memcachetest-${VERSION}-installed
+if [ $? -ne 0 ]; then
+	error "$P: configure failed"
+	popd > /dev/null
+	exit $SHELLPACK_ERROR
+fi
+make -j$NUMCPUS
+if [ $? -ne 0 ]; then
+	error "$P: make failed"
+	popd > /dev/null
+	exit $SHELLPACK_ERROR
+fi
+make install
+if [ $? -ne 0 ]; then
+	error "$P: make install failed"
+	popd > /dev/null
+	exit $SHELLPACK_ERROR
+fi
 
 echo memcachetest installed successfully
 #### Description memcachetest
-#### Details memcachetest 8
+#### Details memcachetest 13
diff --git a/shellpacks/shellpack-install-netperf b/shellpacks/shellpack-install-netperf
--- a/shellpacks/shellpack-install-netperf
+++ b/shellpacks/shellpack-install-netperf
@@ -1,24 +1,23 @@
 #!/bin/bash
 # Netperf installer
 P=netperf-install
-WEB_LOCATION=ftp://ftp.netperf.org/netperf/archive
-MIRROR_LOCATION="$WEBROOT/netperf/"
 DEFAULT_VERSION=2.4.5
 . $SHELLPACK_INCLUDE/common.sh
+WEB_LOCATION=ftp://ftp.netperf.org/netperf/archive
+MIRROR_LOCATION="$WEBROOT/netperf/"
 
 # Basic argument parser
 while [ "$1" != "" ]; do
-  case "$1" in
-    -v)
-            VERSION=$2
-	    shift 2
-	    ;;
-    *)
-            echo Unrecognised option: $1
-	    shift
-  esac
+	case "$1" in
+	-v)
+		VERSION=$2
+		shift 2
+		;;
+	*)
+		echo Unrecognised option: $1
+		shift
+	esac
 done
-
 if [ -z "$VERSION" ]; then
 	VERSION=$DEFAULT_VERSION
 fi
@@ -26,23 +25,20 @@ fi
 # Unconditionally fetch the tar to find out the real version number
 TARFILE=netperf-${VERSION}.tar.gz
 sources_fetch $WEB_LOCATION/$TARFILE $MIRROR_LOCATION/$TARFILE $SHELLPACK_SOURCES/$TARFILE
-
-# Building from scratch, uncompress the tar
 cd $SHELLPACK_SOURCES
-tar xf $TARFILE
+tar -xf $TARFILE
 if [ $? -ne 0 ]; then
-  error "$P: tar xf netperf-${VERSION}.tar.gz failed"
-  popd > /dev/null
-  exit $SHELLPACK_ERROR
+        error "$P: tar xf netperf-${VERSION}.tar.gz failed"
+        popd > /dev/null
+        exit $SHELLPACK_ERROR
 fi
 
 # Rename directory to something we expect.
-[ "$DST_DIR" != "netperf-${VERSION}/" ] && mv $DST_DIR netperf-${VERSION}
+DST_DIR=`tar tf $TARFILE | head -n 1 | awk -F / '{print $1}'`
+mv $DST_DIR netperf-${VERSION}
+pushd netperf-${VERSION} > /dev/null || die Failed to rename tar
 
-# Build the library
-pushd netperf-${VERSION} > /dev/null
-
-# Configure
+pushd $SHELLPACK_SOURCES/netperf-${VERSION} || die Failed to change to source directory
 INSTALLPATH=$SHELLPACK_SOURCES/netperf-${VERSION}-installed
 rm -rf $INSTALLPATH
 CFLAGS="-O2" ./configure --prefix=$INSTALLPATH
@@ -52,22 +48,19 @@ if [ $? -ne 0 ]; then
 	exit $SHELLPACK_ERROR
 fi
 
-# Build
 make
 if [ $? -ne 0 ]; then
 	error "$P: make failed"
 	popd > /dev/null
 	exit $SHELLPACK_ERROR
 fi
-
-# Install
 make install
 if [ $? -ne 0 ]; then
-	error "$P: installation failed"
+	error "$P: make install failed"
 	popd > /dev/null
 	exit $SHELLPACK_ERROR
 fi
 
 echo Netperf installed successfully
 #### Description Netperf benchmark
-#### Details netperf 8
+#### Details netperf 11
diff --git a/shellpacks/shellpack-install-pft b/shellpacks/shellpack-install-pft
--- a/shellpacks/shellpack-install-pft
+++ b/shellpacks/shellpack-install-pft
@@ -1,36 +1,42 @@
 #!/bin/bash
 # This script installs the page fault test
 P=pft-install
-VERSION=0.12x
+DEFAULT_VERSION=0.12x
 . $SHELLPACK_INCLUDE/common.sh
-
-# Basic args parser
-while [ "$1" != "" ]; do
-	case "$1" in
-		-v)
-			VERSION=$2
-			shift 2;;
-		*)	echo Unrecognised option: $1; shift
-	esac
-done
-
-# Download PFT
-TARFILE=pft-${VERSION}.tar.gz
 WEB_LOCATION="http://free.linux.hp.com/~lts/Tools"
 MIRROR_LOCATION="$WEBROOT/pft/$TARFILE"
-sources_fetch $WEB_LOCATION/$TARFILE $MIRROR_LOCATION/$TARFILE $SHELLPACK_SOURCES/$TARFILE
-pushd $SHELLPACK_SOURCES > /dev/null
 
-# Uncompress it
-tar xf pft-${VERSION}.tar.gz
-if [ $? -ne 0 ]; then
-	error "$P: tar xf pft-${VERSION}.tar.gz failed"
-	exit $SHELLPACK_ERROR
+# Basic argument parser
+while [ "$1" != "" ]; do
+	case "$1" in
+	-v)
+		VERSION=$2
+		shift 2
+		;;
+	*)
+		echo Unrecognised option: $1
+		shift
+	esac
+done
+if [ -z "$VERSION" ]; then
+	VERSION=$DEFAULT_VERSION
 fi
 
-# Rename it
-DST_DIR=`tar ztf pft-${VERSION}.tar.gz | head -n 1`
-mv $DST_DIR pft-$VERSION-installed
+# Unconditionally fetch the tar to find out the real version number
+TARFILE=pft-${VERSION}.tar.gz
+sources_fetch $WEB_LOCATION/$TARFILE $MIRROR_LOCATION/$TARFILE $SHELLPACK_SOURCES/$TARFILE
+cd $SHELLPACK_SOURCES
+tar -xf $TARFILE
+if [ $? -ne 0 ]; then
+        error "$P: tar xf pft-${VERSION}.tar.gz failed"
+        popd > /dev/null
+        exit $SHELLPACK_ERROR
+fi
+
+# Rename directory to something we expect.
+DST_DIR=`tar tf $TARFILE | head -n 1 | awk -F / '{print $1}'`
+mv $DST_DIR pft-${VERSION}-installed
+pushd pft-${VERSION}-installed > /dev/null || die Failed to rename tar
 
 # Patch it if necessary
 pushd $SHELLPACK_SOURCES/pft-${VERSION}-installed
@@ -122,7 +128,6 @@ index 2ea0986..5544803 100644
 " | patch -p1 || exit -1
 fi
 
-# Build it
 make
 if [ $? -ne 0 ]; then
 	error "$P: make failed"
@@ -132,4 +137,4 @@ fi
 
 echo pft installed successfully
 #### Description pft
-#### Details pft 5
+#### Details pft 6
diff --git a/shellpacks/shellpack-install-postgresbuild b/shellpacks/shellpack-install-postgresbuild
--- a/shellpacks/shellpack-install-postgresbuild
+++ b/shellpacks/shellpack-install-postgresbuild
@@ -1,8 +1,9 @@
 #!/bin/bash
 # This script installs postgres and leaves it ready for benchmarking
-
 P=postgres-install
-VERSION=9.0.4
+DEFAULT_VERSION=9.0.4
+. $SHELLPACK_INCLUDE/common.sh
+
 LIBHUGETLBFS_VERSION=2.9
 POSTGRES_USER=nobody
 POSTGRES_GROUP=nogroup
@@ -10,40 +11,53 @@ USE_LARGE_PAGES=no
 EFFECTIVE_CACHESIZE=$((756*1048576))
 SHARED_BUFFERS=$((32*1048576))
 WORK_MEM=$((64*1048576))
-. $SHELLPACK_INCLUDE/common.sh
 
 NUMCPUS=`grep processor /proc/cpuinfo | wc -l`
 
-# Basic args parser
+# Basic argument parser
 while [ "$1" != "" ]; do
 	case "$1" in
-		-v)	export VERSION=$2; shift 2;;
-		--cnf)	export CNF_FILE=$2; shift 2;;
-		--postgres-user) 
-			export POSTGRES_USER=$2
-			shift 2;;
-		--use-large-pages)
-			export USE_LARGE_PAGES=yes
-			shift
-			;;
-		--force-build)
-			export FORCE_BUILD=yes
-			shift;;
-		--shutdown)
-			export SHUTDOWN=yes
-			shift;;
-		--effective_cachesize)
-			export EFFECTIVE_CACHESIZE=$2
-			shift 2;;
-		--shared_buffers)
-			export SHARED_BUFFERS=$2
-			shift 2;;
-		--work_mem)
-			export WORK_MEM=$2
-			shift 2;;
-		*)	echo Unrecognised option: $1; shift
+	-v)
+		VERSION=$2
+		shift 2
+		;;
+	--postgres-user)
+		POSTGRES_USER=$2
+		shift 2
+		;;
+	--effective_cachesize)
+		EFFECTIVE_CACHESIZE=$2
+		shift 2
+		;;
+	--shared_buffers)
+		SHARED_BUFFERS=$2
+		shift 2
+		;;
+	--work_mem)
+		WORK_MEM=$2
+		shift 2
+		;;
+	--use-large-pages)
+		USE_LARGE_PAGES=yes
+		shift
+		;;
+	--force-build)
+		FORCE_BUILD=yes
+		shift
+		;;
+	--shutdown)
+		SHUTDOWN=yes
+		shift
+		;;
+	*)
+		echo Unrecognised option: $1
+		shift
 	esac
 done
+if [ -z "$VERSION" ]; then
+	VERSION=$DEFAULT_VERSION
+fi
+
 WEB_LOCATION=http://ftp.ie.postgresql.org/mirrors/ftp.postgresql.org/pub/source/v${VERSION}/postgresql-${VERSION}.tar.gz
 MIRROR_LOCATION="$WEBROOT/postgres/postgresql-${VERSION}.tar.gz"
 
@@ -86,11 +100,18 @@ if [ ! -e $SHELLPACK_SOURCES/postgres-${VERSION}-installed ]; then
 		--enable-assembler \
 		|| die Failed to configure
 
-	echo Building postgres
-	make -j$NUMCPUS || die "Failed to build postgres"
-
-	echo Installing postgres
-	make install || die "Failed to install postgres"
+make -j$NUMCPUS
+if [ $? -ne 0 ]; then
+	error "$P: make failed"
+	popd > /dev/null
+	exit $SHELLPACK_ERROR
+fi
+make install
+if [ $? -ne 0 ]; then
+	error "$P: make install failed"
+	popd > /dev/null
+	exit $SHELLPACK_ERROR
+fi
 	touch $SHELLPACK_SOURCES/postgres-${VERSION}-installed/unconfigured
 fi
 
@@ -280,4 +301,4 @@ fi
 echo postgres successfully installed
 exit $SHELLPACK_SUCCESS
 #### Description Build and setup postgres
-#### Details postgresbuild 18
+#### Details postgresbuild 20
