fsmark: Correct metadata tests, test multiple clients properly
Signed-off-by: Mel Gorman <mgorman@suse.de>

diff --git a/shellpacks/shellpack-install-fsmark b/shellpacks/shellpack-install-fsmark
--- a/shellpacks/shellpack-install-fsmark
+++ b/shellpacks/shellpack-install-fsmark
@@ -37,9 +37,9 @@ sources_fetch $WEB_LOCATION/$VERSION/$TARFILE $MIRROR_LOCATION/$TARFILE $SHELLPA
 cd $SHELLPACK_SOURCES
 tar -xf $TARFILE
 if [ $? -ne 0 ]; then
-        error "$P: tar xf fs_mark-${VERSION}.tar.gz failed"
-        popd > /dev/null
-        exit $SHELLPACK_ERROR
+	error "$P: tar xf fs_mark-${VERSION}.tar.gz failed"
+	popd > /dev/null
+	exit $SHELLPACK_ERROR
 fi
 
 # Rename directory to something we expect.
@@ -57,4 +57,4 @@ fi
 
 echo fsmark installed successfully
 #### Description fsmark
-#### Details fsmark 23
+#### Details fsmark 27
