redis: Add redis benchmark
Signed-off-by: Mel Gorman <mgorman@techsingularity.net>

diff --git a/shellpacks/shellpack-install-redis b/shellpacks/shellpack-install-redis
--- a/shellpacks/shellpack-install-redis
+++ b/shellpacks/shellpack-install-redis
@@ -1,15 +1,15 @@
 #!/bin/bash
-# Netperf installer
-P=netperfmulti-install
-DEFAULT_VERSION=2.4.5
+# Redis installer
+P=redis-install
+DEFAULT_VERSION=3.0.5
 . $SHELLPACK_INCLUDE/common.sh
 TIME_CMD=`which time`
 if [ "$TIME_CMD" = "" ]; then
         TIMEFORMAT="%2Uuser %2Ssystem %Relapsed %P%%CPU"
         TIME_CMD="time"
 fi
-WEB_LOCATION=ftp://ftp.netperf.org/netperf/archive
-MIRROR_LOCATION="$WEBROOT/netperf/"
+WEB_LOCATION=http://download.redis.io/releases
+MIRROR_LOCATION="$WEBROOT/redis/"
 
 # Basic argument parser
 TASKSET_SERVER=
@@ -45,43 +45,34 @@ if [ -z "$VERSION" ]; then
 fi
 
 # Unconditionally fetch the tar to find out the real version number
-TARFILE=netperf-${VERSION}.tar.gz
+TARFILE=redis-${VERSION}.tar.gz
 sources_fetch $WEB_LOCATION/$TARFILE $MIRROR_LOCATION/$TARFILE $SHELLPACK_SOURCES/$TARFILE
 cd $SHELLPACK_SOURCES
 tar -xf $TARFILE
 if [ $? -ne 0 ]; then
-	error "$P: tar xf netperf-${VERSION}.tar.gz failed"
+	error "$P: tar xf redis-${VERSION}.tar.gz failed"
 	popd > /dev/null
 	exit $SHELLPACK_ERROR
 fi
 
 # Rename directory to something we expect.
 DST_DIR=`tar tf $TARFILE | head -n 1 | awk -F / '{print $1}'`
-mv $DST_DIR netperfmulti-${VERSION}
-pushd netperfmulti-${VERSION} > /dev/null || die Failed to rename tar
+mv $DST_DIR redis-${VERSION}
+pushd redis-${VERSION} > /dev/null || die Failed to rename tar
 
-pushd $SHELLPACK_SOURCES/netperfmulti-${VERSION} || die Failed to change to source directory
-export CFLAGS="-O2 $CFLAGS_MMTESTS_EXTRA"
-eval ./configure --prefix=$SHELLPACK_SOURCES/netperfmulti-${VERSION}-installed 
-if [ $? -ne 0 ]; then
-	error "$P: configure failed"
-	popd > /dev/null
-	exit $SHELLPACK_ERROR
-fi
-unset CFLAGS
+pushd $SHELLPACK_SOURCES/redis-${VERSION} || die Failed to change to source directory
 make -j$NUMCPUS 
 if [ $? -ne 0 ]; then
 	error "$P: make failed"
 	popd > /dev/null
 	exit $SHELLPACK_ERROR
 fi
-make install
-if [ $? -ne 0 ]; then
-	error "$P: make install failed"
-	popd > /dev/null
-	exit $SHELLPACK_ERROR
-fi
+make PREFIX=$SHELLPACK_SOURCES/redis-${VERSION}-installed install || die Failed to install redis
 
-echo Netperf installed successfully
-#### Description Netperf benchmark with multiple instances
-#### Details netperfmulti 16
+mkdir $SHELLPACK_SOURCES/redis-${VERSION}-installed/etc || die Failed to create configuration directory
+cat redis.conf | sed -e 's/^save.*//' > $SHELLPACK_SOURCES/redis-${VERSION}-installed/etc/redis-memonly.conf
+cp redis.conf $SHELLPACK_SOURCES/redis-${VERSION}-installed/etc/redis-default-persist.conf
+
+echo Redis installed successfully
+#### Description redis
+#### Details redis 15
