mariadbbuild: update server version
Similar to apache, we currently use quite an old version
of mysql/mariadb. Update from 10.0.12 to 10.1.8.

Signed-off-by: Davidlohr Bueso <dave@stgolabs.net>
Signed-off-by: Mel Gorman <mgorman@suse.com>

diff --git a/shellpacks/shellpack-install-mariadbbuild b/shellpacks/shellpack-install-mariadbbuild
--- a/shellpacks/shellpack-install-mariadbbuild
+++ b/shellpacks/shellpack-install-mariadbbuild
@@ -1,8 +1,13 @@
 #!/bin/bash
 # This script installs mariadb and leaves it ready for benchmarking
 P=mariadb-install
-DEFAULT_VERSION=10.0.12
+DEFAULT_VERSION=10.1.8
 . $SHELLPACK_INCLUDE/common.sh
+TIME_CMD=`which time`
+if [ "$TIME_CMD" = "" ]; then
+        TIMEFORMAT="%2Uuser %2Ssystem %Relapsed %P%%CPU"
+        TIME_CMD="time"
+fi
 
 MARIADB_USER=nobody
 MARIADB_GROUP=nogroup
@@ -12,11 +17,21 @@ NUMCPUS=`grep processor /proc/cpuinfo | wc -l`
 # Basic argument parser
 TASKSET_SERVER=
 TASKSET_CLIENT=
+SERVERSIDE_COMMAND=none
+SERVERSIDE_NAME=`date +%Y%m%d-%H%M-%S`
 
 while [ "$1" != "" ]; do
 	case "$1" in
 	-v)
 		VERSION=$2
+		shift 2
+		;;
+	--serverside-command)
+		SERVERSIDE_COMMAND=$2
+		shift 2
+		;;
+	--serverside-name)
+		SERVERSIDE_NAME=$2
 		shift 2
 		;;
 	--mariadb-user)
@@ -69,9 +84,9 @@ sources_fetch $WEB_LOCATION/$TARFILE $MIRROR_LOCATION/$TARFILE $SHELLPACK_SOURCE
 cd $SHELLPACK_SOURCES
 tar -xf $TARFILE
 if [ $? -ne 0 ]; then
-        error "$P: tar xf mariadb-${VERSION}.tar.gz failed"
-        popd > /dev/null
-        exit $SHELLPACK_ERROR
+	error "$P: tar xf mariadb-${VERSION}.tar.gz failed"
+	popd > /dev/null
+	exit $SHELLPACK_ERROR
 fi
 
 # Rename directory to something we expect.
@@ -119,4 +134,4 @@ mv ${MARIADB_CONF}.tmp $MARIADB_CONF
 echo mariadb successfully installed
 exit $SHELLPACK_SUCCESS
 #### Description mariadbbuild
-#### Details mariadbbuild 30
+#### Details mariadbbuild 33
