wikibench: Use common helpers and mirrors for helper binaries
Signed-off-by: Mel Gorman <mgorman@techsingularity.net>

diff --git a/shellpacks/shellpack-bench-wikibench b/shellpacks/shellpack-bench-wikibench
--- a/shellpacks/shellpack-bench-wikibench
+++ b/shellpacks/shellpack-bench-wikibench
@@ -120,16 +120,43 @@ WORKER_TIMEOUT=300 # ms
 cd wikijector/
 
 # Download Apache httpcomponents libraries (binary versions)
+WEB_LOCATION=http://apache.mirrors.ionfish.org//httpcomponents/httpclient/binary
 HTTPCOMPONENTS_CLIENT_VERSION=4.5.1
-wget -c http://apache.mirrors.ionfish.org//httpcomponents/httpclient/binary/httpcomponents-client-$HTTPCOMPONENTS_CLIENT_VERSION-bin.tar.gz
+# Unconditionally fetch the tar to find out the real version number
+TARFILE=httpcomponents-client-$HTTPCOMPONENTS_CLIENT_VERSION-bin.tar.gz
+sources_fetch $WEB_LOCATION/$TARFILE $MIRROR_LOCATION/$TARFILE $SHELLPACK_SOURCES/$TARFILE
+cd $SHELLPACK_SOURCES
+tar -xf $TARFILE
+if [ $? -ne 0 ]; then
+	error "$P: tar xf httpcomponents-client-$HTTPCOMPONENTS_CLIENT_VERSION-bin.tar.gz failed"
+	popd > /dev/null
+	exit $SHELLPACK_ERROR
+fi
+
+# Rename directory to something we expect.
+DST_DIR=`tar tf $TARFILE | head -n 1 | awk -F / '{print $1}'`
+mv $DST_DIR httpcomponents-client-$HTTPCOMPONENTS_CLIENT_VERSION
+pushd httpcomponents-client-$HTTPCOMPONENTS_CLIENT_VERSION > /dev/null || die Failed to rename tar
+mv $SHELLPACK_SOURCES/httpcomponents-client-$HTTPCOMPONENTS_CLIENT_VERSION . || die Failed to fetch httpcomponents-client
+
+WEB_LOCATION=http://apache.mirrors.ionfish.org//httpcomponents/httpcore/binary
 HTTPCOMPONENTS_CORE_VERSION=4.4.4
-wget -c http://apache.mirrors.ionfish.org//httpcomponents/httpcore/binary/httpcomponents-core-$HTTPCOMPONENTS_CORE_VERSION-bin.tar.gz
+# Unconditionally fetch the tar to find out the real version number
+TARFILE=httpcomponents-core-$HTTPCOMPONENTS_CORE_VERSION-bin.tar.gz
+sources_fetch $WEB_LOCATION/$TARFILE $MIRROR_LOCATION/$TARFILE $SHELLPACK_SOURCES/$TARFILE
+cd $SHELLPACK_SOURCES
+tar -xf $TARFILE
+if [ $? -ne 0 ]; then
+	error "$P: tar xf httpcomponents-core-$HTTPCOMPONENTS_CORE_VERSION-bin.tar.gz failed"
+	popd > /dev/null
+	exit $SHELLPACK_ERROR
+fi
 
-tar xf httpcomponents-client-$HTTPCOMPONENTS_CLIENT_VERSION-bin.tar.gz ||
-die $P: tar xf httpcomponents-client-$HTTPCOMPONENTS_CLIENT_VERSION-bin.tar.gz
-
-tar xf httpcomponents-core-$HTTPCOMPONENTS_CORE_VERSION-bin.tar.gz ||
-die $P: tar xf httpcomponents-core-$HTTPCOMPONENTS_CORE_VERSION-bin.tar.gz
+# Rename directory to something we expect.
+DST_DIR=`tar tf $TARFILE | head -n 1 | awk -F / '{print $1}'`
+mv $DST_DIR httpcomponents-core-$HTTPCOMPONENTS_CORE_VERSION
+pushd httpcomponents-core-$HTTPCOMPONENTS_CORE_VERSION > /dev/null || die Failed to rename tar
+mv $SHELLPACK_SOURCES/httpcomponents-core-$HTTPCOMPONENTS_CORE_VERSION . || die Failed to fetch httpcomponents-core
 
 WIKIBENCH_PERMIL=
 
@@ -151,9 +178,6 @@ wget -c "http://linux-scalability.org/benchmarks/${SAMPLED_FILE}.gz"
 # idx 0 is the controller, the rest are workers
 PIDARR=()
 CONTROLLER_IDX=0
-
-# hack for opensuse. SLE12 already has this...
-export JAVA_HOME=/usr/lib64/jvm/java
 
 $SHELLPACK_INCLUDE/shellpack-bench-mediawikibuild --start
 
@@ -294,4 +318,4 @@ $SHELLPACK_INCLUDE/shellpack-bench-mediawikibuild --stop
 
 exit $SHELLPACK_SUCCESS
 #### Description wikibench
-#### Details wikibench-bench 1
+#### Details wikibench-bench 3
diff --git a/shellpacks/shellpack-install-phpbuild b/shellpacks/shellpack-install-phpbuild
--- a/shellpacks/shellpack-install-phpbuild
+++ b/shellpacks/shellpack-install-phpbuild
@@ -97,9 +97,22 @@ printf '%s\n\t%s\n%s\n' '<FilesMatch "\.phps$">' 'SetHandler application/x-httpd
 echo Generating phpinfo.php file
 echo "<?php phpinfo(); ?>" >> $SHELLPACK_SOURCES/apachebuild-${APACHE_VERSION}-installed/htdocs/phpinfo.php
 
-wget -c https://xcache.lighttpd.net/pub/Releases/$XCACHE_VERSION/xcache-$XCACHE_VERSION.tar.gz
-tar xf xcache-$XCACHE_VERSION.tar.gz || die Failed to setup php xcode
-cd xcache-$XCACHE_VERSION
+WEB_LOCATION=https://xcache.lighttpd.net/pub/Releases/$XCACHE_VERSION
+# Unconditionally fetch the tar to find out the real version number
+TARFILE=xcache-$XCACHE_VERSION.tar.gz
+sources_fetch $WEB_LOCATION/$TARFILE $MIRROR_LOCATION/$TARFILE $SHELLPACK_SOURCES/$TARFILE
+cd $SHELLPACK_SOURCES
+tar -xf $TARFILE
+if [ $? -ne 0 ]; then
+	error "$P: tar xf xcache-$XCACHE_VERSION.tar.gz failed"
+	popd > /dev/null
+	exit $SHELLPACK_ERROR
+fi
+
+# Rename directory to something we expect.
+DST_DIR=`tar tf $TARFILE | head -n 1 | awk -F / '{print $1}'`
+mv $DST_DIR xcache-$XCACHE_VERSION
+pushd xcache-$XCACHE_VERSION > /dev/null || die Failed to rename tar
 $SHELLPACK_SOURCES/phpbuild-${PHP_VERSION}-installed/bin/phpize
 export CFLAGS="-O2 $CFLAGS_MMTESTS_EXTRA"
 eval ./configure --prefix=$SHELLPACK_SOURCES/xcode-${XCACHE_VERSION}-installed --enable-xcache --with-php-config=$SHELLPACK_SOURCES/phpbuild-${PHP_VERSION}-installed/bin/php-config
@@ -126,4 +139,4 @@ cat xcache.ini >> $SHELLPACK_SOURCES/phpbuild-${PHP_VERSION}-installed/php.ini
 
 echo php installed successfully
 #### Description phpbuild
-#### Details phpbuild 1
+#### Details phpbuild 3
diff --git a/shellpacks/shellpack-install-wikibench b/shellpacks/shellpack-install-wikibench
--- a/shellpacks/shellpack-install-wikibench
+++ b/shellpacks/shellpack-install-wikibench
@@ -1,13 +1,16 @@
 #!/bin/bash
 # wikibench installer
-P=wikibench-install
-VERSION=0.3.1
-TARFILE=wikibench-${VERSION}.tar.gz
-WEB_LOCATION=http://www.wikibench.eu/wp-content/uploads/2011/01/$TARFILE
+
+P=wikibench
+DEFAULT_VERSION=0.3.1
+. $SHELLPACK_INCLUDE/common.sh
+TIME_CMD=`which time`
+if [ "$TIME_CMD" = "" ]; then
+        TIMEFORMAT="%2Uuser %2Ssystem %Relapsed %P%%CPU"
+        TIME_CMD="time"
+fi
+WEB_LOCATION=http://www.wikibench.eu/wp-content/uploads/2011/01
 MIRROR_LOCATION=$WEBROOT/wikibench
-APACHE_VERSION=2.4.17
-APR_VERSION=1.5.2
-MARIADB_VERSIO=10.1.8
 MEDIAWIKI_VERSION=1.18.6
 
 # Basic argument parser
@@ -53,18 +56,22 @@ if [ ! -e $SHELLPACK_SOURCES/mediawiki-build-${MEDIAWIKI_VERSION}-installed ]; t
 	echo Mediawiki and httpd server successfully installed.
 fi
 
-sources_fetch $WEB_LOCATION $MIRROR_LOCATION $SHELLPACK_SOURCES/$TARFILE
-
+# Unconditionally fetch the tar to find out the real version number
+TARFILE=wikibench-${VERSION}.tar.gz
+sources_fetch $WEB_LOCATION/$TARFILE $MIRROR_LOCATION/$TARFILE $SHELLPACK_SOURCES/$TARFILE
 cd $SHELLPACK_SOURCES
-tar xf $TARFILE || die $P: tar xf wikibench-$VERSION.tar.gz failed
+tar -xf $TARFILE
+if [ $? -ne 0 ]; then
+	error "$P: tar xf wikibench-${VERSION}.tar.gz failed"
+	popd > /dev/null
+	exit $SHELLPACK_ERROR
+fi
 
 # Rename directory to something we expect.
-DST_DIR=`tar tf $TARFILE | head -n 1`
-[ "$DST_DIR" != "wikibench-${VERSION}-installed/" ] && mv $DST_DIR wikibench-${VERSION}-installed
-
-# Build the library
-pushd wikibench-${VERSION}-installed > /dev/null
+DST_DIR=`tar tf $TARFILE | head -n 1 | awk -F / '{print $1}'`
+mv $DST_DIR wikibench-${VERSION}-installed
+pushd wikibench-${VERSION}-installed > /dev/null || die Failed to rename tar
 
 echo wikibench installed successfully
 #### Description wikibench
-#### Details wikibench 1
+#### Details wikibench 3
