apachebuild: fix apache compilation wrt pcre
... specifically s/pcre/pcrebuild when passing --with-pcre
to apache's configure script. Otherwise, apache will fail
to build altogether as it cannot find the needed lib.

Signed-off-by: Davidlohr Bueso <dave@stgolabs.net>
Signed-off-by: Mel Gorman <mgorman@suse.com>

diff --git a/shellpacks/shellpack-install-apachebuild b/shellpacks/shellpack-install-apachebuild
--- a/shellpacks/shellpack-install-apachebuild
+++ b/shellpacks/shellpack-install-apachebuild
@@ -3,6 +3,11 @@
 P=apachebuild-install
 DEFAULT_VERSION=2.4.10
 . $SHELLPACK_INCLUDE/common.sh
+TIME_CMD=`which time`
+if [ "$TIME_CMD" = "" ]; then
+        TIMEFORMAT="%2Uuser %2Ssystem %Relapsed %P%%CPU"
+        TIME_CMD="time"
+fi
 
 APR_VERSION=1.5.1
 PCRE_VERSION=8.35
@@ -15,11 +20,21 @@ install-depends gcc gcc-c++
 # Basic argument parser
 TASKSET_SERVER=
 TASKSET_CLIENT=
+SERVERSIDE_COMMAND=none
+SERVERSIDE_NAME=`date +%Y%m%d-%H%M-%S`
 
 while [ "$1" != "" ]; do
 	case "$1" in
 	-v)
 		VERSION=$2
+		shift 2
+		;;
+	--serverside-command)
+		SERVERSIDE_COMMAND=$2
+		shift 2
+		;;
+	--serverside-name)
+		SERVERSIDE_NAME=$2
 		shift 2
 		;;
 	*)
@@ -41,9 +56,9 @@ sources_fetch $WEB_LOCATION/$TARFILE $MIRROR_LOCATION/$TARFILE $SHELLPACK_SOURCE
 cd $SHELLPACK_SOURCES
 tar -xf $TARFILE
 if [ $? -ne 0 ]; then
-        error "$P: tar xf httpd-${VERSION}.tar.gz failed"
-        popd > /dev/null
-        exit $SHELLPACK_ERROR
+	error "$P: tar xf httpd-${VERSION}.tar.gz failed"
+	popd > /dev/null
+	exit $SHELLPACK_ERROR
 fi
 
 # Rename directory to something we expect.
@@ -60,7 +75,7 @@ fi
 # Build
 pushd $SHELLPACK_SOURCES/apachebuild-${VERSION} || die Failed to change to source directory
 export CFLAGS="-O2 $CFLAGS_MMTESTS_EXTRA"
-eval ./configure --prefix=$SHELLPACK_SOURCES/apachebuild-${VERSION}-installed --with-apr=$SHELLPACK_SOURCES/aprbuild-${APR_VERSION}-installed --with-apr-util=$SHELLPACK_SOURCES/aprbuild-${APR_VERSION}-installed --with-pcre=$SHELLPACK_SOURCES/pcre-${PCRE_VERSION}-installed
+eval ./configure --prefix=$SHELLPACK_SOURCES/apachebuild-${VERSION}-installed --with-apr=$SHELLPACK_SOURCES/aprbuild-${APR_VERSION}-installed --with-apr-util=$SHELLPACK_SOURCES/aprbuild-${APR_VERSION}-installed --with-pcre=$SHELLPACK_SOURCES/pcrebuild-${PCRE_VERSION}-installed
 if [ $? -ne 0 ]; then
 	error "$P: configure failed"
 	popd > /dev/null
@@ -82,4 +97,4 @@ fi
 
 echo httpd installed successfully
 #### Description apachebuild
-#### Details apachebuild 6
+#### Details apachebuild 7
