perfbuild: Move users of perf onto kernel 4.1
Signed-off-by: Mel Gorman <mgorman@suse.de>

diff --git a/shellpacks/shellpack-install-vmscale b/shellpacks/shellpack-install-vmscale
--- a/shellpacks/shellpack-install-vmscale
+++ b/shellpacks/shellpack-install-vmscale
@@ -3,17 +3,32 @@
 P=vmscale-install
 DEFAULT_VERSION=1
 . $SHELLPACK_INCLUDE/common.sh
+TIME_CMD=`which time`
+if [ "$TIME_CMD" = "" ]; then
+        TIMEFORMAT="%2Uuser %2Ssystem %Relapsed %P%%CPU"
+        TIME_CMD="time"
+fi
 GIT_LOCATION=https://github.com/aristeu/vm-scalability
 MIRROR_LOCATION="$WEBROOT/vmscale"
 
 # Basic argument parser
 TASKSET_SERVER=
 TASKSET_CLIENT=
+SERVERSIDE_COMMAND=none
+SERVERSIDE_NAME=`date +%Y%m%d-%H%M-%S`
 
 while [ "$1" != "" ]; do
 	case "$1" in
 	-v)
 		VERSION=$2
+		shift 2
+		;;
+	--serverside-command)
+		SERVERSIDE_COMMAND=$2
+		shift 2
+		;;
+	--serverside-name)
+		SERVERSIDE_NAME=$2
 		shift 2
 		;;
 	*)
@@ -35,9 +50,9 @@ git_fetch $GIT_LOCATION vmscale-${VERSION}-installed $MIRROR_LOCATION/$TARFILE $
 cd $SHELLPACK_SOURCES
 tar -xf $TARFILE
 if [ $? -ne 0 ]; then
-        error "$P: tar xf vmscale-${VERSION}.tar.gz failed"
-        popd > /dev/null
-        exit $SHELLPACK_ERROR
+	error "$P: tar xf vmscale-${VERSION}.tar.gz failed"
+	popd > /dev/null
+	exit $SHELLPACK_ERROR
 fi
 
 # Rename directory to something we expect.
@@ -158,4 +173,4 @@ index 758d32c..138bf84 100755
  # sparse files won't work as expected on tmpfs/nfs
  create_sparse_root () {
 #### Description vm scalability test suite
-#### Details vmscale 30
+#### Details vmscale 31
