hackbench: Ignore failures
Signed-off-by: Mel Gorman <mgorman@techsingularity.net>

diff --git a/shellpack_src/src/hackbench/hackbench-bench b/shellpack_src/src/hackbench/hackbench-bench
--- a/shellpack_src/src/hackbench/hackbench-bench
+++ b/shellpack_src/src/hackbench/hackbench-bench
@@ -40,8 +40,12 @@ RESULTSLOG=$LOGDIR_RESULTS/hackbench
 		$TIME_CMD -o $LOGDIR_RESULTS/time-$NR_THREADS-$ITERATION  \
 			./hackbench $CONN_TYPE $NR_THREADS $HACKBENCH_TYPE $HACKBENCH_LOOPS \
 				> $LOGDIR_RESULTS/hackbench-$NR_THREADS-$ITERATION
+
+		# Failure likely due to open file or pid limitations
 		if [ $? -ne 0 ]; then
-			die Failed to run hackbench
+			monitor_post_hook $LOGDIR_RESULTS $NR_THREADS
+			rm $LOGDIR_RESULTS/hackbench-$NR_THREADS-$ITERATION
+			exit $SHELLPACK_SUCCESS
 		fi
 	###SHELLPACK iteration_end $HACKBENCH_ITERATIONS
 	
diff --git a/shellpacks/shellpack-bench-hackbench b/shellpacks/shellpack-bench-hackbench
--- a/shellpacks/shellpack-bench-hackbench
+++ b/shellpacks/shellpack-bench-hackbench
@@ -134,8 +134,12 @@ for ITERATION in `seq 1 $HACKBENCH_ITERATIONS`; do
 		$TIME_CMD -o $LOGDIR_RESULTS/time-$NR_THREADS-$ITERATION  \
 			./hackbench $CONN_TYPE $NR_THREADS $HACKBENCH_TYPE $HACKBENCH_LOOPS \
 				> $LOGDIR_RESULTS/hackbench-$NR_THREADS-$ITERATION
+
+		# Failure likely due to open file or pid limitations
 		if [ $? -ne 0 ]; then
-			die Failed to run hackbench
+			monitor_post_hook $LOGDIR_RESULTS $NR_THREADS
+			rm $LOGDIR_RESULTS/hackbench-$NR_THREADS-$ITERATION
+			exit $SHELLPACK_SUCCESS
 		fi
 done
 	
@@ -144,4 +148,4 @@ done
 
 exit $RETVAL
 #### Description Run the HackBench benchmark
-#### Details hackbench-bench 30
+#### Details hackbench-bench 31
