libmicro: Retry build once
Signed-off-by: Mel Gorman <mgorman@suse.com>

diff --git a/shellpack_src/bin/rewrite-shellpack b/shellpack_src/bin/rewrite-shellpack
--- a/shellpack_src/bin/rewrite-shellpack
+++ b/shellpack_src/bin/rewrite-shellpack
@@ -300,6 +300,20 @@ if [ \$? -ne 0 ]; then
 	exit \$SHELLPACK_ERROR
 fi
 EOC
+	} elsif ($command eq "make_retry") {
+		my $opts = join(" ", @details);
+		print <<EOC
+make -j\$NUMCPUS $opts
+if [ \$? -ne 0 ]; then
+	make -j\$NUMCPUS $opts
+	if [ \$? -ne 0 ]; then
+		error "\$P: make failed"
+		popd > /dev/null
+		exit \$SHELLPACK_ERROR
+	fi
+fi
+EOC
+
 	} elsif ($command eq "make_clean") {
 		print <<EOC
 make clean
diff --git a/shellpacks/shellpack-install-libmicro-regular b/shellpacks/shellpack-install-libmicro-regular
--- a/shellpacks/shellpack-install-libmicro-regular
+++ b/shellpacks/shellpack-install-libmicro-regular
@@ -87,11 +87,14 @@ if [ $? -ne 0 ]; then
 fi
 make -j$NUMCPUS 
 if [ $? -ne 0 ]; then
-	error "$P: make failed"
-	popd > /dev/null
-	exit $SHELLPACK_ERROR
+	make -j$NUMCPUS 
+	if [ $? -ne 0 ]; then
+		error "$P: make failed"
+		popd > /dev/null
+		exit $SHELLPACK_ERROR
+	fi
 fi
 
 echo libmicro installed successfully
 #### Description libmicro-regular
-#### Details libmicro-regular 7
+#### Details libmicro-regular 8
