updated to hpc env module

diff --git a/shellpack_src/src/openfoam/openfoam-bench b/shellpack_src/src/openfoam/openfoam-bench
--- a/shellpack_src/src/openfoam/openfoam-bench
+++ b/shellpack_src/src/openfoam/openfoam-bench
@@ -12,21 +12,15 @@
 
 # Install openmpi requirements
 if [ "$OPENFOAM_OPENMPI_VERSION" = "openmpi3" ]; then
-	install-depends openmpi3 openmpi3-devel
+	install-depends openmpi3-gnu-hpc-devel
+	module load gnu openmpi/3 || die "Could not load openmpi/3 module"
 elif [ "$OPENFOAM_OPENMPI_VERSION" = "openmpi2" ]; then
-	install-depends openmpi2 openmpi2-devel
+	install-depends openmpi2-gnu-hpc-devel
+	module load gnu openmpi/2 || die "Could not load openmpi/2 module"
 else
-	install-depends openmpi openmpi-devel
+	die "\$OPENFOAM_OPENMPI_VERSION must be openmpi2 or openmpi3"
 fi
 
-# Set openmpi environment
-if [ "$OPENFOAM_MPI_PATH" != "" ]; then
-	export PATH=$PATH:$OPENFOAM_MPI_PATH
-fi
-
-if [ "$OPENFOAM_MPI_LIBPATH" != "" ]; then
-	export LD_LIBRARY_PATH=$OPENFOAM_MPI_LIBPATH
-fi
 export OMPI_TMPDIR=$SHELLPACK_DATA
 export TMPDIR=$SHELLPACK_DATA
 
@@ -34,7 +28,7 @@ export TMPDIR=$SHELLPACK_DATA
 ###SHELLPACK init_complete
 
 cd $SHELLPACK_SOURCES/openfoambuild-$VERSION-installed/ || die "Failed to cd to openfoam installation directory"
-source etc/bashrc "Failed to source bash environment"
+source etc/bashrc || die "Failed to source bash environment"
 
 # Configure benchmark
 case $OPENFOAM_MODEL in
diff --git a/shellpack_src/src/openfoambuild/openfoambuild-install b/shellpack_src/src/openfoambuild/openfoambuild-install
--- a/shellpack_src/src/openfoambuild/openfoambuild-install
+++ b/shellpack_src/src/openfoambuild/openfoambuild-install
@@ -3,7 +3,7 @@
 GIT_LOCATION=https://develop.openfoam.com/Development/openfoam.git
 MIRROR_LOCATION="$WEBROOT/openfoambuild/"
 
-install-depends cmake boost-devel gnuplot mpfr-devel openmpi-devel glu-devel
+install-depends cmake boost-devel gnuplot mpfr-devel glu-devel
 	libQtWebKit-devel libqt4-devel qt4-assistant-adp-devel qt4-x11-tools
 
 ###SHELLPACK parseargBegin
@@ -24,6 +24,7 @@ if [ ! -e ThirdParty ]; then
 fi
 
 source etc/bashrc || die "Failed to source etc/bashrc"
+module load gnu openmpi || die "Failed to load openmi module"
 cd "$WM_PROJECT_DIR" || die "Failed to change to WM_PROJECT_DIR"
 foamSystemCheck || die "Failed foamSystemCheck"
 ./Allwmake -s -l -j || die "Failed to build Allwmake"
