abinit: Update build dependencies for newer distributions
Signed-off-by: Mel Gorman <mgorman@techsingularity.net>

diff --git a/shellpack_src/src/abinit/abinit-bench b/shellpack_src/src/abinit/abinit-bench
--- a/shellpack_src/src/abinit/abinit-bench
+++ b/shellpack_src/src/abinit/abinit-bench
@@ -1,5 +1,5 @@
 #!/bin/bash
-###SHELLPACK preamble abinit-bench 8.10.2
+###SHELLPACK preamble abinit-bench 10.4.7
 ###SHELLPACK parseargBegin
 ###SHELLPACK parseargParam --model      ABINIT_MODEL
 ###SHELLPACK parseargParam --processes  ABINIT_PROCESSES
@@ -7,12 +7,11 @@
 ###SHELLPACK parseargEnd
 ###SHELLPACK monitor_hooks
 
-export BLAS_VERSION="v0.3.10"
+export BLAS_VERSION="v0.3.30"
 export SCALAPACK_MAKE_FLAGS="-DBUILD_SHARED_LIBS=on"
-export SCALAPACK_VERSION="2.1.0"
-export XC_VERSION="2.2.2"
+export SCALAPACK_VERSION="46d1837e0f6f"
 export ATOMPAW_VERSION="4.0.0.13"
-export FFTW_VERSION="3.3.7"
+export FFTW_VERSION="3.3.10"
 
 MPIRUN=
 if [ "$ABINIT_OPENMPI_VERSION" != "" ]; then
@@ -22,15 +21,6 @@ if [ "$ABINIT_OPENMPI_VERSION" != "" ]; then
 	MPIRUN="mpirun $ABINIT_MPI_OPTS $MMTESTS_MPI_OPTS -np $ABINIT_PROCESSES"
 	export OMP_NUM_THREADS=$ABINIT_THREADS
 fi
-
-###SHELLPACK check_external_install_required blasbuild      blasbuild-${BLAS_VERSION}           ${BLAS_VERSION}
-###SHELLPACK check_external_install_required scalapackbuild scalapackbuild-${SCALAPACK_VERSION} ${SCALAPACK_VERSION}
-###SHELLPACK check_external_install_required xcbuild        xcbuild-${XC_VERSION}               ${XC_VERSION}
-###SHELLPACK check_external_install_required atompawbuild   atompawbuild-${ATOMPAW_VERSION}     ${ATOMPAW_VERSION}
-###SHELLPACK check_external_install_required fftwbuild      fftwbuild-${FFTW_VERSION}           ${FFTW_VERSION}
-export LD_LIBRARY_PATH="$SHELLPACK_SOURCES/abinitdeps-installed/$MMTESTS_LIBDIR:$SHELLPACK_SOURCES/abinitdeps-installed/$MMTESTS_LIBDIR:$LD_LIBRARY_PATH"
-export PATH=$SHELLPACK_SOURCES/abinitdeps-installed/bin:$PATH
-###SHELLPACK check_install_required_continue abinit-$VERSION
 
 export ABI_HOME=$SHELLPACK_SOURCES/abinit-${VERSION}-installed
 export PATH=$ABI_HOME/src/98_main/:$PATH
@@ -51,70 +41,70 @@ STEP=
 FILES=
 SOURCE_DATA=
 STAGE_DATA=
+STAGE_NAME=
+BENCH_CMD="$MPIRUN abinit"
 prepare_stage() {
-	STEP=`echo $STAGE | awk -F : '{print $1}'`
-	FILES=`echo $STAGE | awk -F : '{print $2}'`
-	SOURCE_DATA=`echo $STAGE | awk -F : '{print $3}'`
-	STAGE_DATA=`echo $STAGE | awk -F : '{print $4}'`
+        STEP=`echo $STAGE | awk -F : '{print $1}'`
+        FILES=`echo $STAGE | awk -F : '{print $2}'`
+        SOURCE_DATA=`echo $STAGE | awk -F : '{print $3}'`
+        STAGE_DATA=`echo $STAGE | awk -F : '{print $4}'`
 
-	if [ "$SOURCE_DATA" != "" ]; then
-		ln -s $SOURCE_DATA $STAGE_DATA || die "Failed to symbolic link $SOURCE_DATA $STAGE_DATA"
-	fi
-	cp ../$FILES . || die "Failed to copy $FILES"
-	echo $FILES | sed -e 's/.files//' > $LOGDIR_RESULTS/stage-$STEP.name
+        if [ "$SOURCE_DATA" != "" ]; then
+                ln -s $SOURCE_DATA $STAGE_DATA || die "Failed to symbolic link $SOURCE_DATA $STAGE_DATA"
+        fi
+        cp ../$FILES . || die "Failed to copy $FILES"
+        echo $FILES | sed -e 's/.files//' > $LOGDIR_RESULTS/stage-$STEP.name
+	STAGE_NAME=`echo $FILES | sed -e 's/.files//'`
 }
 
+###SHELLPACK init_only_start
+###SHELLPACK check_external_install_required blasbuild      blasbuild-${BLAS_VERSION}           ${BLAS_VERSION}
+###SHELLPACK check_external_install_required scalapackbuild scalapackbuild-${SCALAPACK_VERSION} ${SCALAPACK_VERSION}
+###SHELLPACK check_external_install_required atompawbuild   atompawbuild-${ATOMPAW_VERSION}     ${ATOMPAW_VERSION}
+###SHELLPACK check_external_install_required fftwbuild      fftwbuild-${FFTW_VERSION}           ${FFTW_VERSION}
+export LD_LIBRARY_PATH="$SHELLPACK_SOURCES/abinitdeps-installed/$MMTESTS_LIBDIR:$SHELLPACK_SOURCES/abinitdeps-installed/$MMTESTS_LIBDIR:$LD_LIBRARY_PATH"
+export PATH=$SHELLPACK_SOURCES/abinitdeps-installed/bin:$PATH
+###SHELLPACK check_install_required_continue abinit-$VERSION
+
 cd $ABI_TESTS/tutoparal/Input/ || die "Failed to cd to $ABI_TESTS/tutoparal/Input/"
-if [ "$INSTALL_ONLY" = "yes" ]; then
-	rm -rf Work
-	mkdir Work || die "Failed to create work directory"
-	cd Work
+rm -rf Work
+mkdir Work || die "Failed to create work directory"
+cd Work
 
-	if [ "$ABINIT_PREPARE" = "yes" ]; then
-		for STAGE in `echo $PREPARE_STAGE_MAP`; do
-			STEP=`echo $STAGE | awk -F : '{print $1}'`
-			prepare_stage
-			echo Preparing $STAGE
-			$MPIRUN abinit < ../$FILES > $ABINIT_MODEL-prepare.log.$STEP
-		done
-	fi
-fi
-###SHELLPACK init_complete
-cd Work || die "Failed to change to work directory"
-if [ "$ABINIT_PREPARE" = "yes" ]; then
-	STAGE_MAP=$RUN_STAGE_MAP
-else
-	STAGE_MAP="$PREPARE_STAGE_MAP
-$RUN_STAGE_MAP"
-fi
+for STAGE in `echo $PREPARE_STAGE_MAP`; do
+	echo === MARK PREPARE $STEP $STAGE >> prepare-$STEP-$STAGE_NAME.log
+	prepare_stage
+	$BENCH_CMD < ../$FILES >> prepare-$STEP-$STAGE_NAME.log
+done
+gzip prepare-$STEP-$STAGE_NAME.log
+###SHELLPACK init_only_end
 
-echo $ABINIT_MAXCPUS > $LOGDIR_RESULTS/scaling-parameters
-BENCH_CMD="$MPIRUN abinit"
+cd $ABI_TESTS/tutoparal/Input/ || die "Failed to cd to $ABI_TESTS/tutoparal/Input/"
+export LD_LIBRARY_PATH="$SHELLPACK_SOURCES/abinitdeps-installed/$MMTESTS_LIBDIR:$SHELLPACK_SOURCES/abinitdeps-installed/$MMTESTS_LIBDIR:$LD_LIBRARY_PATH"
+export PATH=$SHELLPACK_SOURCES/abinitdeps-installed/bin:$PATH
+STAGE_MAP=$RUN_STAGE_MAP
+
 log_runtime "OMP_NUM_THREADS=$ABINIT_THREADS"
 log_runtime "OMP_PLACES=$OMP_PLACES"
 log_runtime "OMP_PROC_BIND=$OMP_PROC_BIND"
 log_cmd "$BENCH_CMD"
 log_linkages $SHELLPACK_SOURCES/abinitdeps-installed/bin/abinit
-for STAGE in `echo $STAGE_MAP`; do
+for STAGE in `echo $RUN_STAGE_MAP`; do
+	echo Preparing $STAGE
 	prepare_stage
-	
+
 	echo Executing $STAGE
-	monitor_pre_hook $LOGDIR_RESULTS $ABINIT_MODEL-stage-$STEP
-	eval $TIME_CMD -o $LOGDIR_RESULTS/abinit-time.$STEP	\
-		$BENCH_CMD < ../$FILES > $ABINIT_MODEL-log.$STEP
-	monitor_post_hook $LOGDIR_RESULTS $ABINIT_MODEL-stage-$STEP
+	mmtests_activity start-$STEP-$STAGE_NAME
+	monitor_pre_hook $LOGDIR_RESULTS $STEP-$STAGE_NAME
+	$TIME_CMD -o $LOGDIR_RESULTS/execute-$STEP-$STAGE_NAME.time	\
+		$BENCH_CMD < ../$FILES > execute-$STEP-$STAGE_NAME.log
+	monitor_post_hook $LOGDIR_RESULTS $STEP-$STAGE_NAME
+	mmtests_activity finish-$STEP-$STAGE_NAME
 
 	if [ $? -ne 0 ]; then
 		die "Failed to execute stage $STEP of $ABINIT_MODEL"
 	fi
-	mv $ABINIT_MODEL-prepare.log.* $LOGDIR_RESULTS/
-	mv $ABINIT_MODEL-log.* $LOGDIR_RESULTS
-	gzip $LOGDIR_RESULTS/$ABINIT_MODEL-prepare.log.*
-	gzip $LOGDIR_RESULTS/$ABINIT_MODEL-log.*
-	for FILE in `ls *.out`; do
-		mv $FILE $LOGDIR_RESULTS/$FILE
-		gzip $LOGDIR_RESULTS/$FILE
-	done
+	tar -cJf $LOGDIR_RESULTS/logs.tar.xz *.log
 done
 
 exit $SHELLPACK_SUCCESS
