hpc: Update openmpi version
Signed-off-by: Mel Gorman <mgorman@techsingularity.net>

diff --git a/shellpack_src/src/hpcg/hpcg-bench b/shellpack_src/src/hpcg/hpcg-bench
--- a/shellpack_src/src/hpcg/hpcg-bench
+++ b/shellpack_src/src/hpcg/hpcg-bench
@@ -1,7 +1,18 @@
 #!/bin/bash
 # This is the script for running the HPCG benchmark
 #
-###SHELLPACK preamble hpcg-bench 3.0
+###SHELLPACK preamble hpcg-bench 3.1
+
+if [ "$HPCG_OPENMPI_VERSION" != "" ]; then
+	install-depends $HPCG_OPENMPI_VERSION $HPCG_OPENMPI_VERSION-devel
+	if [ $? -ne 0 ]; then
+		echo WARNING: Falling back to openmpi1
+		export HPCG_OPENMPI_VERSION_NEW=openmpi
+		export HPCG_MPI_PATH=`echo $HPCG_MPI_PATH | sed -e "s@/$HPCG_OPENMPI_VERSION/$HPCG_OPENMPI_VERSION_NEW/g"`
+		export HPCG_OPENMPI_VERSION=$HPCG_OPENMPI_VERSION_NEW
+		install-depends $HPCG_OPENMPI_VERSION $HPCG_OPENMPI_VERSION-devel
+	fi
+fi
 
 MPIRUN=
 MPIOPT=
@@ -25,7 +36,7 @@ template_set_param() {
 }
 
 ulimit -n 4096
-MPICPUS=$(round_down_power_2 $NUMCPUS)
+MPICPUS=$(round_down_power_2 $HPCG_MAX_CPUS)
 
 # Configure build template
 case $HPCG_PARALLELISE in
@@ -39,7 +50,7 @@ gcc-mpi)
 	TEMPLATE=Linux_MPI
 	unset OMP_NUM_THREADS
 	MPIRUN=$HPCG_MPI_PATH/mpirun
-	MPIOPT="--allow-run-as-root -mca btl ^openib,udapl -np $MPICPUS"
+	MPIOPT="$HPCG_MPI_OPTS -mca btl ^openib,udapl -np $MPICPUS"
 	template_set_param CXX   $HPCG_MPI_PATH/mpicxx
 	template_set_param MPdir $HPCG_MPI_PATH
 	template_set_param MPlib ""
@@ -61,15 +72,15 @@ serial)
 	unset MPIOPT
 	;;
 *)
-	die  Unsupported parallelise option $HPCG_PARALLELISE
+	die "Unsupported parallelise option $HPCG_PARALLELISE"
 	;;
 esac
-make clean || die Failed to clean hpcg
+make clean || die "Failed to clean hpcg"
 make arch=$TEMPLATE
 if [ $? -ne 0 ]; then
 	echo Attempting build with g++ 4.8
 	install-depends gcc48-c++
-	make CXX=g++-4.8 arch=$TEMPLATE || die Failed to build hpcg
+	make CXX=g++-4.8 arch=$TEMPLATE || die "Failed to build hpcg"
 fi
 
 # Configure benchmark
@@ -84,9 +95,8 @@ monitor_pre_hook $LOGDIR_RESULTS $P
 ###SHELLPACK iteration_begin $HPCG_ITERATIONS
 	mmtests_activity hpcg-$ITERATION
 	echo Running hpcg iteration $ITERATION/$HPCG_ITERATIONS cpus $MPICPUS
-	eval $MPIRUN $MPIOPT ./bin/xhpcg 2>&1 | tee $LOGDIR_RESULTS/hpcg-${ITERATION}.raw
-	mv HPCG-Benchmark-*.yaml $LOGDIR_RESULTS/hpcg-${ITERATION}.yaml
-	mv hpcg_log*.txt $LOGDIR_RESULTS/hpcg-${ITERATION}.log
+	eval $MPIRUN $MPIOPT ./bin/xhpcg &> $LOGDIR_RESULTS/hpcg-${ITERATION}.raw
+	mv HPCG-Benchmark_*.txt $LOGDIR_RESULTS/hpcg-${ITERATION}.txt
 ###SHELLPACK iteration_end
 monitor_post_hook $LOGDIR_RESULTS $P
 
