netperf: add ipv6 support
The version of the IP protocol is defined in driver scripts, which is
consistent with the transport layer protocol being defined in driver
scripts. This lead to the need to have a separate driver script for every
combination of a network layer protocol and a transport layer protocol.
The configurations and perl extraction scripts mirror this arrangement.
Configurations without an explicit network layer protocol version were
declared obsolete but kept for the time being to retain compatibility with
existing results.

Signed-off-by: Jiri Wiesner <jwiesner@suse.de>
Signed-off-by: Mel Gorman <mgorman@techsingularity.net>

diff --git a/shellpack_src/src/netperf/netperf-bench b/shellpack_src/src/netperf/netperf-bench
--- a/shellpack_src/src/netperf/netperf-bench
+++ b/shellpack_src/src/netperf/netperf-bench
@@ -1,20 +1,15 @@
 #!/bin/bash
 # This script installs netperf and runs the regression tests
 ###SHELLPACK preamble netperf-bench 2.4.5
-PROTOCOLS="UDP_STREAM TCP_STREAM"
-BUFFER_SIZES="64 128 256 1024 2048 3312 4096 6144 8192 10240 12288 14336 16384"
 
 TASKSET_SERVER=
 TASKSET_CLIENT=
-SERVER_HOST=127.0.0.1
-if [ "$REMOTE_SERVER_HOST" != "" ]; then
-	SERVER_HOST=$REMOTE_SERVER_HOST
-fi
 
 ###SHELLPACK parseargBegin
 ###SHELLPACK parseargInstall
 ###SHELLPACK parseargBindings
 ###SHELLPACK parseargParam    --iterations   ITERATIONS
+###SHELLPACK parseargParam    --net-protocol NET_PROTOCOL
 ###SHELLPACK parseargParam    --protocol     PROTOCOL
 ###SHELLPACK parseargParam    --buffer-sizes BUFFER_SIZES
 ###SHELLPACK parseargParam    --nr-pairs     NR_PAIRS
@@ -23,6 +18,20 @@ fi
 
 ###SHELLPACK check_install_required netperf-${VERSION}
 ###SHELLPACK init_complete
+
+case $NET_PROTOCOL in
+ipv4)
+	NET_PROTOCOL_OPT=-4
+	SERVER_HOST=127.0.0.1
+	;;
+ipv6)
+	NET_PROTOCOL_OPT=-6
+	SERVER_HOST=::1
+	;;
+esac
+if [ "$REMOTE_SERVER_HOST" != "" ]; then
+	SERVER_HOST=$REMOTE_SERVER_HOST
+fi
 
 BUFFER_SIZES=`echo $BUFFER_SIZES | sed -e 's/,/ /g'`
 
@@ -36,7 +45,8 @@ start)
 	mmtests_activity netperf-$SERVERSIDE_NAME
 	monitor_pre_hook $LOGDIR_RESULTS netperf-$SERVERSIDE_NAME
 	NETROOT=$SHELLPACK_SOURCES/netperf-${VERSION}-installed 
-	$TASKSET_SERVER $NETROOT/bin/netserver || die Failed to start netserver
+	$TASKSET_SERVER $NETROOT/bin/netserver $NET_PROTOCOL_OPT \
+		|| die Failed to start netserver
 	sleep 2
 	exit $SHELLPACK_SUCCESS
 	;;
@@ -55,7 +65,8 @@ none)
 
 	echo Starting server
 	NETROOT=$SHELLPACK_SOURCES/netperf-${VERSION}-installed 
-	$TASKSET_SERVER $NETROOT/bin/netserver || die "Failed to start netserver"
+	$TASKSET_SERVER $NETROOT/bin/netserver $NET_PROTOCOL_OPT \
+		|| die "Failed to start netserver"
 	sleep 2
 	;;
 *)
@@ -90,6 +101,7 @@ mmtests_server_ctl start --serverside-name $PROTOCOL-$SIZE
 	
 	echo Running test $PROTOCOL iteration $ITERATION/$ITERATIONS size $SIZE nr_pairs $NR_PAIRS
 	NETPERF_OPTS="\
+		$NET_PROTOCOL_OPT \
 		-t $PROTOCOL \
 		-i 3,3 -I 95,5 \
 		-H $SERVER_HOST \
