salmon: Build additional dependencies
Signed-off-by: Mel Gorman <mgorman@techsingularity.net>

diff --git a/shellpack_src/src/salmon/salmon-bench b/shellpack_src/src/salmon/salmon-bench
--- a/shellpack_src/src/salmon/salmon-bench
+++ b/shellpack_src/src/salmon/salmon-bench
@@ -11,6 +11,7 @@
 export CMAKE_VERSION="v3.8.2"
 export BLAS_VERSION="v0.3.10"
 export SCALAPACK_VERSION="2.1.0"
+export XC_VERSION="4.2.1"
 
 MPIRUN=
 if [ "$SALMON_OPENMPI_VERSION" != "" ]; then
@@ -21,11 +22,10 @@ if [ "$SALMON_OPENMPI_VERSION" != "" ]; then
 fi
 
 rm -rf $SHELLPACK_SOURCES/salmondeps-installed
-###SHELLPACK check_external_install_required cmakebuild      cmakebuild-${CMAKE_VERSION} ${CMAKE_VERSION}
-###SHELLPACK install_merge cmakebuild-${CMAKE_VERSION} salmondeps-installed
-###SHELLPACK check_external_install_required blasbuild      blasbuild-${BLAS_VERSION} ${BLAS_VERSION}
-###SHELLPACK install_merge blasbuild-${BLAS_VERSION} salmondeps-installed
+###SHELLPACK check_external_install_required cmakebuild     cmakebuild-${CMAKE_VERSION}         ${CMAKE_VERSION}
+###SHELLPACK check_external_install_required blasbuild      blasbuild-${BLAS_VERSION}           ${BLAS_VERSION}
 ###SHELLPACK check_external_install_required scalapackbuild scalapackbuild-${SCALAPACK_VERSION} ${SCALAPACK_VERSION}
+###SHELLPACK check_external_install_required xcbuild        xcbuild-${XC_VERSION}               ${XC_VERSION}
 ###SHELLPACK install_merge scalapackbuild-${SCALAPACK_VERSION}  salmondeps-installed
 
 export PATH=$SHELLPACK_SOURCES/salmondeps-installed/bin:$PATH
@@ -55,19 +55,13 @@ echo $SALMON_MAXCPUS > $LOGDIR_RESULTS/scaling-parameters
 cd $INPUT_DIR || die "Failed to change to $INPUT_DIR"
 monitor_pre_hook $LOGDIR_RESULTS $SALMON_MODEL
 ###SHELLPACK iteration_begin $SALMON_ITERATIONS
-	RET=-1
-	ATTEMPT=0
-	while [ $RET -ne 0 -a $ATTEMPT -lt 10 ]; do
-		ATTEMPT=$((ATTEMPT+1))
-		echo Executing iteration $ITERATION/$SALMON_ITERATIONS attempt $ATTEMPT
-		eval $TIME_CMD -o $LOGDIR_RESULTS/salmon-time.$ITERATION	\
-			$BENCH_CMD < $INPUT > $LOGDIR_RESULTS/salmon-log.$ITERATION
-		RET=$?
-		echo $ATTEMPT > $LOGDIR_RESULTS/salmon-attempts.$ITERATION
-	done
+	echo Executing iteration $ITERATION/$SALMON_ITERATIONS
+	eval $TIME_CMD -o $LOGDIR_RESULTS/salmon-time.$ITERATION	\
+		$BENCH_CMD < $INPUT > $LOGDIR_RESULTS/salmon-log.$ITERATION
+	RET=$?
 	gzip $LOGDIR_RESULTS/salmon-log.$ITERATION
-	if [ $ATTEMPT -eq 10 ]; then
-		die "Failed to run salmon after 10 attempts"
+	if [ $RET -ne 0 ]; then
+		die "Failed to execute salmon"
 	fi
 ###SHELLPACK iteration_end
 monitor_post_hook $LOGDIR_RESULTS $SALMON_MODEL
diff --git a/shellpack_src/src/wrf/wrf-bench b/shellpack_src/src/wrf/wrf-bench
--- a/shellpack_src/src/wrf/wrf-bench
+++ b/shellpack_src/src/wrf/wrf-bench
@@ -34,9 +34,21 @@ case $WRF_MODEL in
 conus12km)
 	if [ ! -e $SHELLPACK_SOURCES/wrf-$VERSION-installed/test/em_real_bench ]; then
 		cd $SHELLPACK_SOURCES/wrf-$VERSION-installed/test || die "Failed to change to test directory"
-		file_fetch UNAVAILABLE/conus12km_data_v3.tar.xz $MIRROR_LOCATION/conus12km_data_v3.tar.xz conus12km_data_v3.tar.xz
 		cp -r em_real em_real_bench
-		tar -xf conus12km_data_v3.tar.xz || die "Failed to extract conus12km"
+		wget -q -O $SHELLPACK_SOURCES/conus12km_data_v3.tar.xz $MIRROR_LOCATION/conus12km_data_v3.tar.xz
+		if [ $? -ne 0 ]; then
+			BENCH_ROOT="https://www2.mmm.ucar.edu/WG2bench/conus12km_data_v3/"
+			FILELIST="em_real_bench/namelist.input em_real_bench/sample_diffwrf_output.txt em_real_bench/wrfbdy_d01 em_real_bench/wrf_reference em_real_bench/wrfrst_d01_2001-10-25_00_00_00"
+			for FILE in $FILELIST; do
+				wget -O $FILE $BENCH_ROOT/`basename $FILE`
+				if [ $? -ne 0 ]; then
+					die "Failed to download $BENCH_ROOT/$FILE"
+				fi
+			done
+			echo Creating $SHELLPACK_SOURCES/conus12km_data_v3.tar.xz, suggest uploading to a local mirror
+			tar -Jcf $SHELLPACK_SOURCES/conus12km_data_v3.tar.xz $FILELIST
+		fi
+		tar -xf $SHELLPACK_SOURCES/conus12km_data_v3.tar.xz || die "Failed to extract conus12km_data_v3"
 	fi
 	;;
 *)
