pgbench,sysbench: Optionally disable DB reload on large memory configs
Signed-off-by: Mel Gorman <mgorman@suse.de>

diff --git a/shellpack_src/src/pgbench/pgbench-bench b/shellpack_src/src/pgbench/pgbench-bench
--- a/shellpack_src/src/pgbench/pgbench-bench
+++ b/shellpack_src/src/pgbench/pgbench-bench
@@ -105,6 +105,8 @@ echo o scale factor: $SCALE_FACTOR
 echo o transactions: $MAX_TRANSACTIONS
 echo $SCALE_FACTOR > $LOGDIR_RESULTS/pgbench-scale
 
+FIRST_TIME=yes
+
 ###SHELLPACK threads_large_stride_begin 1 $MAX_THREADS
 	echo -n > $LOGDIR_RESULTS/samples
 
@@ -116,28 +118,31 @@ echo $SCALE_FACTOR > $LOGDIR_RESULTS/pgbench-scale
 		--work_mem $WORK_MEM \
 		-v ${VERSION} || die Failed to get a usable postgres installation
 
-	echo Creating database for thread count $NR_THREADS
-	$PSQL "template1 -c 'CREATE DATABASE pgbench;'"
-	if [ $? -ne 0 ]; then
-		echo " o Database create returned $?"
-		echo " o Dumping previous runs database"
-		$RUNDBUSER "$PSQL template1 -c 'DROP DATABASE pgbench;'"
-		echo " o Re-creating database"
-		$RUNDBUSER "$PSQL template1 -c 'CREATE DATABASE pgbench;'" || die Failed to setup database
-	fi
+	if [ "$MMTESTS_LARGE_MACHINE" != "yes" -o "$FIRST_TIME" = "yes" ]; then
+		echo Creating database for thread count $NR_THREADS
+		$PSQL "template1 -c 'CREATE DATABASE pgbench;'"
+		if [ $? -ne 0 ]; then
+			echo " o Database create returned $?"
+			echo " o Dumping previous runs database"
+			$RUNDBUSER "$PSQL template1 -c 'DROP DATABASE pgbench;'"
+			echo " o Re-creating database"
+			$RUNDBUSER "$PSQL template1 -c 'CREATE DATABASE pgbench;'" || die Failed to setup database
+		fi
 
-	$RUNDBUSER "$PSQL template1 -c 'CREATE ROLE $ROLE with LOGIN;'"
-	if [ $? -ne 0 ]; then
-		echo " o Role create returned $?"
-		$RUNDBUSER "$PSQL template1 -c 'DROP ROLE $ROLE;'"
-		$RUNDBUSER "$PSQL template1 -c 'CREATE ROLE $ROLE with LOGIN;'" || die Failed to create $ROLE role
-	fi
+		$RUNDBUSER "$PSQL template1 -c 'CREATE ROLE $ROLE with LOGIN;'"
+		if [ $? -ne 0 ]; then
+			echo " o Role create returned $?"
+			$RUNDBUSER "$PSQL template1 -c 'DROP ROLE $ROLE;'"
+			$RUNDBUSER "$PSQL template1 -c 'CREATE ROLE $ROLE with LOGIN;'" || die Failed to create $ROLE role
+		fi
 
-	echo Initialising database for pgbench: Scale factor $SCALE_FACTOR
-	$TIME_CMD -o $LOGDIR_RESULTS/load-${NR_THREADS}.time \
-		pgbench -h $PGHOST -p $PGPORT \
-			-i $VACUUM_ARG -s $SCALE_FACTOR pgbench \
-			> $LOGDIR_RESULTS/load-${NR_THREADS}.log 2>&1
+		echo Initialising database for pgbench: Scale factor $SCALE_FACTOR
+		$TIME_CMD -o $LOGDIR_RESULTS/load-${NR_THREADS}.time \
+			pgbench -h $PGHOST -p $PGPORT \
+				-i $VACUUM_ARG -s $SCALE_FACTOR pgbench \
+				> $LOGDIR_RESULTS/load-${NR_THREADS}.log 2>&1
+	fi
+	FIRST_TIME=no
 
 	# Work out max time or max transactions commands
 	MAX_TIME_COMMAND=
@@ -169,9 +174,14 @@ echo $SCALE_FACTOR > $LOGDIR_RESULTS/pgbench-scale
 		fi
 	done
 	monitor_post_hook $LOGDIR_RESULTS $NR_THRADS
-	$RUNDBUSER "$PSQL template1 -c 'DROP DATABASE pgbench;'"
-	$RUNDBUSER "$PSQL template1 -c 'DROP ROLE $ROLE;'"
-	$SHELLPACK_INCLUDE/shellpack-bench-postgresbuild --stop
+	if [ "$MMTESTS_LARGE_MACHINE" != "yes" ]; then
+		$RUNDBUSER "$PSQL template1 -c 'DROP DATABASE pgbench;'"
+		$RUNDBUSER "$PSQL template1 -c 'DROP ROLE $ROLE;'"
+		$SHELLPACK_INCLUDE/shellpack-bench-postgresbuild --stop
+	else
+		$SHELLPACK_INCLUDE/shellpack-bench-postgresbuild --stop
+		echo 3 > /proc/sys/vm/drop_caches
+	fi
 ###SHELLPACK threads_stride_end
 
 # Copy the log files
diff --git a/shellpacks/shellpack-bench-sysbench b/shellpacks/shellpack-bench-sysbench
--- a/shellpacks/shellpack-bench-sysbench
+++ b/shellpacks/shellpack-bench-sysbench
@@ -183,6 +183,7 @@ if [ "$TIME_CMD" = "" ]; then
 	TIME_CMD="time"
 fi
 
+FIRST_TIME=yes
 SYSBENCH_OPTIONS="$MAX_TIME_COMMAND $MAX_TRANSACTIONS_COMMAND $SYSBENCH_DB_OPTIONS"
 OLTP_OPTIONS="--test=oltp $OLTP_TRANSTYPE \
 		--oltp-test-mode=$OLTP_TESTTYPE \
@@ -207,22 +208,25 @@ for NR_THREADS in $THREADS; do
 		--shared_buffers $SHARED_BUFFERS \
 		--work_mem $WORK_MEM || die Failed to get usable database installation
 
-	echo Preparing database
-	if [ "$DBDRIVER" = "postgres" ]; then
-		$RUNDBUSER "$PSQL template1 -c 'DROP DATABASE pgtest;'"
-		$RUNDBUSER "$PSQL template1 -c 'DROP ROLE sbtest;'"
-		$RUNDBUSER "$PSQL template1 -c 'CREATE DATABASE pgtest;'" || die Failed to setup database
-		$RUNDBUSER "$PSQL template1 -c 'CREATE ROLE sbtest with LOGIN;'" || die Failed to create sbtest role
-		cp $SHELLPACK_SOURCES/postgresbuild-${POSTGRES_VERSION}-installed/data/postgresql.conf $LOGDIR_RESULTS
-	else
-		eval $MYSQLADMIN -f drop sbtest
-		eval $MYSQLADMIN create sbtest || die Failed to setup database
-		cp /etc/my.cnf $LOGDIR_RESULTS
+	if [ "$MMTESTS_LARGE_MACHINE" != "yes" -o "$FIRST_TIME" = "yes" ]; then
+		echo Preparing database
+		if [ "$DBDRIVER" = "postgres" ]; then
+			$RUNDBUSER "$PSQL template1 -c 'DROP DATABASE pgtest;'"
+			$RUNDBUSER "$PSQL template1 -c 'DROP ROLE sbtest;'"
+			$RUNDBUSER "$PSQL template1 -c 'CREATE DATABASE pgtest;'" || die Failed to setup database
+			$RUNDBUSER "$PSQL template1 -c 'CREATE ROLE sbtest with LOGIN;'" || die Failed to create sbtest role
+			cp $SHELLPACK_SOURCES/postgresbuild-${POSTGRES_VERSION}-installed/data/postgresql.conf $LOGDIR_RESULTS
+		else
+			eval $MYSQLADMIN -f drop sbtest
+			eval $MYSQLADMIN create sbtest || die Failed to setup database
+			cp /etc/my.cnf $LOGDIR_RESULTS
+		fi
+		echo Preparing database: $SYSBENCH_OPTIONS $OLTP_OPTIONS
+		$TIME_CMD -o $LOGDIR_RESULTS/load-${NR_THREADS}.time \
+			sysbench $SYSBENCH_OPTIONS $OLTP_OPTIONS prepare \
+			> $LOGDIR_RESULTS/load-${NR_THREADS}.log
 	fi
-	echo Preparing database: $SYSBENCH_OPTIONS $OLTP_OPTIONS
-	$TIME_CMD -o $LOGDIR_RESULTS/load-${NR_THREADS}.time \
-		sysbench $SYSBENCH_OPTIONS $OLTP_OPTIONS prepare \
-		> $LOGDIR_RESULTS/load-${NR_THREADS}.log
+	FIRST_TIME=no
 
 	monitor_pre_hook $LOGDIR_RESULTS $NR_THREADS
 	for ITER in `seq 1 $MAX_ITERATIONS`; do
@@ -240,6 +244,10 @@ for NR_THREADS in $THREADS; do
 		fi
 	done
 	monitor_post_hook $LOGDIR_RESULTS $NR_THREADS
+
+	if [ "$MMTESTS_LARGE_MACHINE" = "yes" ]; then
+		echo 3 > /proc/sys/vm/drop_caches
+	fi
 done
 
 echo Cleaning database: sysbench $SYSBENCH_OPTIONS --test=oltp $OLTP_OPTIONS cleanup
@@ -259,4 +267,4 @@ $SHELLPACK_INCLUDE/shellpack-bench-${DBDRIVER}build --stop
 echo sysbench successfully completed
 exit $SHELLPACK_SUCCESS
 #### Description Run the sysbench benchmark
-#### Details sysbench-bench 63
+#### Details sysbench-bench 64
