apachebench: create MAINTAINERS.html
Run the apachebench install script from the bench script. The install
script for apachebench does not run and the MAINTAINERS.html file is not
created in the htdocs directory, which leads to apachebench not being able
to detect a regression that is reproducible with a document of roughly 400
KiB in size. Additional clean up of the install script.

Signed-off-by: Jiri Wiesner <jwiesner@suse.de>
Signed-off-by: Mel Gorman <mgorman@techsingularity.net>

diff --git a/shellpack_src/src/apachebench/apachebench-install b/shellpack_src/src/apachebench/apachebench-install
--- a/shellpack_src/src/apachebench/apachebench-install
+++ b/shellpack_src/src/apachebench/apachebench-install
@@ -1,25 +1,19 @@
 #!/bin/bash
 # apachebench installer
 ###SHELLPACK preamble apachebench-install 2.4.39
-WEB_LOCATION=http://download.joedog.org/siege
-MIRROR_LOCATION="$WEBROOT/apachebench/"
-APACHE_VERSION=2.4.39
 
 ###SHELLPACK parseargBegin
 ###SHELLPACK parseargEnd
 
-###SHELLPACK sources_fetch siege-${VERSION}.tar.gz siege-${VERSION}
-if [ ! -e $SHELLPACK_SOURCES/apachebuild-${APACHE_VERSION}-installed ]; then
-	echo Installing apache server
-	$SHELLPACK_TOPLEVEL/shellpack_src/src/refresh.sh apachebuild
-	$SHELLPACK_INCLUDE/shellpack-install-apachebuild -v ${APACHE_VERSION} || die Failed to install apache httpd
-	echo Apache server successfully installed.
-fi
+echo Installing apache server...
+$SHELLPACK_INCLUDE/shellpack-bench-apachebuild || die "Failed to install apache http server."
+
+mkdir -p $SHELLPACK_SOURCES/apachebench-${VERSION}-installed
 
 ###SHELLPACK self_extract MAINTAINERS.html
-mv $SHELLPACK_TEMP/MAINTAINERS.html $SHELLPACK_SOURCES/apachebuild-${APACHE_VERSION}-installed/htdocs/
+mv $SHELLPACK_TEMP/MAINTAINERS.html $SHELLPACK_SOURCES/apachebuild-${VERSION}-installed/htdocs/
 
-echo apachebench successfully
+echo apachebench installed successfully
 exit $SHELLPACK_SUCCESS
 
 ==== BEGIN MAINTAINERS.html ====
