specjvm: Use openjdk
Signed-off-by: Mel Gorman <mgorman@techsingularity.net>

diff --git a/shellpack_src/src/specjvm/specjvm-install b/shellpack_src/src/specjvm/specjvm-install
--- a/shellpack_src/src/specjvm/specjvm-install
+++ b/shellpack_src/src/specjvm/specjvm-install
@@ -1,16 +1,15 @@
 #!/bin/bash
 
-P='specjvm-install'
+###SHELLPACK preamble specjvm 2008
 WEB_LOCATION="NOT_AVAILABLE"
 MIRROR_LOCATION="$WEBROOT/proprietary/spec/SPECjvm2008_1_00_setup.jar"
-export PATH=$SPECJVM_JRE:$PATH
 
-. $SHELLPACK_INCLUDE/common.sh
+for PACKAGE in $SPECJVM_PACKAGES; do
+	install-depends $PACKAGE
+done
 
-cd $SHELLPACK_SOURCES || die Sources directory does not exist
-
+cd $SHELLPACK_SOURCES || die "Sources directory does not exist"
 sources_fetch $WEB_LOCATION $MIRROR_LOCATION $SHELLPACK_SOURCES/SPECjvm2008_1_00_setup.jar
-cd $SHELLPACK_SOURCES
-java -jar SPECjvm2008_1_00_setup.jar -DUSER_INSTALL_DIR=`pwd`/specjvm -i silent || die Failed to install specjvm
+java -jar SPECjvm2008_1_00_setup.jar -DUSER_INSTALL_DIR=`pwd`/specjvm -i silent || die "Failed to install specjvm"
 
 exit $SHELLPACK_SUCCESS
