openfoam: Prototype support for running the motorbike tutorial as a benchmark
Signed-off-by: Mel Gorman <mgorman@techsingularity.net>

diff --git a/shellpack_src/src/nas/nas-bench b/shellpack_src/src/nas/nas-bench
--- a/shellpack_src/src/nas/nas-bench
+++ b/shellpack_src/src/nas/nas-bench
@@ -156,7 +156,7 @@ SUBVERSION=$VERSION
 if [ ! -e $SHELLPACK_SOURCES/nas-$VERSION-installed/NPB$VERSION-$NAS_TYPE ]; then
 	SUBVERSION=`echo $VERSION | sed -e 's/\.[0-9]*$//'`
 fi
-pushd $SHELLPACK_SOURCES/nas-$VERSION-installed/NPB$SUBVERSION-$NAS_TYPE > /dev/null || die Failed to cd to nas-$VERSION-installed/NPB$SUBVERSION-$NAS_TYPE
+pushd $SHELLPACK_SOURCES/nas-$VERSION-installed/NPB$SUBVERSION-$NAS_TYPE > /dev/null || die "Failed to cd to nas-$VERSION-installed/NPB$SUBVERSION-$NAS_TYPE"
 echo -n > config/suite.def
 for JOB in $JOBLIST; do
 	lookup_mpicpus $JOB
diff --git a/shellpack_src/src/openfoam/openfoam-bench b/shellpack_src/src/openfoam/openfoam-bench
--- a/shellpack_src/src/openfoam/openfoam-bench
+++ b/shellpack_src/src/openfoam/openfoam-bench
@@ -4,6 +4,9 @@
 ###SHELLPACK parseargBegin
 ###SHELLPACK parseargInstall
 ###SHELLPACK parseargBindings
+###SHELLPACK parseargParam --max-cpus	OPENFOAM_MAXCPUS
+###SHELLPACK parseargParam --model	OPENFOAM_MODEL
+###SHELLPACK parseargParam --iterations	OPENFOAM_ITERATIONS
 ###SHELLPACK parseargEnd
 ###SHELLPACK monitor_hooks
 
@@ -24,8 +27,91 @@ fi
 if [ "$OPENFOAM_MPI_LIBPATH" != "" ]; then
 	export LD_LIBRARY_PATH=$OPENFOAM_MPI_LIBPATH
 fi
+export OMPI_TMPDIR=$SHELLPACK_DATA
+export TMPDIR=$SHELLPACK_DATA
 
 ###SHELLPACK check_external_install_required openfoambuild openfoambuild-${VERSION} ${VERSION}
 ###SHELLPACK init_complete
+
+cd $SHELLPACK_SOURCES/openfoambuild-$VERSION-installed/ || die "Failed to cd to openfoam installation directory"
+source etc/bashrc "Failed to source bash environment"
+
+# Configure benchmark
+case $OPENFOAM_MODEL in
+motorbike-tutorial)
+	cd tutorials/incompressible/simpleFoam/ || die "Failed to cd to simpleFoam tutorial directory"
+	rm -rf motorBike-mmtests
+	cp -r motorBike motorBike-mmtests
+	cd motorBike-mmtests || die "Failed to cd to motorbike-mmtests tutorial directory"
+
+	SUBDOMAINS=$OPENFOAM_MAXCPUS
+	XDIVISON=0
+	YDIVISION=0
+
+	# Starting from SUBDOMAINs, calculate the maximum subdomains
+	# allowed while maintaining a 3 to 2 ratio for divisions in
+	# the X and Y directions. For example, the default is (3 2)
+	# for 6 subdomains. 12 domains require (4 3).
+	XDIVISION=3
+	YDIVISION=2
+	XMAX=$XDIVISION
+	YMAX=$YDIVISION
+
+	SCALE=1
+	while [ $((3*SCALE)) -lt $OPENFOAM_MAXCPUS ]; do
+		XMAX=$((3*SCALE))
+
+		TESTY=`echo "scale=0; $XMAX / 3 * 2" | bc -l`
+		if [ $((TESTY/2*3)) -ne $XMAX ]; then
+			SCALE=$((SCALE+1))
+			continue
+		fi
+		YMAX=$TESTY
+
+		if [ $((XMAX*YMAX)) -le $OPENFOAM_MAXCPUS ]; then
+			XDIVISION=$XMAX
+			YDIVISION=$YMAX
+		fi
+
+		SCALE=$((SCALE+1))
+	done
+
+	SUBDOMAINS=$((XDIVISION*YDIVISION))
+	echo Scaling parameters
+	echo "o Requested subdomains $OPENFOAM_MAXCPUS"
+	echo "o Actual subdomains    $SUBDOMAINS"
+	echo "o X division           $XDIVISION"
+	echo "o Y division           $YDIVISION"
+	echo "$OPENFOAM_MAXCPUS : $SUBDOMAINS : $XDIVISION x $YDIVISION" > $LOGDIR_RESULTS/scaling-parameters
+
+	# Rewrite benchmark parameters
+	sed -i -e "s/decomposeParDict.6/decomposeParDict.$SUBDOMAINS/" Allrun
+	mv system/decomposeParDict.6 system/decomposeParDict.$SUBDOMAINS
+	sed -i -e "s/numberOfSubdomains.*/numberOfSubdomains $SUBDOMAINS;/" 	system/decomposeParDict.$SUBDOMAINS
+	sed -i -e "s/^    n .*;/    n ($XDIVISION $YDIVISION 1);/"		system/decomposeParDict.$SUBDOMAINS
+
+	chown -R mpiuser:$USERS . &>/dev/null
+
+	;;
+*)
+	die "Unrecognised model $OPENFOAM_MODEL"
+	;;
+esac
+
+# Execute benchmark
+chown -R mpiuser:users $SHELLPACK_DATA
+monitor_pre_hook $LOGDIR_RESULTS $OPENFOAM_MODEL
+###SHELLPACK iteration_begin $OPENFOAM_ITERATIONS
+	echo Executing iteration $ITERATION/$OPENFOAM_ITERATIONS
+	su -p mpiuser -c ./Allclean
+	$TIME_CMD -o $LOGDIR_RESULTS/openfoam-time.$ITERATION	\
+		su -p mpiuser -c ./Allrun 2>&1 | tee $LOGDIR_RESULTS/openfoam-log.$ITERATION
+	gzip $LOGDIR_RESULTS/openfoam-log.$ITERATION
+
+	if [ "$OPENFOAM_SAVEDATA" = "yes" ]; then
+		tar -czf $LOGDIR_RESULTS/openfoam-data-$ITERATION.tar.gz .
+	fi
+###SHELLPACK iteration_end
+monitor_post_hook $LOGDIR_RESULTS $OPENFOAM_MODEL
 
 exit $SHELLPACK_SUCCESS
