nas: Run multiple iterations
Signed-off-by: Mel Gorman <mgorman@techsingularity.net>

diff --git a/shellpack_src/src/nas/nas-bench b/shellpack_src/src/nas/nas-bench
--- a/shellpack_src/src/nas/nas-bench
+++ b/shellpack_src/src/nas/nas-bench
@@ -57,7 +57,8 @@ fi
 		MPIOPT="-mca btl btl_sm_use_cma 1"
 		shift
 		;;
-###SHELLPACK parseargParam --max-cpus NAS_MAX_CPUS
+###SHELLPACK parseargParam --max-cpus   NAS_MAX_CPUS
+###SHELLPACK parseargParam --iterations NAS_ITERATIONS
 ###SHELLPACK parseargEnd
 
 ###SHELLPACK check_install_required nas-$VERSION
@@ -129,33 +130,35 @@ make clean || die "Failed to clean"
 make suite || die "Failed to build"
 
 for JOB in $JOBLIST; do
-	mmtests_activity $JOB
-	if [ "$RUNBITS" = "32" -a ! -x ./bin/$JOB.$NAS_CLASS ]; then
-		echo "Skipping $JOB.$NAS_CLASS"
-		continue
-	fi
+	mmtests_activity $JOB.$NAS_CLASS
+	###SHELLPACK iteration_begin $NAS_ITERATIONS
+		if [ "$RUNBITS" = "32" -a ! -x ./bin/$JOB.$NAS_CLASS ]; then
+			echo "Skipping $JOB.$NAS_CLASS"
+			continue
+		fi
 
-	echo Executing $JOB.$NAS_CLASS
-	monitor_pre_hook $LOGDIR_RESULTS $JOB.$NAS_CLASS
-	case $NAS_TYPE in
-	SER|OMP)
-		eval $TIME_CMD -o $LOGDIR_RESULTS/time-$JOB.$NAS_CLASS.time	\
-			./bin/$JOB.$NAS_CLASS					\
-			> $LOGDIR_RESULTS/$JOB.$NAS_CLASS.log 2>&1
-		;;
-	MPI)
-		eval $TIME_CMD -o $LOGDIR_RESULTS/time-$JOB.$NAS_CLASS.time \
-			mpirun --allow-run-as-root $MPIOPT -np $MPICPUS $MPIRUN_EXTRA ./bin/$JOB.$NAS_CLASS.$MPICPUS \
-			> $LOGDIR_RESULTS/$JOB.$NAS_CLASS.log 2>&1
-		;;
-	esac
+		echo Executing $JOB.$NAS_CLASS iteration $ITERATION/$NAS_ITERATIONS
+		monitor_pre_hook $LOGDIR_RESULTS $JOB.$NAS_CLASS
+		case $NAS_TYPE in
+		SER|OMP)
+			eval $TIME_CMD -o $LOGDIR_RESULTS/time-$JOB.$NAS_CLASS.$ITERATION	\
+				./bin/$JOB.$NAS_CLASS						\
+				> $LOGDIR_RESULTS/$JOB.$NAS_CLASS.log.$ITERATION 2>&1
+			;;
+		MPI)
+			eval $TIME_CMD -o $LOGDIR_RESULTS/time-$JOB.$NAS_CLASS.$ITERATION	\
+				mpirun --allow-run-as-root $MPIOPT -np $MPICPUS $MPIRUN_EXTRA ./bin/$JOB.$NAS_CLASS.$MPICPUS \
+				> $LOGDIR_RESULTS/$JOB.$NAS_CLASS.log.$ITERATION 2>&1
+			;;
+		esac
 
-	if [ $? -ne 0 ]; then
-		die "Failed to execute $JOB.$NAS_CLASS"
-	fi
-	monitor_post_hook $LOGDIR_RESULTS $JOB.$NAS_CLASS
+		if [ $? -ne 0 ]; then
+			die "Failed to execute $JOB.$NAS_CLASS"
+		fi
+		monitor_post_hook $LOGDIR_RESULTS $JOB.$NAS_CLASS
 
-	rm `find -name "ADC.view.dat*"` 2> /dev/null
+		rm `find -name "ADC.view.dat*"` 2> /dev/null
+	###SHELLPACK iteration_end $NAS_ITERATIONS
 done
 
 exit $SHELLPACK_SUCCESS
