filebench: Update download location
Signed-off-by: Mel Gorman <mgorman@techsingularity.net>

diff --git a/shellpack_src/src/filebench/filebench-install b/shellpack_src/src/filebench/filebench-install
--- a/shellpack_src/src/filebench/filebench-install
+++ b/shellpack_src/src/filebench/filebench-install
@@ -1,14 +1,14 @@
 #!/bin/bash
 
 ###SHELLPACK preamble filebench-install 1.4.9.1
-WEB_LOCATION="https://downloads.sourceforge.net/project/filebench/older/filebench-1.4.9.1/filebench-1.4.9.1.tar.gz"
+WEB_LOCATION="https://github.com/filebench/filebench/archive/refs/tags/"
 MIRROR_LOCATION="$WEBROOT/filebench"
 
 ###SHELLPACK parseargBegin
 ###SHELLPACK parseargEnd
 
 rm -rf $SHELLPACK_SOURCES/filebench-${VERSION}
-###SHELLPACK sources_fetch filebench-${VERSION}/filebench-${VERSION}.tar.gz filebench-$VERSION
+###SHELLPACK sources_fetch ${VERSION}.tar.gz filebench-$VERSION
 
 ###SHELLPACK build_start filebench-$VERSION
 
@@ -28,6 +28,9 @@ rm $TEMPFILE
 sed -i -e '/Release the read lock, allowing threads to start/d' parser_gram.y
 sed -i -e '/pthread_rwlock_unlock/d' parser_gram.y
 
+if [ ! -e ./configure ]; then
+	autoreconf --install || die "Failed to run autoreconf"
+fi
 ###SHELLPACK build_configure filebench-${VERSION}
 ###SHELLPACK make_make_install
 
