ltp: Update to 20190115 and add lite configuration
Signed-off-by: Mel Gorman <mgorman@techsingularity.net>

diff --git a/shellpack_src/src/ltp/ltp-bench b/shellpack_src/src/ltp/ltp-bench
--- a/shellpack_src/src/ltp/ltp-bench
+++ b/shellpack_src/src/ltp/ltp-bench
@@ -1,7 +1,8 @@
 #!/bin/bash
 # This script installs ltp and runs the regression tests
-###SHELLPACK preamble ltp-bench full-20120104
+###SHELLPACK preamble ltp-bench 20190115
 LTP_RUN_TESTS="controllers"
+LTP_RUN_ITERATIONS=1
 
 ###SHELLPACK parseargBegin
 ###SHELLPACK parseargInstall
@@ -13,31 +14,27 @@ LTP_RUN_TESTS="controllers"
 ###SHELLPACK check_install_required ltp-${VERSION}
 
 # Run the testsuite
-cd $SHELLPACK_SOURCES/ltp-${VERSION}-installed || die Failed to cd to ltp install directory
-export LTPROOT=`pwd`
-export PATH=$PATH:$LTPROOT/testcases/bin
+cd $SHELLPACK_SOURCES/ltp-${VERSION}-installed || die "Failed to cd to ltp install directory"
+export PATH=$PATH:$SHELLPACK_SOURCES/ltp-${VERSION}-installed/testcases/bin
 
-if [ "$LTP_RUN_ITERATIONS" = "" ]; then
-	LTP_RUN_ITERATIONS=1
-fi
-
-for TEST in $LTP_RUN_TESTS; do
+for TESTNAME in $LTP_RUN_TESTS; do
 	echo Executing $TEST LTP test
 	RESULTS="$LOGDIR_RESULTS"
-	mkdir -p $RESULTS
 
 	for ITER in `seq 1 $LTP_RUN_ITERATIONS`; do
-		if [ "$TEST" = "test-direct-process" ]; then
+		if [ "$TESTNAME" = "test-direct-process" ]; then
 			# This is part of a CPU hotplug reproduction case. It hammers
 			# process creation and is intended as a scheduler stress test
-			( ./testcases/bin/process -b 10 -d 5 || die ltp $TEST failed ) | tee $RESULTS/log-$TEST.txt
-		elif [ -e runtest/$TEST ]; then
-			( ./runltp -f $TEST $LTP_RUN_ARGS 2>&1 || die ltp $TEST failed ) | tee $RESULTS/log-$TEST.txt
-		elif [ -e testcases/bin/$TEST ]; then
-			( ./testcases/bin/$TEST $LTP_RUN_ARGS 2>&1 || die ltp $TEST failed ) | tee $RESULTS/log-$TEST.txt
+			save_rc ./testcases/bin/process -b 10 -d 5 | tee $LOGDIR_RESULTS/ltp-${TESTNAME}.log
+		elif [ -e runtest/$TESTNAME ]; then
+			save_rc ./runltp -f $TESTNAME $LTP_RUN_ARGS  | tee $LOGDIR_RESULTS/ltp-${TESTNAME}.log
+		elif [ -e testcases/bin/$TESTNAME ]; then
+			save_rc ./testcases/bin/$TESTNAME $LTP_RUN_ARGS | tee $LOGDIR_RESULTS/ltp-${TESTNAME}.log
 		else
-			( ./runltp $TEST $LTP_RUN_ARGS 2>&1 || die ltp $TEST failed ) | tee $RESULTS/log-$TEST.txt
+			die "No method available to run $TESTNAME"
 		fi
+		recover_rc
+		echo $? > $LOGDIR_RESULTS/${TESTNAME}.status
 	done
 
 	# Check for failures
diff --git a/shellpacks/shellpack-install-ltp b/shellpacks/shellpack-install-ltp
--- a/shellpacks/shellpack-install-ltp
+++ b/shellpacks/shellpack-install-ltp
@@ -1,17 +1,20 @@
 #!/bin/bash
 # LTP installer
 P=ltp-install
-INSTALL_TESTS=0
-VERSION=
-DEFAULT_VERSION=20150420
-WEB_LOCATION=http://netcologne.dl.sourceforge.net/project/ltp/LTP%20Source
-MIRROR_LOCATION=$WEBROOT/ltp
-LTP_SOURCE_REPO=http://mcp/mmtests-mirror
+DEFAULT_VERSION=20190115
 . $SHELLPACK_INCLUDE/common.sh
+TIME_CMD=`which time`
+if [ "$TIME_CMD" = "" ]; then
+        TIMEFORMAT="%2Uuser %2Ssystem %Relapsed %P%%CPU"
+        TIME_CMD="time"
+fi
+GIT_LOCATION=https://github.com/linux-test-project/ltp
+MIRROR_LOCATION="$WEBROOT/ltp"
 
 # Basic argument parser
 TASKSET_SERVER=
 TASKSET_CLIENT=
+TASKSET_ALL=
 SERVERSIDE_COMMAND=none
 SERVERSIDE_NAME=`date +%Y%m%d-%H%M-%S`
 
@@ -51,12 +54,12 @@ if [ -z "$VERSION" ]; then
 fi
 
 # Unconditionally fetch the tar to find out the real version number
-TARFILE=ltp-full-${VERSION}.tar.bz2
-sources_fetch $WEB_LOCATION/ltp-${VERSION}/$TARFILE $MIRROR_LOCATION/$TARFILE $SHELLPACK_SOURCES/$TARFILE $WEB_LOCATION_ALT/ltp-${VERSION}/$TARFILE
+TARFILE=ltp-${VERSION}.tar.gz
+git_fetch $GIT_LOCATION ltp-$VERSION $MIRROR_LOCATION/$TARFILE $SHELLPACK_SOURCES/$TARFILE $VERSION
 cd $SHELLPACK_SOURCES
 tar -xf $TARFILE
 if [ $? -ne 0 ]; then
-	error "$P: tar xf ltp-full-${VERSION}.tar.bz2 failed"
+	error "$P: tar xf ltp-${VERSION}.tar.gz failed"
 	popd > /dev/null
 	exit $SHELLPACK_ERROR
 fi
@@ -65,10 +68,11 @@ fi
 DST_DIR=`tar tf $TARFILE | head -n 1 | awk -F / '{print $1}'`
 mv $DST_DIR ltp-$VERSION
 pushd ltp-$VERSION > /dev/null || die Failed to rename tar
-pushd $SHELLPACK_SOURCES/ltp-$VERSION || die Failed to change to source directory
+pushd $SHELLPACK_SOURCES/ltp-${VERSION} || die Failed to change to source directory
 for FILE in `find -name "*"`; do
 	touch $FILE
 done
+make autotools || die "Failed to make autotools"
 export CFLAGS="-O2 $CFLAGS_MMTESTS_EXTRA"
 eval ./configure --prefix=$SHELLPACK_SOURCES/ltp-${VERSION}-installed 
 if [ $? -ne 0 ]; then
@@ -97,4 +101,4 @@ fi
 
 echo LTP installed successfully
 #### Description LTP Regression Test Suite
-#### Details ltp 27
+#### Details ltp 32
