cyclictest: Add configuration for running kernel build in the background
Signed-off-by: Mel Gorman <mgorman@techsingularity.net>

diff --git a/shellpack_src/src/cyclictest/cyclictest-bench b/shellpack_src/src/cyclictest/cyclictest-bench
--- a/shellpack_src/src/cyclictest/cyclictest-bench
+++ b/shellpack_src/src/cyclictest/cyclictest-bench
@@ -1,6 +1,9 @@
 #!/bin/bash
 # cyclictest
 ###SHELLPACK preamble cyclictest-bench v1.5
+MIRROR_LOCATION="$WEBROOT/kernbench"
+KERNEL_VERSION=5.2.14
+WEB_LOCATION=https://www.kernel.org/pub/linux/kernel/v5.x
 
 CYCLICTEST_BACKGROUND=none
 
@@ -12,8 +15,35 @@ CYCLICTEST_BACKGROUND=none
 ###SHELLPACK parseargEnd
 ###SHELLPACK monitor_hooks
 
-###SHELLPACK check_external_install_required rttestbuild rttestbuild-${VERSION} ${VERSION}
-###SHELLPACK init_complete
+###SHELLPACK init_only_start
+###SHELLPACK check_external_install_required_continue rttestbuild rttestbuild-${VERSION} ${VERSION}
+
+case $CYCLICTEST_BACKGROUND in
+kernbench)
+	echo Preparing kernel tree for background job
+	cd $SHELLPACK_DATA
+	rm -f ./linux-$KERNEL_VERSION.tar.gz
+	sources_fetch $WEB_LOCATION/linux-$KERNEL_VERSION.tar.gz $MIRROR_LOCATION/linux-$KERNEL_VERSION.tar.gz ./linux-$KERNEL_VERSION.tar.gz
+	tar xf linux-$KERNEL_VERSION.tar.gz || die "Failed to extract"
+	cd linux-$KERNEL_VERSION || die "Unexpected layout"
+	yes '' | make defconfig &>/dev/null || die "Failed to make defconfig"
+	make -j$NUMCPUS clean &> /dev/null
+
+	cat << EOF > build-loop.sh
+	cleanup() {
+		killall -KILL make
+	}
+	trap cleanup EXIT
+	cd $SHELLPACK_DATA/linux-$KERNEL_VERSION
+	while [ 1 ]; do
+		make -j$NUMCPUS vmlinux &> /dev/null
+		make clean &> /dev/null
+	done
+EOF
+	chmod a+x build-loop.sh
+	;;
+esac
+###SHELLPACK init_only_end
 
 cd $SHELLPACK_SOURCES/rttestbuild-${VERSION}-installed || die "Failed to change to rttest directory"
 if [ "$CYCLICTEST_AFFINITY" = "yes" ]; then
@@ -26,6 +56,11 @@ hackbench)
 	./hackbench -P -g $NUMCPUS -l 200000000 &
 	BACKGROUND_PID=$!
 	echo "Background hackbench $PID"
+	;;
+kernbench)
+	$SHELLPACK_DATA/linux-$KERNEL_VERSION/build-loop.sh &
+	BACKGROUND_PID=$!
+	echo "Background kernbench $PID"
 	;;
 none)
 	echo "No background task specified"
