klp: Move cyclictest to a common installation and allow patching of getppid
Patching getppid allows use of perf bench syscall to measure syscall
overhead after live patching of a basic function.

Signed-off-by: Mel Gorman <mgorman@techsingularity.net>

diff --git a/shellpack_src/src/cyclictest/cyclictest-bench b/shellpack_src/src/cyclictest/cyclictest-bench
--- a/shellpack_src/src/cyclictest/cyclictest-bench
+++ b/shellpack_src/src/cyclictest/cyclictest-bench
@@ -17,6 +17,7 @@ CYCLICTEST_BACKGROUND=none
 
 ###SHELLPACK init_only_start
 ###SHELLPACK check_external_install_required rttestbuild rttestbuild-${VERSION} ${VERSION}
+###SHELLPACK check_external_install_required klp         klp-0			0
 
 case $CYCLICTEST_BACKGROUND in
 kernbench)
@@ -43,12 +44,7 @@ EOF
 	chmod a+x build-loop.sh
 	;;
 klp)
-	echo Preparing git repo
-	cd $SHELLPACK_DATA
-	if [ ! -e qa_test_klp ]; then
-		git clone https://github.com/SUSE/qa_test_klp || die "Failed to clone klp repository"
-	fi
-	cd $SHELLPACK_DATA/qa_test_klp || die "Clone but didn't clone, what?"
+	cd $SHELLPACK_SOURCES/klp-0-installed || die "External installation of KLP failed"
 
 	###SHELLPACK self_extract klp_tc_1.sh
 	mv $SHELLPACK_TEMP/klp_tc_1.sh . || die "Failed to self-extract tc-1"
diff --git a/shellpack_src/src/klp/klp-install b/shellpack_src/src/klp/klp-install
--- a/shellpack_src/src/klp/klp-install
+++ b/shellpack_src/src/klp/klp-install
@@ -7,5 +7,25 @@ MIRROR_LOCATION="$WEBROOT/klp/"
 ###SHELLPACK parseargEnd
 
 ###SHELLPACK git_fetch klp-${VERSION}.tar.gz klp-${VERSION}-installed
+cd $SHELLPACK_SOURCES/klp-${VERSION}-installed || die "Failed to change to cloned directory"
+###SHELLPACK self_extract klp_tc_1.sh
+###SHELLPACK self_extract klp_tc_2.sh
+###SHELLPACK self_extract 0001-patch-getppid.patch
+###SHELLPACK self_extract 0002-force-kill-chimem.patch
+
+for SCRIPT in klp_tc_1.sh klp_tc_2.sh; do
+	mv $SHELLPACK_TEMP/$SCRIPT . || die "Failed to self-extract $SCRIPT"
+	chmod a+x $SCRIPT
+done
+
+for PATCH in 0001-patch-getppid.patch 0002-force-kill-chimem.patch; do
+	cat $SHELLPACK_TEMP/$PATCH | patch -p1 || die "Failed to patch $PATCH"
+done
 
 echo klp installed successfully
+exit 0
+
+###SHELLPACK include_file klp_tc_1.sh
+###SHELLPACK include_file klp_tc_2.sh
+###SHELLPACK include_file 0001-patch-getppid.patch
+###SHELLPACK include_file 0002-force-kill-chimem.patch
