stream: Convert to ExtractShellpack.pm
Signed-off-by: Mel Gorman <mgorman@techsingularity.net>

diff --git a/shellpack_src/src/stream/stream-bench b/shellpack_src/src/stream/stream-bench
--- a/shellpack_src/src/stream/stream-bench
+++ b/shellpack_src/src/stream/stream-bench
@@ -5,6 +5,7 @@ install-depends openmpi openmpi-devel openmpi-libs
 install-depends libpsm_infinipath1
 
 STREAM_METHOD=single
+STREAM_THREADS=_
 OPENMP=
 OPENMPI=
 MPICPUS=
@@ -44,23 +45,23 @@ fi
 TASKSET=
 case $STREAM_METHOD in
 single)
-	gcc -DSTREAM_ARRAY_SIZE=$STREAM_ARRAY_ELEMENTS $STREAM_BUILD_FLAGS stream.c -o stream || die Failed to compile stream binary
+	gcc -DSTREAM_ARRAY_SIZE=$STREAM_ARRAY_ELEMENTS $STREAM_BUILD_FLAGS stream.c -o stream || die "Failed to compile stream binary"
 	;;
 single-bind)
-	gcc -DSTREAM_ARRAY_SIZE=$STREAM_ARRAY_ELEMENTS $STREAM_BUILD_FLAGS stream.c -o stream || die Failed to compile stream binary
+	gcc -DSTREAM_ARRAY_SIZE=$STREAM_ARRAY_ELEMENTS $STREAM_BUILD_FLAGS stream.c -o stream || die "Failed to compile stream binary"
 	CPULIST=`cat /sys/devices/system/cpu/cpu1/cache/index3/shared_cpu_list`
 	TASKSET="taskset -c $CPULIST"
 	;;
-
 omp)
-	gcc -DSTREAM_ARRAY_SIZE=$STREAM_ARRAY_ELEMENTS -fopenmp $STREAM_BUILD_FLAGS stream.c -o stream || die Failed to compile stream binary
+	gcc -DSTREAM_ARRAY_SIZE=$STREAM_ARRAY_ELEMENTS -fopenmp $STREAM_BUILD_FLAGS stream.c -o stream || die "Failed to compile stream binary"
 	export OMP_NUM_THREADS=$STREAM_THREADS
 	;;
 esac
 
 monitor_pre_hook $LOGDIR_RESULTS $P
 ###SHELLPACK iteration_begin $STREAM_ITERATIONS
-	eval $TASKSET ./stream 2>&1 | tee $LOGDIR_RESULTS/stream-$ITERATION.log
+	echo Starting iteration $ITERATION/$STREAM_ITERATIONS threads $STREAM_THREADS
+	eval $TASKSET ./stream &> $LOGDIR_RESULTS/benchlog-$STREAM_THREADS-_-$ITERATION
 ###SHELLPACK iteration_end $STREAM_ITERATIONS
 monitor_post_hook $LOGDIR_RESULTS $P
 
