gitcheckout: add a last resort fallback to git.kernel.org
The config we have in configs/ uses $WEBROOT (and $SSHROOT)
which by default point to http://mcp/mmtests-mirror and that
is not available outside of SUSE infra. Of course one can
change that easily enough, but it's equally easy for us to
provide a fallback, in case the mirror is not there. This
way, we can tell users to just run:

  ./run-mmtests -c configs/config-workload-kerndevel TEST0

without having to also ask them to tweak the config file.

Note that I know we have the git_fetch shellpack command
and I tried using it. However, that fetch the repository
in work/sources rather than where we need then (in
work/testdisk/data) and moving the directory afterwords
looked clumsy.

Reported-by: Emilio Bruno <emilio.bruno@edu.unito.it>
Signed-off-by: Dario Faggioli <dfaggioli@suse.com>
Signed-off-by: Mel Gorman <mgorman@techsingularity.net>

diff --git a/shellpack_src/src/gitcheckout/gitcheckout-bench b/shellpack_src/src/gitcheckout/gitcheckout-bench
--- a/shellpack_src/src/gitcheckout/gitcheckout-bench
+++ b/shellpack_src/src/gitcheckout/gitcheckout-bench
@@ -27,6 +27,7 @@ install-depends git-core
 		echo Using $GITCHECKOUT_SOURCETAR
 		wget -q -O gitcheckout.tar.gz $GITCHECKOUT_SOURCETAR
 		if [ $? -ne 0 ]; then
+			echo "Can't retrieve $GITCHECKOUT_SOURCETAR, falling back to $GITCHECKOUT_SOURCE"
 			rm -f gitcheckout.tar.gz
 		fi
 	fi
@@ -39,7 +40,12 @@ install-depends git-core
 		mv $DST_DIR gitcheckout
 	else
 		echo Cloning $GITCHECKOUT_SOURCE
-		git clone $GITCHECKOUT_SOURCE gitcheckout || exit $SHELLPACK_ERROR
+		git clone $GITCHECKOUT_SOURCE gitcheckout
+		if [ $? -ne 0 ]; then
+			GITCHECKOUT_SOURCE=git://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux-2.6
+			echo "Clone failed! Falling back to $GITCHECKOUT_SOURCE"
+			git clone $GITCHECKOUT_SOURCE gitcheckout || exit $SHELLPACK_ERROR
+		fi
 	fi
 ###SHELLPACK init_only_end
 
