run-kvm.sh and bin-virt/*: Improve console output
Improve some existing messages, and add some new ones, for giving the
user a little bit better visibility of what is going on and at what
stage of the benchmark we are.

Signed-off-by: Dario Faggioli <dfaggioli@suse.com>
Signed-off-by: Mel Gorman <mgorman@techsingularity.net>

diff --git a/bin-virt/kvm-ip-address b/bin-virt/kvm-ip-address
--- a/bin-virt/kvm-ip-address
+++ b/bin-virt/kvm-ip-address
@@ -33,7 +33,7 @@ while [ "$GUEST_IP" = "" ]; do
 		CURRENTTIME=`date +%s`
 		RUNNING=$((CURRENTTIME-STARTTIME))
 		if [ $RUNNING -gt $TIMEOUT ]; then
-			echo Timeout exceeded for discovering IP address >&2
+			echo "ERROR: Timeout exceeded for discovering $VM IP address" >&2
 			exit -1
 		fi
 	fi
