thpchallenge: Add kernel build background load
Signed-off-by: Mel Gorman <mgorman@techsingularity.net>

diff --git a/shellpack_src/addon/fragment/lib/kernel-build b/shellpack_src/addon/fragment/lib/kernel-build
--- a/shellpack_src/addon/fragment/lib/kernel-build
+++ b/shellpack_src/addon/fragment/lib/kernel-build
@@ -1,5 +1,5 @@
 # prepare:	Create the kernel files that will be built
-# run:		Build defconfig kernel in a loop, each loop cleans
+# run:		Build kernel in a loop, each loop cleans
 # cleanup:	Shutdown kernel build
 #
 MIRROR_LOCATION="$WEBROOT/kernbench"
@@ -7,12 +7,27 @@ KERNEL_VERSION=5.14
 WEB_LOCATION=https://www.kernel.org/pub/linux/kernel/v5.x
 
 KBUILD_JOBS=$NUMCPUS
+KBUILD_WARMUP=0
+KBUILD_CONFIG=allmodconfig
+KBUILD_WAIT_PHASE=$1
+
+set_kbuild_status() {
+	echo "$@" > /tmp/mmtests-fragment-kernel-build-status
+}
 
 while [ $# -ge 1 ]; do
 	case $1 in
 	--kbuild-jobs)
 		KBUILD_JOBS=$2
 		shift 2
+		;;
+	--kbuild-wait-phase)
+		KBUILD_WAIT_PHASE=$2
+		shift 2
+		;;
+	--kbuild-warmup)
+		KBUILD_WARMUP=1
+		shift
 		;;
 	*)
 		die "Unrecognised $METHOD arg $1"
@@ -21,15 +36,67 @@ while [ $# -ge 1 ]; do
 done
 
 case $COMMAND in
+wait-build-phase)
+	if [ ! -e /tmp/mmtests-fragment-kernel-build-status ]; then
+		die "Unknown state"
+	fi
+	STATUS=`cat /tmp/mmtests-fragment-kernel-build-status`
+	if [ "$STATUS" = "build-$KBUILD_WAIT_PHASE" ]; then
+		exit 0
+	fi
+	echo -n Waiting for kernel-build $KBUILD_WAIT_PHASE phase to start.
+	WAIT=-1
+	while [ "$STATUS" != "build-$KBUILD_WAIT_PHASE" ]; do
+		sleep 1
+		STATUS=`cat /tmp/mmtests-fragment-kernel-build-status`
+		WAIT=$((WAIT+1))
+		if [ $((WAIT%5)) -ne 0 ]; then
+			continue
+		fi
+
+		case $STATUS in
+		prepare-warmup-vmlinux)
+			echo -n V
+			;;
+		prepare-warmup-modules)
+			echo -n M
+			;;
+		build-clean)
+			echo -n c
+			;;
+		build-vmlinux)
+			echo -n v
+			;;
+		build-modules)
+			echo -n m
+			;;
+		*)
+			die "Unrecognised status $STATUS"
+			;;
+		esac
+	done
+	echo
+	;;
 prepare)
 	cd $SHELLPACK_DATA
+	set_kbuild_status prepare
 	if [ ! -e ./linux-$KERNEL_VERSION.tar.xz ]; then
 		sources_fetch $WEB_LOCATION/linux-$KERNEL_VERSION.tar.xz $MIRROR_LOCATION/linux-$KERNEL_VERSION.tar.xz ./linux-$KERNEL_VERSION.tar.xz
 	fi
 	echo Extracting linux-$KERNEL_VERSION.tar.xz
 	tar xf linux-$KERNEL_VERSION.tar.xz || die "Failed to extract"
 	cd linux-$KERNEL_VERSION || die "Unexpected layout"
-	yes '' | make defconfig &>/dev/null || die "Failed to make defconfig"
+	yes '' | make $KBUILD_CONFIG &>/dev/null || die "Failed to make $KBUILD_CONFIG"
+
+	if [ $KBUILD_WARMUP -ne 0 ]; then
+		KBUILD_STATUS="prepare-warmup"
+		echo Prepare warmup build vmlinux
+		set_kbuild_status prepare-warmup-vmlinux
+		make -j$KBUILD_JOBS vmlinux &>/dev/null
+		echo Prepare warmup build modules
+		set_kbuild_status prepare-warmup-modules
+		make -j$KBUILD_JOBS modules &>/dev/null
+	fi
 
 	cat << EOF > build-loop.sh
 #!/bin/bash
@@ -46,11 +113,13 @@ trap cleanup TERM
 cd $SHELLPACK_DATA/linux-$KERNEL_VERSION || exit -1
 rm -f /tmp/mmtests-fragment-kernel-build-exit
 while [ ! -e /tmp/mmtests-fragment-kernel-build-exit ]; do
-	make -j$KBUILD_JOBS clean &> /dev/null
-	make -j$KBUILD_JOBS vmlinux &> /dev/null &
-	KBUILD_PID=\$!
-	echo \$KBUILD_PID > /tmp/mmtests-fragment-kernel-build-make-pid
-	wait
+	for PHASE in clean vmlinux modules; do
+		echo build-\$PHASE > /tmp/mmtests-fragment-kernel-build-status
+		make -j$KBUILD_JOBS \$PHASE &> /dev/null &
+		KBUILD_PID=\$!
+		echo \$KBUILD_PID > /tmp/mmtests-fragment-kernel-build-make-pid
+		wait
+	done
 done
 EOF
 	chmod a+x build-loop.sh
@@ -72,6 +141,7 @@ cleanup)
 	rm -f  /tmp/mmtests-fragment-kernel-build-loop-pid
 	rm -f  /tmp/mmtests-fragment-kernel-build-make-pid
 	rm -f  /tmp/mmtests-fragment-kernel-build-exit
+	rm -f  /tmp/mmtests-fragment-kernel-build-status
 	;;
 esac
 
diff --git a/shellpack_src/src/thpchallenge/thpchallenge-bench b/shellpack_src/src/thpchallenge/thpchallenge-bench
--- a/shellpack_src/src/thpchallenge/thpchallenge-bench
+++ b/shellpack_src/src/thpchallenge/thpchallenge-bench
@@ -4,16 +4,21 @@
 
 export FIO_VERSION="3.33"
 
+THPCHALLENGE_KBUILD_JOBS=$NUMCPUS
+THPCHALLENGE_KBUILD_WARMUP=
+
 MADV_HUGEPAGE=0
 
 ###SHELLPACK parseargBegin
 ###SHELLPACK parseargInstall
 ###SHELLPACK parseargParam	--min-threads	THPCHALLENGE_MIN_THREADS
 ###SHELLPACK parseargParam	--max-threads	THPCHALLENGE_MAX_THREADS
-###SHELLPACK parseargParam	--fio-threads	THPCHALLENGE_FIO_THREADS
 ###SHELLPACK parseargParam	--thp-size	THPCHALLENGE_THP_WSETSIZE
-###SHELLPACK parseargParam	--fio-size	THPCHALLENGE_FIO_WSETSIZE
 ###SHELLPACK parseargParam	--madv-huge	THPCHALLENGE_MADV_HUGEPAGE
+###SHELLPACK parseargParam	--fio-threads	THPCHALLENGE_FIO_THREADS
+###SHELLPACK parseargParam	--fio-size	THPCHALLENGE_FIO_WSETSIZE
+###SHELLPACK parseargParam	--kbuild-jobs	THPCHALLENGE_KBUILD_JOBS
+###SHELLPACK parseargParam	--kbuild-warmup	THPCHALLENGE_KBUILD_WARMUP
 ###SHELLPACK parseargEnd
 ###SHELLPACK monitor_hooks
 
@@ -29,6 +34,14 @@ fio-random-reader-inefficient)
 		--fio-size    $THPCHALLENGE_FIO_WSETSIZE	\
 		--fio-threads $THPCHALLENGE_FIO_THREADS		\
 		--fio-version $FIO_VERSION || die "Failed to prepare $THPCHALLENGE_BACKGROUND"
+	;;
+kernel-build)
+	if [ "$THPCHALLENGE_KBUILD_WARMUP" = "yes" ]; then
+		THPCHALLENGE_KBUILD_WARMUP="--kbuild-warmup"
+	fi
+	fragment prepare --method $THPCHALLENGE_BACKGROUND	\
+		--kbuild-jobs $THPCHALLENGE_KBUILD_JOBS		\
+		$THPCHALLENGE_KBUILD_WARMUP || die "Failed to prepare $THPCHALLENGE_BACKGROUND"
 	;;
 none)
 	echo No background task to prepare
@@ -52,6 +65,10 @@ fio-random-reader-inefficient)
 		--fio-threads $THPCHALLENGE_FIO_THREADS		\
 		--fio-version $FIO_VERSION || die "Failed to run $THPCHALLENGE_BACKGROUND"
 	;;
+kernel-build)
+	fragment run --method $THPCHALLENGE_BACKGROUND		\
+		|| die "Failed to run $THPCHALLENGE_BACKGROUND"
+	;;
 none)
 	echo No background task to prepare
 	;;
@@ -61,18 +78,25 @@ esac
 
 echo Warmup complete
 ###SHELLPACK threads_large_stride_begin $THPCHALLENGE_MIN_THREADS $THPCHALLENGE_MAX_THREADS
+	if [ "$THPCHALLENGE_BACKGROUND" = "kernel-build" ]; then
+		echo Prepare thpchallenge $NR_THREADS/$THPCHALLENGE_MAX_THREADS
+		fragment wait-build-phase --method $THPCHALLENGE_BACKGROUND --kbuild-wait-phase vmlinux
+		fragment wait-build-phase --method $THPCHALLENGE_BACKGROUND --kbuild-wait-phase modules
+	fi
+
 	monitor_pre_hook $LOGDIR_RESULTS $NR_THREADS
-	echo Starting thpchallenge $NR_THREADS/$THPCHALLENGE_MAX_THREADS size:$THPCHALLENGE_THP_WSETSIZE madv:$MADV_HUGEPAGE
+	echo Starting thpchallenge $NR_THREADS/$THPCHALLENGE_MAX_THREADS size:$((THPCHALLENGE_THP_WSETSIZE/1048576))MB madv:$MADV_HUGEPAGE
 	$TIME_CMD -o $LOGDIR_RESULTS/threads-${NR_THREADS}.time \
 		./thpchallenge $NR_THREADS $THPCHALLENGE_THP_WSETSIZE $MADV_HUGEPAGE \
 			> $LOGDIR_RESULTS/threads-${NR_THREADS}.log 2>&1
 	monitor_post_hook $LOGDIR_RESULTS $NR_THREADS
+	echo Complete thpchallenge $NR_THREADS/$THPCHALLENGE_MAX_THREADS
 	gzip $LOGDIR_RESULTS/threads-${NR_THREADS}.log
 ###SHELLPACK threads_stride_end
 echo Finished thpchallenge
 
 case $THPCHALLENGE_BACKGROUND in
-fio-random-reader-inefficient)
+fio-random-reader-inefficient|kernel-build)
 	fragment cleanup --method $THPCHALLENGE_BACKGROUND
 	;;
 none)
